### ISSUE TITLE
[NOT ISSUE] MO is dead....

### ISSUE THREAD

**Issue by SiTWulf** [TanninOne/modorganizer#1009]
Now this incredible Mod Manager is Dead.
More info in here: http://www.nexusmods.com/fallout4/news/12905/?

**Comment by Akzyra** [comment]
This is old news...
This is a issue tracker, putting "not issue" in the title is just wrong.

**Comment by AronaxAE** [comment]
This has been known for a while now, not news at all. There are people trying to folk MO right now and make a fully playable version but for now we have http://www.nexusmods.com/skyrimspecialedition/mods/1725 which works completely fine until we get a full stable version from someone else.
