### ISSUE TITLE
Moving Directory to Other Drive

### ISSUE THREAD

**Issue by InfinateX** [TanninOne/modorganizer#1014]
I may have done something wrong when I tried to do this, but I wanted to move my MO downloads and everything else off of my SSD to save a lot of space on it. My SSD has my OS install and some of the slower programs that run on my computer, so I want to free up some space on it in case I need to install anything else on it. I tried to move the folder and change the directories in MO, but then it bugged out the application. I had to put everything back. Is there a way I can move all of that stuff off of my OS drive?

**Comment by ArcadiaFell** [comment]
I did this rather recently. If you are using MO2, it is definitely done here.
http://puu.sh/soixa/e689567978.png
Click the ... next to Base Directory.
Once you have changed the directory, you need to cut and paste the files from the original directory to the new one.
Rinse and repeat for each game.

For MO (not 2), I'd imagine it would be similar, but I am not entirely sure.

**Comment by InfinateX** [comment]
That's what I did, but then Mod Organizer stopped recognizing my Fallout 4 install. I have no idea why it wouldn't be able to do that, but for some reason it can't.

**Comment by InfinateX** [comment]
Not sure what I did, but I kept playing around with it, copying and pasting files to new locations, deleting important files then redoing things, and stuff like that, then I got it to work. It eventually stopped giving me that error. I'm really not sure why it worked though. Guess I'll just accept it though.
