### ISSUE TITLE
Some undefined function

### ISSUE THREAD

**Issue by enpinion** [TanninOne/modorganizer#1028]
commit=5ae681e | branch=new_vfs_library
src/
organizercode.cpp:1242
`  while (
      res = ::MsgWaitForMultipleObjects(1, &handle, false, 500,
                                        QS_KEY | QS_MOUSE),
      (MOBase::isOneOf(res, {WAIT_FAILED, WAIT_OBJECT_0}) &&
       ((m_UserInterface == nullptr) || !m_UserInterface->unlockClicked()))) {`

usvfsconnector.cpp:104
`UsvfsConnector::UsvfsConnector()
{
  USVFSParameters params;
  LogLevel level = logLevel(Settings::instance().logLevel());
  USVFSInitParameters(&params, SHMID, false, level);
  InitLogging(false);
  CreateVFS(&params);
  SetLogLevel(level);`

It seems there are some missing functions:
`CreateVFS()` in usvfsconnector.cpp
`isOneOf()` in organizercore.cpp

Or is there anything require to compile MO?

**Comment by LePresidente** [comment]
Read through issue 998 and 995 for help regarding this.

**Comment by enpinion** [comment]
Thanks, I never knew he commit a upstream code since I clone the repo a month ago.
