### ISSUE TITLE
SkyrimSE doesn't see any mods.(2.0.8b)

### ISSUE THREAD

**Issue by BlayeeR** [TanninOne/modorganizer#1033]
So there's a big issue but I don't know if I can explain it correctly.

With correct plugins.txt(edited it manually and it matches my load order from MO2- both in MO2 profile and %localappdata%/skyrim special edition) my game doesnt see any mods. I tried various ways of editing plugins.txt but that doesnt help. When I copied one of my mods .esp to data folder and launched game through MO2 it recognized this mod(like plugins.txt works good, but vfs dont pass mod files correctly?). It seems like there is some problem with virtualization? 
LOOT and SSEEdit see mods correctly(but loot doesnt update loadorder.txt).

And is it normal for SSE to everytime launch launcher even through SkyrimSE.exe?

**Comment by BlayeeR** [comment]
Looks like problem exist for Fallout 4 too(tested by myself) and Skyrim #1029 on 1.3.11(hows that possible?)

**Comment by BlayeeR** [comment]
I don't know why but it works like charm today. I literally didnt do nothing since I approached this problem

**Comment by Omega1084** [comment]
Any idea of what you did to fix it? Anything at all that changed?
I've reinstalled both MO and now ALL MY MODS from scratch along with a clean install of Skyrim and I still CTD like I'm missing my ESPs.
