### ISSUE TITLE
Configurator error Skyrim SE

### ISSUE THREAD

**Issue by Chrisands** [TanninOne/modorganizer#1044]
![2016-12-16](https://cloud.githubusercontent.com/assets/12214583/21260546/7af9d270-c397-11e6-90ff-2773659d2ef5.png)
Windows 10 x64

**Comment by GSDFan** [comment]
This feature may not be fully developed, but you have to have "Local Game Settings" checked in the profile in order for the configurator to work. You get there from configure profiles, click on the profile you want and select the local game settings option. 

With this MO will write the ini files to the profile and when unchecker rename them with and underscore character.
