### ISSUE TITLE
Random textures not loading and random CTD

### ISSUE THREAD

**Issue by Jeremiahp15** [TanninOne/modorganizer#1090]
I have a problem with mod organizer randomly not loading all mods, by that i mean sometimes skin textures are purple, sometimes black, sometimes animals are purple (not modded), sometimes a npc is full purple (weapons, armors, skin, face, everything). if i reboot the game maybe everything goes well or maybe not. my other issue, could be related, is that i get random CTD. its not specific to a location or event, just completely random. I'm not sure if Mod organizer has a limit to mods or files it can load (i have about 100 mods) or if there's something i setup wrong. has happened since i switched to MO (reinstalled all mods through MO)

**Comment by gerbilOFdoom** [comment]
This is most likely an issue with conflicting mods. Make sure your mod order is sorted with LOOT and also make sure you've created a Bashed patch.

More information on how to use Mod Organizer [here](http://wiki.step-project.com/Guide:Mod_Organizer)

**Comment by Jeremiahp15** [comment]
I've done all of that. not only that but like i said, some texture that go purple are objects I never modified. like animals, or the texture for items on floor, or rugs, beds, furniture.

**Comment by gerbilOFdoom** [comment]
Which game and version of MO are you using?

It might help to use [LePresidente's branch](https://github.com/LePresidente/modorganizer/releases)

**Comment by Jeremiahp15** [comment]
I'm using 1.3.11 (not beta) for Skyrim. I've done everything i could think of to solve it but i can't get rid it.Most mods i'm using are the same I had before resetting windows. I do however use the beta for Fallout 4 (the one you suggested) is there a way to use the beta MO for both games?

**Comment by gerbilOFdoom** [comment]
You could try MO2 in Skyrim by creating an extra install directory, ideally outside of the Program Files folders but I'm not certain it will help. Also, on the off chance that there's some sort of corruption could you verify the game cache if you have steam or otherwise reinstall skyrim?

**Comment by Jeremiahp15** [comment]
yeah i did verify. when i did the bash it did help a lot, but the problem still happens, weird thing is that i think not every same object gets the purple texture, or sometimes also missing alpha textures. i played today for about 3 hrs without purple texture, when i got to a bar in riften, almost everyones clothes was purple, but i didn't see any purple clothes in any other cities.
