### ISSUE TITLE
USVFS_Proxy Command Window will not Close

### ISSUE THREAD

**Issue by SkyeRangerDelta** [TanninOne/modorganizer#1118]
**Issue Cause:** running a 32x Program in MO2.
**Description:** this _usvfs_proxy.exe_ command prompt window has no interest in closing whatsoever. Even under end task via Task Manager and SuperF4. MO2 was running SSELODGen for SkyrimSE when the window opened and I can not close it whatsoever.

This screenshot is the window that will not close.
![screenshot_1](https://user-images.githubusercontent.com/12277949/28504633-59db2db6-6fe8-11e7-90e6-2869ea65c7fa.png)

**Comment by wcxaaa** [comment]
Could close that via Ctrl + C.
