### ISSUE TITLE
Problem with installing FNIS.

### ISSUE THREAD

**Issue by PublicMenace** [TanninOne/modorganizer#1120]
When I hit ''Update FNIS behaviour'' there are always three files generated in my Overwrite mod.How can I stop that? It's always these in the attached screenshot. I've just switched to MO today so i'm still a newbie and this could be a ridiculously easy to fix issue but I couldn't find anything about it. I've already tried just dragging the files into the FNIS mod but that doesn't fix it, the files keep getting generated.
![image](https://user-images.githubusercontent.com/24361954/28849502-8d260db8-7717-11e7-8edc-85a56ebb7533.png)

**Comment by JamesYeoman** [comment]
That is supposed to happen. That is what FNIS generates. You need to right-click the Overwrite Mod and click Create Mod and let it overwrite FNIS
