### ISSUE TITLE
No Skyrim Special Edition plugin?

### ISSUE THREAD

**Issue by Zentharius** [TanninOne/modorganizer#1161]
I have used Mod Organizer for almost 5 years now, and when I finally decided to upgrade to Special Edition(for the sole purpose of mod support) I tried getting MO 2.0.7. After downloading I didn't see a Skyrim Special edition plugin, but just thought that it was standard. There was a skyrim plugin, but I didn't really think about it. When I try to open it, it simply has a message saying "Plugin to handle Skyrim Special Edition no longer installed", and proceeds to close itself. I can provide video of the install of it to see if I'm doing something wrong, but otherwise I would like to know if I have to install a plugin from somewhere else, or if I need to reinstall SSE or whatever else needs to happen.

**Comment by SuperSandro2000** [comment]
This is the old repo and is no longer maintained. Please refer to this one https://github.com/LePresidente/modorganizer
It has working Skyrim special edition out of the box and the current version is 2.1.1.
