### ISSUE TITLE
[Skyrim LE] Issue with installing FNIS 7.2

### ISSUE THREAD

**Issue by MrLinguist** [TanninOne/modorganizer#1174]
Yo, trying to run FNIS 7.2 with Mod Organizer and I keep getting the following error:
failed to inject dll into "GenerateFNISforUsers.exe": failed to access thread context. Please note that Mod Organizer does not support 64bit binaries! (The parameter is incorrect. [87]). I'm just installing it the same way I normally would; hitting the "Download with Manager" button on the page and setting the data directory in MO. I am installing the Oldrim version btw,  Any ideas why this is happening?

**Comment by Zarggg** [comment]
If you're playing the original version of Skyrim, you may consider using the older MO 1.3.11 instead of the newer MO2. There is a guide for setting up FNIS on the STEP Project website that might be useful as well: http://wiki.step-project.com/Fores_New_Idles_in_Skyrim#Recommendations

**Comment by MrLinguist** [comment]
Found the proper version for FNIS. Thanks!
