### ISSUE TITLE
Mod Organizer 2 download speed capped at 1 MB/s despite having premium membership

### ISSUE THREAD

**Issue by nolanmanning703** [TanninOne/modorganizer#1185]
As the title says, my downloads are capped at 1 MB/s in MO2. I'm downloading mods through the Nexus using the "Mod Manager Download" button. I have a premium membership, and if I download manually instead of with the manager I get uncapped speeds. I'm signed into the Nexus with MO2 and I have it set to prefer the North American Premium server, but my mods still refuse to download faster than 1 MB/s.

Do you have any idea why this is happening? Any help would be appreciated.

**Comment by nolanmanning703** [comment]
The issue appears to have resolved itself, so nevermind!

**Comment by SuperSandro2000** [comment]
This is the MO1 repo!
