### ISSUE TITLE
TBG Feature request #1269 (GrantSP on 2015-07-23): Installation of *.fomod files stored inside archives

### ISSUE THREAD

**Issue by TanninOne** [TanninOne/modorganizer#287]
I've just been informed that Nexus doesn't allow *.fomods to be uploaded without them being inside archives. As this requires MO users to manually unzip them before installation I was wondering if it is possible to do this internally.
Maybe the archive could be opened and if it contains a *.fomod the fomod installer is then called.

**Comment by ThosRTanner** [comment]
Can you point to an example? I was poking around in the code and it seems like it ought to do this

**Comment by GrantSP** [comment]
There's a Fallout New Vegas mod called [Interior Lighting Overhaul](http://www.nexusmods.com/newvegas/mods/35794/?)

**Comment by ThosRTanner** [comment]
Ah. That contains an fomod **and** other stuff, all in a subdirectory. Rather than being a zipped fomod. Might be fun, but I will see
