### ISSUE TITLE
TBG Feature request #1329 (selsie on 2015-09-17): Not only Nexus

### ISSUE THREAD

**Issue by TanninOne** [TanninOne/modorganizer#308]
It would be great if 'visit on Nexus' could be replaced by "Visit Site" given that I provided the proper URL on e.g. LL, TEG or other relevant sites for mods without a Nexus ID.

It would of course not be automagically (as nexus), but if I could add the right URL I could easily go and check for updates to my non Nexus mods.

**Comment by TanninOne** [comment]
thosrtanner on 2015-09-18: The web site is actually available for things installed with a fomod installer. Or at least it's available to be remembered. I might have a poke around between game sessions

**Comment by ThosRTanner** [comment]
Note: the above pull requests add the infrastructure to allow URLs to be exposed by an installer (and the fomod one uses it). If you want to add one manually, you can edit the .meta file and a `url=http://etc` line.

**Comment by ThosRTanner** [comment]
um *blush* i forgot to give the pull requests the same name so it might not have been clear all these should have gone together
