### ISSUE TITLE
&#39;

### ISSUE THREAD

**Issue by selsie** [TanninOne/modorganizer#324]
I downloaded a mod from the Nexus with a ' in it.

The file name is shown as ... & # 39 ; s 

To reproduce:
download http://www.nexusmods.com/skyrim/mods/69934/?

**Comment by ThosRTanner** [comment]
A clarification: When you download the mod manually, it displays as

    Velexia's Animals are not Monsters-69934-1-2.rar

Installing this suggests Velexia as a mod name which doesn't seem quite right. Query mod info fails to spot the mod number and you have to enter it manually. And then you get

    Velexia&#39;s Animals are not Monsters (Update, v1.2)

When you install that, you get a suggested mod name of  Velexia&#39;s Animals are not Monsters

**Comment by selsie** [comment]
to make a long story short, MO chokes at '
wherever the name thing is, in the code, it's probably surrounded by ' so a
' means end of name.
