### ISSUE TITLE
Refactor archive library to have more of a qt-style interface and not depend on bits of 7zip code internally

### ISSUE THREAD

**Issue by ThosRTanner** [TanninOne/modorganizer#333]
This is a placeholder to keep the pull requests together

**Comment by ThosRTanner** [comment]
you need to pull the arcive and nmm import requests as well or it wont build

**Comment by TanninOne** [comment]
Yeah, sorry. I was on the train when doing the merge. And then the internet connection was gone.

**Comment by ThosRTanner** [comment]
heh. you have to love trains
