### ISSUE TITLE
I Dont know what is it

### ISSUE THREAD

**Issue by GetGun** [TanninOne/modorganizer#348]
The bug tracker and code repository for Mod Organizer have moved.
Please post bugs to https://github.com/TanninOne/modorganizer/issues now.
Existing open bugs have been imported into that tracker although some state and formatting may have been lost.
The source code has been split into multiple projects on github. Please see here for a complete list: https://github.com/TanninOne/modorganizer

**Comment by TanninOne** [comment]
Is there a question here?

**Comment by GetGun** [comment]
yes?

**Comment by ThosRTanner** [comment]
What is the question? because all you've done is posted the announcement

**Comment by GetGun** [comment]
ok my fault please help :(
