### ISSUE TITLE
Mod Organizer 2 INI Editor not working

### ISSUE THREAD

**Issue by TechAngel85** [TanninOne/modorganizer#367]
Installed MO2 for Skyrim. The Skyrim.ini and the SkyrimPrefs.ini were added to the profile but the INI Editor is not showing any files to edit. It's simply blank. I've verified the INI files are present in the profile folder.

**Comment by Kattmandu** [comment]
I second this.

**Comment by TanninOne** [comment]
Fixed in alpha 2
