### ISSUE TITLE
MO2 won't run

### ISSUE THREAD

**Issue by MrCreeperPhil** [TanninOne/modorganizer#371]
I downloaded the MO2a1 archive, unzipped everything to C:/Mod Organizer, so installation should be okay. However, I can't seem to get ModOrganizer.exe to run. No matter how many times I click/doubleclick the exe file, the only thing that happens is that my explorer window just closes down. I tried running the exe as administrator, tried moving folders, even renamed it to modorganizer.exe (without capital letters), but nothing seems to work. Any help?

**Comment by NoShotz** [comment]
you could try installing it to the game's directory, as i did that with fallout 4 and it worked just fine

**Comment by MrCreeperPhil** [comment]
I just did that, still no result. I did try something else too: I downloaded the 1.3.11 installer from http://www.nexusmods.com/skyrim/mods/1334/? and then I installed the 2alpha1 over it. This resulted in the program launching, prompting me to choose a game, asking me if I wanted the tutorial, to which I responded 'no', but then I got the Python error for the pyCfg.py file and the application crashed.

**Comment by paulholl** [comment]
I'm pretty sure 1.3 and 2,0 are incompatible entirely.  Either way, you can delete the foilder, redownload from here:

https://github.com/TanninOne/modorganizer/releases/download/2.0alpha1/ModOrganizer2a1.7z

And unzip it to your desktop to try again.

**Comment by strangerism** [comment]
I have installed ModOrganizer2a1.7z from GitHub and it worked fine, the only issue was the pyCfg.py library throwing an error at launch, resolved by deleting it. MO is installed on the same drive where the the game is but not the game folder.

**Comment by AciDCooL** [comment]
Tip of the day Mo2 won't work if you have a cusstom dxgi.dll in the folder, rename it to say dxgi.old or something and magic will happen :santa: 
tbf people should try an alpha with the vanilla game without any modification and then start trowing shit at it instead of the other way around :wink:

**Comment by TheGreenDragon** [comment]
I had to white list MO2 in Avast or it would not launch at all, no splash screen or anything.
