### ISSUE TITLE
Plugins.txt/loadorder.txt not being updated/virtually updated

### ISSUE THREAD

**Issue by NoShotz** [TanninOne/modorganizer#374]
The loadorder.txt and plugins.txt files within the mod organizer folder, are not being carried over to the location the default ones in the appdata folder for fallout 4

**Comment by pman11** [comment]
im having the same issue... i have to manually add it to the text files to get the esp's to work in game

**Comment by NoShotz** [comment]
i just copy the files here, https://blam.halo.click/YG47SX.png  into the appdata folder

**Comment by strangerism** [comment]
I tested a couple of esp and they were loaded and working. No need to edit the plugin.txt in AppData or any workaround. Windows 10

**Comment by NoShotz** [comment]
Fixed in Alpha 2
