### ISSUE TITLE
FNIS Not running from drop-down menu.

### ISSUE THREAD

**Issue by DragoValhar** [TanninOne/modorganizer#375]
Install Via RAR file -> Set Data Directory -> Okay. All Green. 
Configure Executables -> Title, Binary Path, Add, Close. All Green. 
Select FNIS from Executable Drop down -> Run -> Error: GenerateFNISforusers failed to start. Do you want more information about this problem? [Yes/No] -> Click Yes = https://support.microsoft.com/en-us/kb/2715633. I have attempted the suggested fix and it does not solve the problem. My .Net framework is fully updated to the latest version.
Any ideas?

**Comment by GrantSP** [comment]
Is this for MO 1.3.11 or the alpha MO v2.0?

**Comment by DragoValhar** [comment]
v1.3.11

**Comment by GrantSP** [comment]
You will need to set the .NET correctly.
MO's guide has the instructions for it. http://wiki.step-project.com/Guide:Mod_Organizer#Installing_Mod_Organizer

**Comment by DragoValhar** [comment]
![default net](https://cloud.githubusercontent.com/assets/16007034/11396261/3c6d917a-933e-11e5-8394-95c690d70e8f.png)

You mean do the thing that I already said I did with no success that was suggested here? 
https://support.microsoft.com/en-us/kb/2715633

**Comment by DragoValhar** [comment]
Err. That sounded more smart ass than intended. What I get for replying before coffee. My bad

**Comment by GrantSP** [comment]
I too should have picked up on your comment about your .NET install.
You will need to supply your logs so we can see what is throwing FNIS a curveball.

**Comment by DragoValhar** [comment]
[Log.txt](https://github.com/TanninOne/modorganizer/files/44412/Log.txt)

**Comment by GrantSP** [comment]
Well nothing there to show any issues with MO.
Which version of FNIS? There were some issues with the recent updates that required some hasty fixes from @fore. I have not seen this issue myself on my two systems with versions 5.5 or 6.x.

**Comment by DragoValhar** [comment]
v6.0.2

**Comment by GrantSP** [comment]
Simple question, do you actually have FNIS active in the left-hand pane?
I've tried various ways to induce this message and this is the only way I can see it.

**Comment by DragoValhar** [comment]
Oh my gods.. This whole time. Thanks. I didn't have it ticked because I didn't think I needed to until after everything was installed. -facepalm-

**Comment by TanninOne** [comment]
guess this is resolved then. :) Thank you @GrantSP :+1:
