### ISSUE TITLE
Not working if dxgi.dll is present

### ISSUE THREAD

**Issue by Madpaddy** [TanninOne/modorganizer#378]
Not working if dxgi.dll is present,  game will crash on launch if dxgi.dll from reshade is present.

**Comment by midnightvoyager** [comment]
I can confirm the same thing happens to me.

**Comment by Kattmandu** [comment]
Ah, so that's why my game won't launch through MO.

**Comment by zSoulweaver** [comment]
I've had the same issue with ENB aswell. Shadowboost is the only one that seems to work for me.

**Comment by Madpaddy** [comment]
Its a very strange one after removing Dxgi.dll it worked then after a number of restarts it then stopped, Now it wont run even with vanilla, so maybe it was just coincidence.

**Comment by TanninOne** [comment]
This should be fixed in alpha 2

**Comment by papazmichael** [comment]
rename dxgi to d3d11
worked for me
