### ISSUE TITLE
Additional labels needed for the GitHub issues page.

### ISSUE THREAD

**Issue by GrantSP** [TanninOne/modorganizer#379]
May I suggest the addition of these labels to aid in sorting the issues?
MO1, MO2 or some other description to differentiate the version 2 issues from the 1.3.11 issues.

Also a tag for each of the games currently, or soon to be, supported by MO:
TES4, TES5, FO3, FO4, FNV

Also a reminder somewhere to have those that post issues to actually use the tags.

**Comment by TanninOne** [comment]
I added the MO1, MO2 labels but I'm not convinced the game-labels makes sense. Game-support is contained in plugins and those have their own repository with their own issue tracker so if it's clear which game a problem relates to, it's best to place it with the corresponding game.

**Comment by GrantSP** [comment]
Dammit, just realised non-collaborators can't assign labels!
