### ISSUE TITLE
"Sort" button needs a config option

### ISSUE THREAD

**Issue by Techwolf** [TanninOne/modorganizer#383]
When pressing the sort button, it calls loot-cli.exe. The issue I have is I need to append "--no-sandbox" to the command line that executes it.

The "--no-sandbox" fixes an issue with CEF that loot uses under wine.

**Comment by TanninOne** [comment]
This makes little to no sense, lootcli doesn't even have such an option. Are you aware that lootcli is a custom component of MO that does not have a ui and thus does not use cef at all?

Also, linux is not a supported platform for mo as the vfs is platform specific.

**Comment by Techwolf** [comment]
This was a simple request, not a demand to fix a bug.

The LOOT folks was a lot more responsive and in fact sent me over here as I opened the issue over there first.

With Steam Machines being sold now and will probably be one of the top x-mas gifts, i'me sure some of them would want to run Skyrim on it. I am in the works of creating a guide to run Skyim on Steam Machines or similar boxes.

You can keep this issue closed as some farther testing showed the problem to be not related to this request. So while you have written me off, I have not given up on this. :-)
