### ISSUE TITLE
MO (1.3.x & 2.0a) ask for Steam to be active when tools are called.

### ISSUE THREAD

**Issue by GrantSP** [TanninOne/modorganizer#385]
Most, if not all, external tools used to work on mods for the various games do not require Steam to be active to function yet MO asks for it upon execution.
I'm assuming this is because as far as MO is concerned an external tool or the game executable are viewed in the same way.

Is it possible though to add a switch, or some other mechanism, to the "Executables dialogue" that tells MO to run certain programmes without asking for Steam?

**Comment by ThosRTanner** [comment]
See #309

**Comment by GrantSP** [comment]
Thanks @ThosRTanner , I missed that one.
We can close this one.
