### ISSUE TITLE
MO2 - Remembers Nexus credentials and logs in even when settings cleared

### ISSUE THREAD

**Issue by ccjuju** [TanninOne/modorganizer#391]
MO2 appears to be remembering Nexus login credentials, and continuing to log in to Nexus when the program is loaded, even though I have:
1. Unchecked 'Automatically Log-In to Nexus' in Settings->Nexus
2. Replaced username/password with bogus data in the text fields (e.g. "aaaaaaaa"/"aaaaaaaa")
3. Confirmed that the previous username no longer exists in **ModOrganizer.ini**

It looks like MO2 is continuing to use the previous data in **ModOrganizer2\webcache\nexus_cookies.dat** even if Nexus login is disabled.  Manually deleting this file prevents MO2 from logging in on next run.

**Comment by ThosRTanner** [comment]
That's not mo2 specific.

**Comment by TanninOne** [comment]
No, MO doesn't remember the credentials but it does store the login cookie so you will remain logged in until the cookie expires or Nexus changes its cookie format. You already found the solution to that.
