### ISSUE TITLE
MO2 - Closing the game MO will launch the game a second time

### ISSUE THREAD

**Issue by strangerism** [TanninOne/modorganizer#392]
I experience this sporadically. I launch the game through MO then I close it and instead of MO "unlocking" it will launch the game straight away a second time.

Might not be related strictly to MO, who knows, but I only saw this when using MO.
Worth mentioning imho.

**Comment by strangerism** [comment]
this happening in beta2 although I dunno if it is only me

**Comment by NoShotz** [comment]
never has happened to me

**Comment by strangerism** [comment]
I am closing this as it's really weird and probably is not related to MO but my mouse lighting fast clicking..
