### ISSUE TITLE
MO2 won't load certain loose file mods

### ISSUE THREAD

**Issue by NoShotz** [TanninOne/modorganizer#396]
For some reason MO2 doesnt wan't to load this mod, http://www.nexusmods.com/fallout4/mods/3344/?

The log file is saying error, http://pastebin.com/KQgrEFMu

**Comment by strangerism** [comment]
this isn't the only mod with loose files that is not loaded, I'll add my list for reference:

http://www.nexusmods.com/fallout4/mods/1002/?
http://www.nexusmods.com/fallout4/mods/1204/?
http://www.nexusmods.com/fallout4/mods/735/?
http://www.nexusmods.com/fallout4/mods/1073/?

**Comment by NoShotz** [comment]
it also seems that the gore overhaul mod also his this error

**Comment by NoShotz** [comment]
Its possible it may be fixed tommorow due to this, https://blam.halo.click/EVGO9e.png

**Comment by NeoTU** [comment]
Phew... thought it was just me, spent hours troubleshooting with no luck with certain loose texture files loading and others not, hope this gets looked into and resolved as it's completely halted me playing FO4 for the moment as I refuse to dirty install mods to play.

**Comment by NoShotz** [comment]
Fixed with MO2 Alpha 2
