### ISSUE TITLE
Startup Exception

### ISSUE THREAD

**Issue by gravypod** [TanninOne/modorganizer#401]
I get this message box http://i.imgur.com/uuRc4Q0.png
After clicking ok, the application starts fine.

The mod organizer loads all of my mods and starts correctly. I've just taken to ignoring the box.

**Comment by Goofysoccer** [comment]
Yep, that's no big deal, just a small bug. Should be fixed soon

**Comment by TanninOne** [comment]
There is already a report for ths: issue #366

**Comment by jerry7890** [comment]
Fix at #427

**Comment by TanninOne** [comment]
duplicate of #366
