### ISSUE TITLE
adding .zip extension to .7z archives when importing from NMM

### ISSUE THREAD

**Issue by cdogg111** [TanninOne/modorganizer#405]
when trying to read an archive other than .zip it adds a .zip extension and fails because the file cannot be found, it crashes MO right away. i recommend you and support for 7zip

**Comment by ThosRTanner** [comment]
It (MO) does support 7zip archives natively as it uses 7zip to unpack archives. A quick peek at the NMMImport code suggests it doesn't add a .zip extension and does support .7z files natively unless it's going wrong here: https://github.com/TanninOne/modorganizer-tool_nmmimport/blob/master/src/nmmimport.cpp#L338 - which isn't so much "adding .zip" as "assuming .zip"

**Comment by cdogg111** [comment]
i worked around it.. but the error would throw a message referring to a .7z file that actually existed in my filesystem, the only difference was the .zip added on the end like this: "name_of_mod.7z.zip"
