### ISSUE TITLE
 MO2 alpha 2: Disabling texture mod don't refresh the virtual directory until MO2 is closed and restarted.

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#409]
Disabling texture mod don't refresh the virtual directory until MO2 is closed and restarted. Was checking out a signs mod to compare the vanilla to the new texture and when I unticked the mod and restarted Fallout 4 the signs were just showing purple no texture loaded at all. Shutdown of MO2 and restart everything and the vanilla textures were back.

**Comment by strangerism** [comment]
as I discovered this issue can be worked around by clicking "refresh" in the drop down list button on top of the mods panel. Doing so the vfs will be consistent with your enabled mods panel next time you launch.

**Comment by rdunlap** [comment]
Good catch. I should have tried that. :)
Thanks!

**Comment by rdunlap** [comment]
Automatic refresh of the plugins list is working properly as of Beta 1. This issue is fixed.

Robert
