### ISSUE TITLE
MO2 Save Games are not available

### ISSUE THREAD

**Issue by sydtrakked** [TanninOne/modorganizer#410]
When I launch FO4 from MO2 the game loads to Main Menu screen but only allows me to start a new game. I copied my save games to the Profiles folder in the Mod Organizer directory but still no go. 

I tried modifying the executables within MO2 and ticked the close MO upon launch and that loads save games but it is just a vanilla game with no mods activated (I'm assuming this is loading from the My Games folder in Documents).

**Comment by rdunlap** [comment]
The only saves it will see/use right now is the save directory for the game. Local profile related saves are not working yet in the alpha. I keep MO running and locked when Fallout is running and see no problems in mods except when you install/uninstall or when you select/deselect mods you will probably have to close and reopen MO2 as its not yet dynamically refreshing changes in all cases. I personally have always had better results from MO by leaving it run during the game.

Robert

**Comment by sydtrakked** [comment]
Yea I figured that was the case (I noticed it said local saves aren't working yet). But it isn't recognizing the regular FO4 save directory when I keep MO running. I'm going to check right now whether mods are loaded on a new game.

And I am on win10 and I believe everything is being run as admin.

**Comment by Zahlfire** [comment]
I am having the same problem on Windows 10 x64. Mod Organizer doesn't recognize any of the saves, including the ones in the default My Games/Fallout4/Saves directory, and none of the mods are working. My ini's are setup properly to use the mods.

**Comment by rdunlap** [comment]
Ok,
Let me try to talk you through a short process. If This works its something I am pretty sure Tannin already knows about but please do post back so he can see that its still ongoing. Go to c:\Users\(yourUserName)\AppData\Local\Fallout4\plugins.txt and replace it with the one in ModOrganizer2\profiles\Default\plugins.txt. OF COURSE BACK UP the original first please. but esp's are not being picked up from the virtual overwrite and this will fire them up for you. If it does any mod you add or remove will need the same treatment until he gets it fixed. at that time go back into profile folder and restore your original and let MO2 to what it does virtually.

This is only needed for changes that involve a plugin. Textures and meshes and such without esp don't require it as they don't write to the plugins file.

remember to post back so Tannin can see it. :) 
*(i am nosy and curious too)

Robert

**Comment by sydtrakked** [comment]
Sorry, I have been busy and haven't had a chance to test. Also I moved all my games onto a new SSD and now it seems like FO4 won't even load without MO. I verified game cache in Steam last night and will test the game again tonight.

**Comment by sydtrakked** [comment]
Ok... so I don't know where to start with what actually fixed this issue. Since I had moved my game to a new drive I thought the game was crashing on startup so I resorted to re-installing it completely, only to find out that I have this weird bug where my game just immediately minimizes on the main menu and the only way to stop it is to keep clicking my mouse while the game first loads up.

Now my mods and saves are working. This is NOT using your advice because after re-installing the game it put the plugins.txt back to just Fallout.esm. What I'm thinking my issue was is that I renamed my profile in MO2. Renaming it back to "Default" seems to me to be what probably solved everything.

**Comment by rdunlap** [comment]
Sounds correct. It turns out that my issue with the plugins file was related to AVG not playing nice with MO2. It will have to be submitted for white-listing, Until then I set several exceptions in AVG to force it to ignore MO2 and all its processes and my plugins are now being handled properly by MO2. Tannin has said in other posts that only Default profile is working right now. He will code in the other profiles and profile level saves before moving it to beta. for the minimizing issue check to see if you have some fallout ini setting related to size/topmost/fullscreen set wrong. mine was doing that when I first started fixing the widescreen issues in the game and I messed up on a setting. NOTE: MO2 now has an active ini editor for the Default profile.

Robert

**Comment by CTKnudsen** [comment]
I am also having an issue with MO launching the game (but not the launcher for some reason, unfortunately), but not being able to see save games with the default profile, with or without local saves copied and the local saves button checked (or not).  Have tried creating new (duplicate) profiles, to no avail.  

I have not tried to start a new game to see if mods are working - I really don't feel like starting over ATM...
