### ISSUE TITLE
FALLOUT 4 (CTD, NO START, ~~~.DLL,  ETC... )

### ISSUE THREAD

**Issue by Sunlyn** [TanninOne/modorganizer#413]
Window 10 Pro 64bit

MO on C:\
Fallout 4 on C:\

NO ISSUE
PERFECT GAMEPLAY

Program files (x86) = FUxK
it is very simple problem ...

**Comment by gerbilOFdoom** [comment]
This is most likely a permissions issue. Program Files (x86) is a protected directory Windows 7+

**Comment by WhiteZeroX** [comment]
gerbilOFdoom is probably right. You can try running the program As Administrator. Or change the folder permissions for MO in Program Files: Right-click the MO folder, Properties, Security Tab, Edit, select Users group, check the Modify box under Allow, click Apply.
