### ISSUE TITLE
MO 2 Alpha New Error -  Failed to request file info from nexus

### ISSUE THREAD

**Issue by vile80r** [TanninOne/modorganizer#415]
All of a sudden I have started getting this error:

Failed to request file info from nexus

Mods will not download from Nexus but I can install manually.

**Comment by NoShotz** [comment]
it generally means that the file hasnt been scaned on the nexus, its not a MO2 issue

**Comment by vile80r** [comment]
Thank you for the quick response.  Would anything else cause this issue?  I tested it on mods I  successfully downloaded and installed already with MO but still get this error.

**Comment by vile80r** [comment]
Nexus has been updated to 0.61.2 
Changing MO to match that fixed it.
