### ISSUE TITLE
Problem with large size texture mod

### ISSUE THREAD

**Issue by scridernguyen** [TanninOne/modorganizer#424]
I won't be able to make it to the main menu intro if I have this mod enable due to Fallout 4 stopped working http://www.nexusmods.com/fallout4/mods/3918. Could it be due to the large size of the mod? I have tried to split it into multiple parts but result varies (sometimes it works sometimes it doesn't)

**Comment by NoShotz** [comment]
i don't think it would be, as i use similarly large size texture mods
