### ISSUE TITLE
MO2 alpha 2 is looking for a non existent D: drive

### ISSUE THREAD

**Issue by JezzX** [TanninOne/modorganizer#427]
When I run MO 2 alpha 2 it seems to be looking at my d: drive which I don't have and then throwing the error in the screenshot below.  I'm on windows 10 and have C: E: F: but no D:
Clicking continue makes it still load perfectly fine though (after the ignore the python error already reported)

Sorry if its been reported before but I couldn't find it in the issues just the python error on startup

![2015-12-09 1](https://cloud.githubusercontent.com/assets/487701/11683576/cb0117f4-9ebf-11e5-8eca-d9b33f25fa6c.png)

**Comment by JezzX** [comment]
I should probably mention that d: is actually the memory card slot on my printer so it is empty

**Comment by TanninOne** [comment]
Could you check if your modorganizer.ini refers to d: ?
Alternatively: is it possible that at some earlier time d: was a hard disk and one of the supported games was installed there? In that case your registry may still state d: as the installation directory of one of the games.

**Comment by JezzX** [comment]
My INI doesn't have any references to d: in it but a long time ago I did have skyrim and FNV both installed to the d: drive on an old set up and have just copied the MO directories from those installs onto my new PC (to not have to download everything again). And may have rerun them 

So Your probably right about it being a registry entry but I've looked and can't find it so if you can tell me where in the reg it stores them I will look

**Comment by TanninOne** [comment]
HKEY_LOCAL_MACHINE\Software\Wow6432Node\bethesda softworks\<game name>

**Comment by JezzX** [comment]
Nope neither of them have d: paths its just skyrim and fallout 4 currently, and fallout 4 that I'm running this version with is located on c:

I wonder if MO or one of its addons is scanning drives at boot and because D: was assigned but not  mounted it was causing the issue. 

If you want I can change the drive letter back to d: and see if it errors then maybe get some loging happening if its possible before the app runs

**Comment by TanninOne** [comment]
No, MO does not scan drives. If it accesses the d drive that's because d is referenced somewhere.

**Comment by jerry7890** [comment]
...\ModOrganizer2\plugins\pyCfg.py
line 5     f = open("d:/temp/sp.txt", "w")                  - looks for drive D:
line 6     print >>f, "%s" % sys.path                       - creates file sp.txt for debuging system environment

Line 5 causes "missing drive D:" error if you dont have drive d:
Line 6 causes "... error" if you dont have dir "\temp" on drive d:
Fixes: 1) comment the lines with "#" or
           2) change "d:/temp/sp.txt" with ".../ModOrganizer2/logs/sp.txt" for checking you pathes or
           3) create dir "d:\temp" if you have drive d:
and MO2 start without errors.(still problems with 32bit externals"
My sp.txt="['G:\\Fallout 4\\ModOrganizer2\\plugins\\data', 'G:\\Fallout 4\\ModOrganizer2', 'G:\\Fallout 4\\ModOrganizer2\\python27.zip', 'G:\\Fallout 4\\ModOrganizer2\\python27.zip\\Lib', 'G:\\Fallout 4\\ModOrganizer2\\python27.zip\\DLLs', 'G:\\Fallout 4\\ModOrganizer2\\python27.zip\\Lib\\site-packages', 'G:\\Fallout 4\\ModOrganizer2\\Lib']"
Problem is "...\\python27.zip\\DLLs..." python27.zip only has lib directory, not to mention its 4-5years old. Current python is 2.7.11 with few years of bugfixing mostly for 64bit systems
My python from https://github.com/wrye-bash/wrye-bash/.
I created new  python27.zip from my python 2.7.11 \lib and \dlls and MO2 run w/o error (just MO2).

**Comment by TanninOne** [comment]
those lines are only for debugging and aren't necessary. If I'm not mistaken they were also never part of the repository.

Why would you go through the trouble of updating the python27.zip and then not contribute it???

**Comment by jerry7890** [comment]
I'm new to this. created acount few minutes ago where to upload the file and how?

**Comment by jerry7890** [comment]
Uploaded the created python27.zip
https://drive.google.com/open?id=0B_alDL0KAeCQQU5tMWpvajhaOXM

**Comment by TanninOne** [comment]
Thanks for the upload. I'll check it out before the next release.
