### ISSUE TITLE
Can't run Fallout 4 since patch

### ISSUE THREAD

**Issue by Knae** [TanninOne/modorganizer#428]
Ever since fallout 4 was updated, i can't run the game or the launcher. When I try, there'll be a loading bar about loading vfs, then the cursor will change to 'busy' for a few seconds then back to normal. After there'll be nothing. Though it exists in the task manager, it never runs. i can run the game with mods through the old-fashioned method, i.e pasting into the data folder and running through steam.

[Edit] using MO Alpha 2

**Comment by talynstryker** [comment]
I used to have similar issue whenever I would update FNV in Steam.  So, perhaps it will work for you.

If you haven't already done so, make sure you have set your ini files in Documents\My Games\FalloutNV to readonly so they won't get overwritten.

Steps:
1. Run Fallout 4 via the standard Launcher one time.
2. When you get to the menu to Continue, New, etc, choose Quit.
3. Then open MO and try it.

**Comment by Knae** [comment]
nope, still not working. Thanks for the really quick reply though

**Comment by rdunlap** [comment]
One addition.
make SURE that your MO2  ini files for the game are current and correct and also note that starting up the games launcher will disable all your mods. This will only affect MO2 if you start the launcher with MO2 and expect it to have your mods. The launcher itself is the same one they used during the beta and it cleans out the mods from plugins file. MO2 is still preserving its active list *(I have tested it) but starting launcher then click play and no mods.

Next Item I was getting the same thing and tracked it down to AVG. My AVG updated a few days ago and that exact behavior was demonstrated. Try disabling your AV just long enough to try a run. If it works use your AV's settings to create an exception for the following.
1. ModOrganizer.exe
2.usvfs_proxy.exe
3. usvfs_x64.dll
4. then do a folder exception for the entire ModOrganizer folder 
AVG for some reason still acted up until I excepted all of the above. Normally just the primary exe can be excepted then any processes are treated the same. Apparently AVG is not doing that with this one.
As stated in other threads this is not unexpected behavior and when the codebase is released Tannin will submit it for white listing on AV products that are having trouble with it. ALSO if this is the problem do post back and include the AV Brand so he can see it and track it.

**Comment by Knae** [comment]
Thanks! That did it. I'm using AVG as well. However, it only works while AVG is disabled. I tried adding exceptions like you said, but it's not working. I might have add more files to the exception list

**Comment by rdunlap** [comment]
Let me go and check my list again but those are the only ones i have been setting. I have had several strange issues creep in since Alpha 2 and have been testing variations because I am convinced AVG was doing strange things all along.

Ok I have 2 exceptions for ModOrganizer.exe there are two kinds of exe exception.
one for even when the file is moved and one for even when the file has been changed.
but my AVG is up and full protect mode so the exceptions are working. I am sure it has something to do with 2 versions of ModOrganizer on the computer since MO2 don't do skyrim or any 32 bit games yet.

Robert

**Comment by Knae** [comment]
I've MO for Fallout 4 and skyrim, so i might try creating exceptions for both simultaneously. Beyond that, i'll just stick to disabling AVG when starting Fallout 4

**Comment by rdunlap** [comment]
At least we figured out how to get your GAME started :)
I personally think when 32 bit support comes online and i can switch all my games to MO2 then most of my AVG issues will go away.
