### ISSUE TITLE
Failed to initiallize plugin pyCfg.py

### ISSUE THREAD

**Issue by Skinripper** [TanninOne/modorganizer#430]
Everytime on MO2 start up I get the error "failed to initialize plugin D:////ModOrganizer2/plugins/pyCfg.py: An unexpected C++ exception was thrown in python code"

After the error box is closed, MO2 runs, but I don't know if this is causing me any problems beneath the program while running.

**Comment by NoShotz** [comment]
its already been reported

**Comment by TanninOne** [comment]
Duplicat of issue #366
