### ISSUE TITLE
[MO alpha2]Error message at launch of MO (still work after it)

### ISSUE THREAD

**Issue by LeFlemard** [TanninOne/modorganizer#432]
Hi,
When starting MO (alpha 2, v2.0.2a), I always have this error message : 
window header : "error"
window text : "failed to initialize plugin  [...]/plugins/pyCfg.py: An unexpected C++ exception was thrown in python code"
window button : "Ok"

It still perfectly start after that, but I dunno what I did wrong that could make this happen.
Thanks :)

**Comment by NoShotz** [comment]
Its been reported many times, and it won't cause any problems

**Comment by LeFlemard** [comment]
okidoki, I really should browse the issue page before posting tho, my bad :p
