### ISSUE TITLE
Mod Organizer says "There was an error reported recently"

### ISSUE THREAD

**Issue by EpitomyofShyness** [TanninOne/modorganizer#440]
DEBUG (16:19:28.0867): all hooks installed
INFO (16:19:28.0867): injection done
DEBUG (16:19:28.0867): set current directory b: D:\Games\MergePlugins -> D:\Games\MergePlugins
DEBUG (16:19:28.0870): create process (w) D:\Programs\Champollion-V1.0.1-x64\Champollion.exe - "\Programs\Champollion-V1.0.1-x64\Champollion.exe" "D:\Games\MergePlugins\temp\generalPex" -p "D:\Games\MergePlugins\temp\generalPsc" (in D:\Games\MergePlugins) - hooking
ERROR (16:19:28.0873): failed to inject into D:\Programs\Champollion-V1.0.1-x64\Champollion.exe: failed to access thread context. Please note that Mod Organizer does not support 64bit binaries! (The parameter is incorrect. [87])
DEBUG (16:19:29.0106): hooks removed
----------- LOG END -----------
DEBUG (16:19:29.0328): create process (w) null - "D:\Games\Mod Organizer - Skyrim\mods\Interface Mods\merge\HUD Mods Merged-Copy.bat" (in D:\Games\MergePlugins\) - hooking
-------------------------------
INFO (16:19:29.0357): Windows 6.1 (workstation)

**Comment by TanninOne** [comment]
The log contains the explanation: MO1 does not support 64-bit applications
