### ISSUE TITLE
Fallout 4 and LOOT - LOOT doesn't see VFS

### ISSUE THREAD

**Issue by vile80r** [TanninOne/modorganizer#442]
When I launch LOOT with MO 2, LOOT only sees one plugin that is in the actual game directory. 

LOOT is not looking at the VFS where I have 23 plugins installed.

**Comment by Wadu436** [comment]
I think your LOOT has to be 64-bit, as the library for VFS only supports 64-bit right now.

**Comment by vile80r** [comment]
That is a good point.

**Comment by TanninOne** [comment]
Yep, known issue.

**Comment by vile80r** [comment]
Why did you close the issue? Is it fixed?
Is there an existing issue open already?

**Comment by TanninOne** [comment]
No, but because there are already at least 2 issues open pertaining to the same bug.
