### ISSUE TITLE
Unknown Error Report

### ISSUE THREAD

**Issue by SmytheTech** [TanninOne/modorganizer#444]
Getting this error report log:
INFO (19:51:32.0090): using mod "Bashed Patch"
INFO (19:51:32.0090): using mod "ScreenShot Assist"
INFO (19:51:32.0090): using mod "Archery Gameplay Overhaul"
INFO (19:51:32.0090): using mod "Halo'sPoser"
ERROR (19:51:32.0090): mod "C:\Steam\steamapps\common\Skyrim\Mod Organizer\mods\Pca 136f alpha loosefile" doesn't exist, maybe there is a typo?
INFO (19:51:32.0130): using mod "D13 Skyrim Leveled items can level up Unique upgrade balanced"
INFO (19:51:32.0130): using mod "DSR Output"
INFO (19:51:32.0130): using mod "XP32 Maximum Skeleton Extended"
INFO (19:51:32.0130): using mod "Unique Weapons Redone"
INFO (19:51:32.0131): using mod "Deadly Dragons Armory Hotfix"

This was after I deleted the files for the [Pca 136f alpha loosefile] mod so I'm wondering if I've done something wrong in attempting to remove it.

**Comment by ThosRTanner** [comment]
well, yes, as per your comments, you didn't delete the mod from within modorganiser so it thinks it should have a mod but can't find the information for it. You should right click on the mod and select delete.

**Comment by ThosRTanner** [comment]
@TanninOne I think this can be closed
