### ISSUE TITLE
MO2 "failed to assign to job object: 1450" (multiple folders issue ?)

### ISSUE THREAD

**Issue by Erewon** [TanninOne/modorganizer#458]
First of all, I can properly launch the game without any mods activated via MO2.

I had a theory that mods containing loose textures (.dds) or meshes (.nif) would cause the following issue, but after some testing it turns out they are not all affected. The error is the following:

<b>[W] failed to assign to job object: 1450</b>

I did a lot of testing, and it seems that any mods that affect multiple folders inside the <i>textures</i> or <i>meshes</i> folder <b>will</b> cause the error.

My question is: what does this error mean and how can I fix it (obviously)?

See the MO2 log with all my mods activated (Texture Optmization Project was the first mod in the load order during this test, and affects multiple folders inside the <i>textures</i> one): [MO2 log.txt](https://github.com/TanninOne/modorganizer/files/72774/MO2.log.txt)

Everything works fine when I put the mods in the <i>Data</i> folder directly, not using MO2.

<b>EDIT:</b> I missed a crucial information which was that if the warning occurs, MO doesn't start the game at all.

**Comment by TanninOne** [comment]
This is not an error message, it's a warning. It means that MO can't group the started processes in a job group, probably due to another application messing with the mechanism. All this means is that MO may unlock it's UI before the last process has ended. This has nothing at all to do with what files your vfs contains.

**Comment by Erewon** [comment]
Thanks for answering :)

If that is so, why it it that it only affects this types of mod? There must be a link, right?
Do you have any idea what kind of application might be messing with with the grouping part?

**Comment by TanninOne** [comment]
It doesn't. As I said, this warning has nothing to do with the content of your mods. This is a typical case of correlation that does not imply causation.
The kind of application would be the kind that thinks what other applications do is their business like debuggers, anti-virus, virus or other malware, overlay tools like fraps or evga precision, ...

**Comment by Erewon** [comment]
Windows 10 got a major update and it seems to have solved the problem, now everything works like a charm... I guess we'll never know :P

**Comment by TanninOne** [comment]
very very odd... :(
