### ISSUE TITLE
Multiple mod installation directories

### ISSUE THREAD

**Issue by matortheeternal** [TanninOne/modorganizer#460]
I have an SSD with limited space.  I want to run some mods off of the SSD, but some off of my HDD.  Currently there's no way for me to do this, because Mod Organizer has one mods folder which is located in one directory.  It'd be cool if a user could specify two mods folders, and then specify which folder they want to use for each of their mods installed through Mod Organizer.

This is specifically useful for a power user who has downloaded and installed mods that they aren't using in a current playthrough.  These mods take up valuable SSD space for no reason, and completely uninstalling them is annoying (because then they have to be installed again, or the user has to keep the downloads).

**Comment by TanninOne** [comment]
You can just move mods to a different location and use regular junction points to link them to MOs mods directory.
Adding the option to do this from MO would add considerable complexity to MO (UI to manage the different mod directories, a way to choose it during installation, a dialog to move mods between locations, ...). This means a lot of work and sources of confusion for unexperienced users for a fairly obscure feature.

**Comment by matortheeternal** [comment]
Ah, ok.  I didn't know that was a possibility.  I'll use that in the future.  Thank you!
