### ISSUE TITLE
[Feature Request] Option to add Blank or Empty Mod in left panel

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#467]
It would be great to have an option via right click or button on button bar to add an empty mod to the left panel.Maybe brings up a name dialog in the creation process. I always collect up several small esp's that become just part of the always use background noise. I usually pick one of the involved esp's and change the mod name in the left panel to something unique and simply open it in explorer to add or change directly. It would be nice to have the ability to just create a blank empty mod and use drag and drop or explorer to populate it. 

I am going to use my Skyrim installation of MO1.X to give an example. I have one such mod created and have added several useful esp's for when I want to do a play through as a Mage another for when i am wanting to do Fighter etc.... One folder specifically I create as Fixes and small fix esp's go into it so instead of trying to remember mod names and scrolling for it I can just go to Fixes or Mage or Fighter. All the relevant esp's are there along with any associated loose files and readme's. 

I realize this is only a convenience request. I am just putting it out there as a "Would be nice to have" request. 

Robert

**Comment by patchling** [comment]
you can put/add an empty folder in the C:\<your mo directory here>\Mod Organizer\mods folder and it will show up in the left pane window as a mod when mo is running. starts empty, add your mods either from windows or in mo when it is running. i have done this a time or two myself.

the bundle of "always used for a playthrough type" mod idea sounds interesting, i've just done custom catagorys and just enable all or disable all when changing playthrough types.

**Comment by rdunlap** [comment]
I have tried that one too. Either me or ModOrganizer was feeling obstinate when I did. besides the whole reason I do it like that is to shorten up the list. :) Right now there are only 10 mods in my left pane for Fallout 4, but if it goes off anything like Skyrim we will have the overloaded lists again. That drives me nuts trying to spot what I am looking for. With the named folder thing I just know right where to go. In almost every case *(I can think of one or two exceptions) any textures or loose files in those folders I want to be overwrite winners anyhow so I keep those folders at the bottom of the list and easy to find.

**Comment by rdunlap** [comment]
I guess all that to say I knew how to work around it. I was just suggesting a convenience feature. Something I use over and over again I consider a candidate for streamlining. 
 :)

Robert

**Comment by TanninOne** [comment]
This could easily be implemented as a plugin (like 3 lines of codes compared to the hello world sample). Please try to advertise this feature request (i.e. on the step forum). We desperately need to get more devs contributing on Mod Organizer and this is the simplest form of code contribution possible.

**Comment by Wadu436** [comment]
I have never written a plugin before (heck, I only have very basic knowledge of C++), but I want to learn C++ (or at least a bit more than I know now), so I'm going to try this. Don't expect too much though.

**Comment by rdunlap** [comment]
I will be happy to assist with testing. I am not current in any useful language but years of UI coding and Data Backend coding have given me a reasonable approach to testing. Let me know if you need anything i can help with. I would also like to see the code of the final result since I have started studying C++ to brush up from too many years ago, as well as Python. *(Python may actually be useful to me in a much shorter window, as its syntax feels more natural to me.). Going to the Engineers bookstore in Atlanta this weekend to meet an old friend who is going to set me up with his recommended self work references. Thanks for deciding to give this a shot. :)

Robert

**Comment by Wadu436** [comment]
Well, I can't even get the HelloWorld example to work (gives errors about missing referenced header files) and when I import all the uibase headers+source files, it gives a boost error.

**Comment by rdunlap** [comment]
Tannin Added it in Beta 1 in the context menu as well as in the menu tree above. 

THANKS!

Robert
