### ISSUE TITLE
MO2 Not Functioning on Windows 7

### ISSUE THREAD

**Issue by MithosFall** [TanninOne/modorganizer#470]
TanninOne, my dawg.  I recognize how much time, effort, and hair-pulling it must take to recode this for 64-bit operating systems, and maybe this isn't the right location for this.  Also, I'm also very sorry if this has been answered elsewhere.  I couldn't find anything on it.  But Windows 7 support surely has to be top priority, right?

It's been nearly two months since MO2's alpha was released and the GECK is coming soon.  I don't wanna be Naggy McBallbuster, it's just, what's making it take so long?  I'm not trying to be annoying, I actually do want to know, even though I'm not that experienced with programming.

**Comment by TanninOne** [comment]
There already is an issue about this: #381
