### ISSUE TITLE
Dividers/separators (left pane minor feature suggestion) 

### ISSUE THREAD

**Issue by Smashpatch** [TanninOne/modorganizer#472]
This should be a trivial issue to implement, that I believe will add a lot to the "organizer" part of MO.

* I first created a text file in a temp folder with irrelevant text in it and called it (because I'm using the STEP Guide, section 2.C is Extenders) Extenders_MO_dummy_file.txt
* Then I created a folder called "Interface" in my temp folder and copied Extenders_MO_dummy_file.txt into that.
* I then archived the dummy text file in and including my temp Interface folder to Extenders_MO_dummy_file.7z
* I then copied the 7z file to my MO downloads folder and installed it.
* Once it was in the MO left pane I then renamed the "non-mod" to:

_______________________________Extenders________________________________

Once that was done (and leaving it unticked) I dragged it up the left pane to where my SKSE Scripts and other mods (that are visible in the MO left pane) that the STEP Guide linked to install in its "Extenders" section.

I then renamed my temp\Interface\Extenders_MO_dummy_file.txt to temp\Interface\Fixes_MO_dummy_file.txt, because the section after "Extenders" in the STEP Guide is "Fixes".

I repeated the process above, but archived my (temp) Interface folder and the dummy/renamed text file in it to temp\Fixes_MO_dummy_file.7z, copied that to my MO downloads folder, installed it then renamed it to

_______________________________Fixes________________________________
 
...and (without selecting/checking it) moved it up to where my mods are as linked from the Step Guide's "Fixes" section.

I did this for every STEP Guide section and my left pane in MO is now very easy to navigate through, and it's very easy to spot any mods that are out of place.

Of course it can be done with any "section names" for the left MO pane, but it is a bit of a pain that MO could do for us (probably not the way I had to do it) with a right-click on the left pane then "Add separator..." We could then give the visual divider/separator a name, as in the two examples above or not and just create a line/divider/separator to help us to organize/see our related/grouped mods better, and to also make it much easier to find where to drag newly-installed mods of a given type to, which is why I did this. I got tired of getting lost every time I had to drag a newly-installed mod to the section it needed to be dragged to.

**Comment by Sultansmooth** [comment]
I second this, using a mod instead of an integrated feature has a good amount of negative effects.

**Comment by TanninOne** [comment]
Not going to happen. The left pane is supposed to be ordered by the priority of a mod, not by categories. That's what categories are there for. If you want to order your mods by categories then assign categories and let MO sort by it. If you need a separator between categories, use the grouping feature.

**Comment by Techwolf** [comment]
Only one problem with that, many mods already set the category. So to do what you said we need a second categories column.

**Comment by Smashpatch** [comment]
>Only one problem with that, many mods already set the category.
>So to do what you said we need a second categories column.

Absolutely, and thanks for your feedback. That's what I'm suggesting. I find the existing categories to be less than helpful. I'm suggesting a second level  (a broader and user-defined level) of categories, with and I'm using it by hacking it as I documented, but it'd be nice if there was a way to define our own categories of mods, especially with MO because it's more advanced than NMM (I think) so we're likely the players who have 200+ mods installed.

It's difficult to keep track. I look at it no differently than bookmarks in Firefox. If I need a new category for whatever bookmarks, I define one.  If I need a divider line in my bookmarks, I add one.

The existing categories of mods is useless, to me. I know we can re-define them but that's a massive pain and it's potentially a topic to address with each mod developer, if we happen to disagree with whatever category they default their mod to.

I just want headings (and I have them via my documented hack) that allow us to define (so to easily find) broad categories of mods, especially as the STEP Guide lays mods out in its sections, which is what I have in MO, via my "hack".

**Comment by Gernash** [comment]
I thought it was a pain to change categories as well
if you change or add 1 category Modorganizer2 creates a file categories.dat you can edit that manually with a text editor
I know on 1st glance it looks complicated but it's really basic
ID|NAME|Nexus IDs|Parent ID
you can reorder (copy past) so the order is 1,2,3,4,5......
change the names to what you like

[categories.txt](https://github.com/TanninOne/modorganizer/files/410215/categories.txt)

it contains the default categories for Fallout 4, Skyrim and Oblivion Categories

from here https://github.com/TanninOne/modorganizer/issues/897

**Comment by Smashpatch** [comment]
>I thought it was a pain to change categories as well
>if you change or add 1 category Modorganizer2 creates
>a file categories.dat you can edit that manually with a text editor


Interesting, thanks for posting that. It doesn't seem that complicated, but
I'd still like to have the option of visual dividers. Even if we could only
add horizontal lines without any text or whatever embedded in horizontal
lines, I still think it'd be helpful to MO users. And it'd be easy to
implement, no harm done. Those who wanted to use it, would, those who
didn't, wouldn't. :) Nothing forced, just an additional and only visual
organizing option.

**Comment by Gernash** [comment]
I've been doing it like this
http://wiki.step-project.com/User:Gernash/MODWiki#Organizing_ModOrganizer
At least the headers are grey

**Comment by Gernash** [comment]
I assume if you edited the style you could have empty mods HOT PINK
I have not looked into that as yet

**Comment by Smashpatch** [comment]
>I've been doing it like this
>http://wiki.step-project.com/User:Gernash/MODWiki#Organizing_ModOrganizer
>At least the headers are grey

What an awesome post. This is really interesting, seeing all of these different ways to categorize things.  But can't we agree that it could be made easier with an interface option, such as "Add divider" (to the left pane, right pane, any pane). Type nothing and get a visual horizontal divider line, type whatever and it gets centred in the (visual only) horizontal divider, or don't select "Add divider" (or whatever) and stick to whatever one is already using to sort/organize mods. ;)

**Comment by Gernash** [comment]
http://www.nexusmods.com/skyrim/mods/63743/?
the orange contrasts enough to see the grey easly (these are not mo2.qss but seem to work i.e. no script errors in bottom box)

But your eyes, I've posted around the place and see if the reverse can be done.....

**Comment by Gernash** [comment]
OK http://www.nexusmods.com/skyrim/mods/73817/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmodfiles%2F%3Fid%3D73817&pUp=1
is Skyrim 
He is the winner

**Comment by Gernash** [comment]
And my last post on this thread
did you realize you can do this
-----------------------------------------------------Core Mods------------------------------------------

I need sleep

**Comment by Smashpatch** [comment]
>And my last post on this thread
>did you realize you can do this
>-----------------------------------------------------Core Mods------------------------------------------

Thank you for the post, but no I do not realize that or how I can do the above (not with MO 1.3.11), other than how I documented I did it at the top of this thread. 

And I can read, I was it's your last post, but I'm just to the board/thread because it still doesn't seem that the very simple little visual interface feature I suggested is even understood by anyone, as yet. I don't know how to do the above, other than that I have already done:

________________________________________Extenders___________________________________________

and every other visual table divider the STEP Guide separates its massive list of mods into, as a purely visual dividers (nothing to do with changing anything about how MO, or the STEP Guide either, sorts things, nothing to with actual mod cagetories or any other column we can sort mods by) just purely visual dividers.

In MO 1.3.11 I can't find any way to easily implement the simple visual feature I've suggested:  an MO interface button "Insert divider" that then pops open a text input control. Hit Enter or click OK on the text input control and users get a horizontal rule/visual divider, above or below wherever the current selection is in the left or any other MO pane. Type whatever into the text input control after selecting "Insert Divider" and MO centers whatever input in the horizontal rule/purely visual divider line, such as:

____________________________________________Core mods___________________________________________

I looked in the "Open list options..." dropdown mentioned here (but for MO2, which I'm not using)... I tried the "Create mod..." list on the Overwrite folder and typing in basically what you suggested, 

________________________________________Core mods___________________________________________

but MO strips the main reason I do it (the underscores): to add a visual divider line, to help me to just visually find (and sort new) mods in my list of over 200 mods.

The list is far too long to have in one big chunk, with no visual aids to help users to visually separate mods, basically as the line breaks I'm using in this post to avoid posting a "wall of text", which MO does not let us do (that I know of, other than how I documented I did it, with a very tedious hack).

It wouldn't change anything at all, functionally. The priorities of mods in the left pane remains the same, the categories that mod developers assign to mods (and that I pay no attention to, because it's too tedius compared to the simple little feature I suggested) remains the same. Everything remains the same, other than an option to "Insert divider" above or below wherever the current selection is, in the left pane, or any of the right panes.

Visual dividers never get selected (shouldn't even have a checkbox beside them; other than maybe as a handle to drag them with), because they're visual aids only, not actual mod names in the left pane, or any of the right panes.

>-----------------------------------------------------Core Mods------------------------------------------

If there is an easy way to add purely visual dividers, as above, in MO2 (or maybe I missed it in MO 1.3.11) then that's all I ever needed to know. :)

But I don't know how to do that, other than how I documented I did it, at the top of this thread.

I'm suggesting that the tedium I went through to implement this very simple and purely visual feature, be very simple new MO feature, that can be implemented via a simple interface feature (already documented above and "remembered" by MO in profile text files, in archives.txt, loadorder.txt (one special character that cannot show up in a filename, such as * or ? or a control character, as the first character in the text files can let MO know "this is a visual divider for display only. It's not a filename, it's not anything but a purely visual divider to display, in a given position of a given list"), we might as well have a downloads.txt file in profile folders so that we can add visual dividers to what is certainly a total mess of a massive list of downloaded files with no "organization" at all in MY MO "Downloads" tab.

This product is called an "organizer" not a mess creator. I have paragraph breaks in this post because "walls of text" tend to get ignored (around the Facebook and Twitter generation, anything over 20 characters tends to get ignored, but). But MO does not allow us to put visual-only "paragraph breaks" into our massive left pane mod lists or any right-pane lists.

It would be simple to create "invsible" visual dividers in the left/any pane if Tannin also added a simple Font settings dialog in the setting for user-defined visual dividers. Set the foreground color of "dividers" to the same as your MO background color and you'd get "paragraph breaks" instead of visual horizontal rules, with whatever (if any) text centred in them, in whatever font face, size, foreground and background color any user wanted to use.

It would all also be 100% optional. Don't want "paragraph breaks" or visual dividers in anything? Then don't select the suggested "Insert Divider" toolbar option to do so, and MO will remain exactly as it is.

**Comment by Gernash** [comment]
Yea I see you cant do it in the mo 1.3.11 hence the wall of frustration

http://www.nexusmods.com/fallout4/mods/17371/?

enjoy Just copy and paste into your mods folder


BAM!!!!!!!

**Comment by Smashpatch** [comment]
>Yea I see you cant do it in the mo 1.3.11 hence the wall of frustration

>http://www.nexusmods.com/fallout4/mods/17371/?

>enjoy Just copy and paste into your mods folder

>BAM!!!!!!!

I thank you for the link and for all of your posts. But I'm frustrated that I can't get a simple answer as to whether this simple (and necessary, and optional) feature is already part of MO (Tannin told me above that it was never going to happen because the left pane is for mod priorities. But what I documented and suggested has nothing to do with mod priorities, load order or anything else functional. Visual dividers would change nothing, functionally) but I don't want to frustrate you.

I appreciate all of your feedback and am looking for MO2. I'll have to see if it has the simple feature I've suggested. If it does, it was the only post that Tannin or anyone else ever needed to make here.  :)

**Comment by Gernash** [comment]
MO 1.3.11 dosent do it
MO2 has a feature to create an empty MOD
MO2 does not work for skyrim 
The link is folders with the extra info you need for MO to see them in your mod list you can use them as seperaters, just dont check them.(They are empty and should be fine if you check them but MO complains about it)

**Comment by Gernash** [comment]
I'd say there will be no NEW development till HD Skyrim if it need patches.
Looks like dev time is for MO2

**Comment by Smashpatch** [comment]
I installed MO2, clicked on the "Open list options..." dropdown, selected "Create empty mod" and I didn't even notice that what I'd entered (____________________Empty mod____________________) had been displayed.

Though it is kinda cook that it shows up (I haven't changed the style of MO yet) in greya and italics, like the empty Overwrite folder, it is only displayed in the "Mod Name" tab.

A actual visual divider goes from one side of a pane to the other, and it shouldn't be up to the user to figure out how many underscores or dashes or whatever to type, to accomplish that, or to drag the "Mod Name" tab across the left pane (and I want this feature for every pane, there's no reason not to have it for every pane, it's easy)..

The software should provide a horizintal rule, and if any text is entered after "Insert divider" is selected, it should be auto-centred in the horizonal rule that (regardless of any tabs) runs from one side of whatever pane the divider is added to, to the other.

It's also nowhere that any average user is going to find it, or understand what it does. "Insert divider" is clear, and what it does, how it visually operates should be just as clear. Dividers run from one side of a pane to the other, not within a tab. It is easier than what I had to do with v1, but it's still a hack in v2, compared to what it could very simply be. :)

**Comment by GSDFan** [comment]
While not a one button solution, do the following:
Start with an empty overwrite folder.
Double click the overwrite folder to open the info panel. Actually this is the MO folder view.
Right click inside the window and select create new folder. Name it what you want.
Close the window.
Right click the overwrite folder and select create mod. Name it what you want. press OK.
Move the new Mod to where you want.

**Comment by Smashpatch** [comment]
>While not a one button solution, do the following:
>Start with an empty overwrite folder.
>Double click the overwrite folder to open the info panel. Actually this is the MO folder view.
>Right click inside the window and select create new folder. Name it what you want.
>Close the window.
>Right click the overwrite folder and select create mod. Name it what you want. press OK.
>Move the new Mod to where you want.

I do appreciate your post, but I'm getting more and more bewildered as to why Tannin is not simply responding "What you're suggesting is very easy to do, and there's no reason not to do it, so it's as good as done." It'd take about fifteen minutes, done.

**Comment by TanninOne** [comment]
Because it's a terrible idea and I refuse to endorse it! Read my previous comment: you are not supposed to sort the mods by some categories, you should put them into categories based on their categories.

The mod sorting has functional relevance as it decides the order in which mods get installed, it is NOT a custom do-whatever-you-want user ordering. And it is independent of their category, including the step category.
This is evident by the fact that the step guide (at least last time I checked) causes "potential mod order problem" warnings which have to be fixed by reordering the mod list.

You may get to the point where you have to choose to either fixing your game and breake the order imposed by your dividers or keep your dividers intact and use the wrong textures, meshes or - worst of all - scripts in your game. How stupid is that? Why would I advocate this use of MO when it clearly conflicts with its function?

**Comment by Smashpatch** [comment]
>Because it's a terrible idea and I refuse to endorse it! Read my previous comment: you are not supposed to sort the mods by some categories,
>you should put them into categories based on their categories.

How gracious of you. I will endeavour to be more polite and professional in my response.

I did read your previous comment about this and you made it clear, again in this post that you don't even know what I am suggesting:

>Not going to happen. The left pane is supposed to be ordered by the priority of a mod, not by categories.
>That's what categories are there for. If you want to order your mods by categories then assign categories and let MO sort by it.
>If you need a separator between categories, use the grouping feature.

All I've ever known is that the mods in my left pane are ordered in the order they are supposed to be in, as defined by the STEP Guide and/or the mod developer, regardless of whatever category mod developers define for them (and I certainly can't be bothered re-defining all of that in over 250 mods, when it's not necessary), 

Purely visual aids, that might as well be paragraph breaks in the massive "walls of text" in many MO lists, can never change anything, functionally. Visual is visual, funtional is functional. My left pane is ordered by mod priority, as it should be. It just happens to have (unselected, so non-existant to Skyrim according to your own tutorial) visual aids in it, much like the paragraph breaks in this or any text to avoid massive "walls of text", which is is all MO allows users to have, at present.

>The mod sorting has functional relevance as it decides the order in which mods get installed, it is NOT a custom do-whatever-you-want user ordering.
>And it is independent of their category, including the step category.

I'm well aware of function versus non-function, and have posted so many times. I have understood that since before I created purely visual hacked (and unselected, so non-existent to Skyrim) visual-only dividers and I am not the only user who has done so. I also guarantee that the STEP Guide is going to come up with a hack for this), because the "walls of text" in MO are unacceptable. No one ever suggested "do-whatever-you-want" user ordering, and if any user wants to do that, they dn not need the purely visual, very simple feature I suggested and that others are obviously doing on their own, as well.

If any user wants to screw their mod priorities up, all they have to do is drag-and-drop, so perhaps you should disable that feature (though since every mod I have ever madded to MO ends up right at the bottom snd I have to drag-and-drop it to wherever the STEP Guide states it should be, or wherever the mod developer states it should be, without drag-and-drop we would be stuck having to download/install mods AS our priorities, so we would never be able to add new mods and drag them to where they belong).

Purely visual aids that affect nothing functionally, affect nothing but visual display. It would be no different to ask that we be allowed to define different font faces, sizes and colors for the categories of mods that mod developers define (and that I decline to re-define the mod developer-defined categories of hundreds of mods, manually). Who cares what font face, font size or color anything happens to show up in? Even around mods that are selected (visual horizantal dividers would never be selected, so according to your own documentation they do not exist to Skyrim. No "mod" that isn't even selected can possibly affect anything), it wouldn't matter what font face, font size or color MO happened to display mods in different categories in. Visual is visual. Functional is a whole other story, but I have never suggested anything that changes the functionality of anything. 


>This is evident by the fact that the step guide (at least last time I checked) causes "potential mod order problem" warnings
>which have to be fixed by reordering the mod list.

You have apparently not even looked at, let alone completed the STEP Guide. It has __divided__ HTML tables, __organized__ HTML tables, not a "wall of text" as MO forces users to deal with, and the order that the STEP Guide lists things in, is the order in which users are supposed to complete each step.

Given that MO (and NMM) simply dump newly-installed mods at the bottom of the mod list (left pane in MO), it's how the STEP Guide must document each step. 

Even though the STEP Guide has section names and table/"paragraph breaks" between its massive HTML tables, it doesn't mean that users are supposed to skip to the end to install whatever in the "Patches" HTML table before they configure their video driver, etc., and install Skyrim and extenders at the top of the STEP Guide.

You seem to be assuming that MO users are mentally retarded and have no ideaa what they're doing. I can assure you that I know what I'm doing with my visual dividers, and that because I define them, they never "force" me to do anything (other than maybe to add a new visual-only divider, visual-only because they are never selected, so they don't exist to Skyrim, and why would OUR OWN user-defined visual-only dividers ever dictate to us users? We're free to delete the things, move them, add new ones; they are visual aids only. How could anything that users define possibly "dictate" to them?).  

All the purely visual (not selected, so according to your own documentation they "do not exist to Skyrim") hacked dividers I added do, is exactly what the STEP Guide does: instead of having one big wall of text in one HTML table, the STEP Guide splits its HTML tables (step categories/sections) up into several different HTML tables, that have section/category names (or whatever anyone wants to call them) and paragraph numbers, so that they can easily be seen and referred to; quite unlike the messes in MOs panes, without the purely visual hacked horizintal dividers I added, that use the exact same names as the STEP Guide __separated__ HTML tables use.

>You may get to the point where you have to choose to either fixing your game and breake the order imposed by your dividers
>or keep your dividers intact and use the wrong textures, meshes or - worst of all - scripts in your game. How stupid is that?

How stupid is it to suggest that any MO user would somehow have their own user-defined visual-only dividers "imposed" on them? They are user-defined, so they cannot possibly "impose" upon any user. If we find that a purely visual divider doesn't fit whatever mod we are installing, then we create a new user-defined section/divider, such as

_____________________________My Stuff___________________________________

or

____________________________Bottom______________________________________


or whatever it makes sense to a given user to call a new purely visual "section", under a purely visual divider, that no user would ever be obligated to use.

If a mod developer documents that his mod must go under <mod X> then I either define a LOOT metarule to ensure that LOOT sorts it below <mod X> or if it doesn't have a plug-in, so is ignored by LOOT, I simply drag that mod below <mod X>, without a care about my user-defined totally visual divider lines. I don't have to care about what I define myself, but when a mod developer states "put this mod under <mods X/Y>" they tend to be in the same category of mods. So my purely visual dividers still work just fine. And if not, I add a new one, but you make it a major pain, for no valid reason.

**Comment by TanninOne** [comment]
Please don't waste my time. Read my post again and this time try to comprehend it instead of repeating the same thing over and over again. 

> I'm aware of function versus non-function, and have posted so many times. I have understood function versus totally visual display.

No you have not, otherwise you would not insist you could put a purely visual separator into an order _that is not purely visual_
It's nonsense It may work in specific cases, i.e. if you install STEP and only STEP (which is the only case the step guys care about), but it will not work in a general case. And MO is not the "Step Installer", so I will not endorse this as a reasonable approach for MO.

> You seem to be assuming that MO users are mentally retarded 

> I can assure you that I know what I'm doing with my visual dividers, and that because I define them,

> You have apparently not even looked at, let alone completed the STEP Guide. It has divided HTML 
> tables, organized HTML tables, not a "wall of text" as MO forces users to deal with, and the order that
> the STEP Guide lists things in, is the order in which users are supposed to complete each step.

> How could anything that users define possibly "dictate" to them

The STEP guide puts mods in a certain order. MO gives a PMOP warning about that order that there may script conflicts. Users ignore the PMOP warning because they prefer the organized STEP order. THIS is how the visual order of mods "dictates" things. Users (and the STEP curators) ignore a valid _functional_ suggestion to improve their mod order because it would break the visual order.
That is why the visual order is stupid, it gives the impression of order, because things look ordered to you, the user, when you should be caring about the technical order that matters to the game.

STEP is a curated list - the work of many people over an extended time to determine its stable. Absolutely NO custom user mod installation will have that level of testing. This has nothing to do with users being retarded. Do you expect me to believe MO users look at the source code of all the scripts installed by all their mods to ensure the order they set up manually is stable? And that all their texture sets match all the meshes to ensure they work together?
That's ridiculous! Unless you follow a guide like STEP, you should be following the instructions of the individual mod authors about which dependency to install when and then not screw that order up because you want to put mods into invented groups you came up with yourself **without** understanding the dependencies between all mods.
And if there is a PMOP warning you should bloody well follow it, even if it puts a mod at a place that you feel is "messy".
This is how you get a stable game and I think this is more important than visually ordering the mod list.

And no, I don't install STEP because STEP is built on the assumption that you install no other mods and that's not how I mod games. In fact, if I was planning to install only the mods from a curated list, I wouldn't be using MO.
MO is built for users that experiment heavily with mods, that has always been the target audience. If that's not you then too bad, I didn't write this for you.

**Comment by psyk3d** [comment]
> Of course it can be done with any "section names" for the left MO pane, but it is a bit of a pain that MO could do for us (probably not the way I had to do it) with a right-click on the left pane then "Add separator..."

Why not just use the already integrated categories feature?

Here is an example:
[https://snag.gy/RhPU0V.jpg](url)
