### ISSUE TITLE
Mod Organizer 2 Alpha 3 HUGE CRASHING ISSUE

### ISSUE THREAD

**Issue by Leer0x** [TanninOne/modorganizer#475]
On MO2 Alpha 3, there is a SERIOUS problem after I setup my mod organizer, the ABSOLUTE FIRST TIME Mod Organizer 2a3 attempts to load Fallout4 mod organizer, it crashes, it is a COMPLETELY brand new install of 2 Alpha 3, i have done nothing at all.........that is the FIRST time it ran, I deleted all my mod organizer appdata things including the alpha 3 install. Redownloaded Alpha 3, now it won't even give me any messages just starting (Even though my computer thinks it never ran it before because I deleted appdata) and it just crashes...sucks terribly. Can anyone help?

**Comment by haileyambition** [comment]
I was unable to get alpha3 to start as well.

**Comment by haileyambition** [comment]
Actually seems if i copy the ModOrganizer.ini file from alpha2 over top of alpha3 i can get by the issue. Loot CLI seems to still fail. Full Loot installation seemed to pick up my mods on this version though it immediately crashed on clicking apply with Error code: -1; Failed to get game data. Details: boost::filesystem::file_size: The request is not supported: "D:\Steam\steamapps\common\Fallout 4\zWGirlClothSimply.esp".  I would suggest likely all the bugs im seeing are from my installation and overwriting the ini, but I'll keep poking at it.

**Comment by rdunlap** [comment]
I had the same error issue but solved it partly by removing msvcp120 and msvcr120 from MO2 folder and app fired off fine. FO4Edit opens and sees all the mods but on exit MO2 Crashes. Even with the crash it still saved the changes to the mod i edited. I saved a dmp file for Tannin and will send it to him. Likely its a simple fix.

Robert

**Comment by Leer0x** [comment]
Ahh
Thanks for all the help will report once I can get this over with

**Comment by michaelrw10** [comment]
same here. same behavior i had with alpha 2. launch game, nearly instant crash "fallout 4 has stopped working"
no mods of any kind are active

**Comment by rdunlap** [comment]
This issue appears resolved with Alpha 4. The only issue i have produced is the ini files are not being used. The game ini file is being used.

Robert

**Comment by TanninOne** [comment]
Thank you for the feedback
