### ISSUE TITLE
Crash with mo2 alpha 3 when importing mods from nmm

### ISSUE THREAD

**Issue by jimmon89** [TanninOne/modorganizer#481]
[ModOrganizer.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/86164/ModOrganizer.exe.dmp.zip)
managed to get past the crash by manually adding the missing info that it wasnt adding but it needed
(current config after successful start... [ModOrganizer.zip](https://github.com/TanninOne/modorganizer/files/86167/ModOrganizer.zip))
tried to import my current mod list from nexus mm and it crashes as soon as i click "NMM Import"

**Comment by TanninOne** [comment]
NMM Import is no longer supported (in fact importing from profile-enabled nmm versions was never supported)
