### ISSUE TITLE
MO2 Alpha 2 Crashes after canceling install and move

### ISSUE THREAD

**Issue by NoobTaco** [TanninOne/modorganizer#482]
Installed into my Skyrim directory as Modular (Not portable) Tried to launch and got the warning about using space in my C drive. Cancled the dialog. Tried to run again and it crashed. Moved it to another drive and it crashes.

It looks like a orphan file is somewhere telling it the type of install it is but I can't locate it.

Windows 10 64bit

[ModOrganizer.exe.zip](https://github.com/TanninOne/modorganizer/files/86285/ModOrganizer.exe.zip)

**Comment by TanninOne** [comment]
please try deleting plugins/game...dll plugins you don't need (at least gameFalloutnv.dll and gameOblivion.dll)
Also: I'm fairly certain MO2 doesn't work with Skyrim yet as 32-bit support is still unstable.

**Comment by PRieST47** [comment]
I have exactly the same issue.
Deleted every file from MO2 (Folder with extracted files and created folder in appdata).

If I download MO2 again, extract everything and start it, I don't get a dialog ('regular' or 'portable') and MO2 still crashes.

**Comment by N00bTaco** [comment]
Deleting the dll's does not work.

Where is MO2 writing its config files? It is not local to the install itself. That is the issue I believe. An ini or config is set somewhere that is causing it to crash. If I could just purge that ini and have it recreate it it possibly will work. In either even this is not a graceful  way of handling this error.

**Comment by TheGreenDragon** [comment]
Open Regedit and search for Tannin, should be in the Computer\HKEY_CURRENT_USER\SOFTWARE branch. Delete the folder and try the install again. This worked for me.
