### ISSUE TITLE
Fallout 4 hangs on intro video every few restarts

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#483]
Hi this is new to Alpha 3. every few starts it will hang right around the time the Steam Overlay should be showing up. I am working on a mod so its taking lots of restarts to finish up my stuff and this is new. Alpha 2 would go long periods before it would hang as noted in a prev post. I am attaching the last log file to this. NOTE: this is a huge log file. its like 30 megs. the others are all below a meg.

Robert

[usvfs-2016-01-11_22-03-08.zip](https://github.com/TanninOne/modorganizer/files/86660/usvfs-2016-01-11_22-03-08.zip)

**Comment by DeadMor0z** [comment]
Same here. With a2 Fallout4 worked fine, with a3 CTD right after steam overlay pop-up showed.

**Comment by ogrotten** [comment]
Me also. see #500. Is that similar?

**Comment by rdunlap** [comment]
looks similar to me. I had to move back to A2 since I had about 3 mods getting done and tested so I had to move backward one step to a more stable one. I only had the crash/hang every few starts of Fallout 4 just often enough to make me nervous.

Robert

**Comment by rdunlap** [comment]
This issue appears resolved in Alpha 4. I have done each of my replication steps and no crash or hang. Alpha 4 does appear to not use the MO ini files but so far this is the only issue I can produce. :)

Robert

**Comment by TanninOne** [comment]
Thanks for the feedback
