### ISSUE TITLE
For pre-release versions, there's no clearly stated method of updating.

### ISSUE THREAD

**Issue by ogrotten** [TanninOne/modorganizer#485]
What is the preferred method of updating? I'm assuming that it's just copy files over, but that's not made clear. Perhaps a short `readme.txt` at the folder level in the zip.

**Comment by TanninOne** [comment]
You should create a clean install for each install

**Comment by ogrotten** [comment]
Ok great. Thanks. Will do from here on.

The point of the post tho was that it's not stated in the docs.
