### ISSUE TITLE
Alpha 3 - Percephere's Findings

### ISSUE THREAD

**Issue by Percephere** [TanninOne/modorganizer#487]
So far it looks like Alpha 3 cannot:

1. Run FO4 via F4SE; crash after Bethesda logo.
2. Check archives (use the archive invalidation ini edit to work around this).
3. Open or export files through external applications (i.e. Bodyslide, Material Editor, INI Config Tool,, et cetera).
4. Install most mods; not sure what the criteria is for this, but MO will usually crash after installation (note: all of the files installed still go through correctly, it just crashes). I get around this by manually adding the mod folders and then editing the mod IDs/links via MO.

Other than that, Mod Organizer seems to be working fairly well. Just' needs some bug-smashing and fine-tuning. Awesome work.

**Comment by TanninOne** [comment]
Please comment in existing bug reports if they exist, this issue tracker will be a mess if every individual posts his/her findings in an individual report and then combines multiple issues in one report.
