### ISSUE TITLE
How to switch over?

### ISSUE THREAD

**Issue by Teldryn** [TanninOne/modorganizer#489]
0 kudos 10 posts 

How do I make it so My downloaded mods go to NMM not Mod organizer. I tried mod organizer but I just don't like it sorry

**Comment by GSDFan** [comment]
<a href="http://forum.step-project.com/topic/8103-how-does-one-disassociate-mo-with-download-to-nmm/?view=findpost&p=128611&hl=nmm">How Does One Disassociate MO with 'Download to NMM'?</a>
