### ISSUE TITLE
Mod Installs at Wrong Path

### ISSUE THREAD

**Issue by RayAdhiasa** [TanninOne/modorganizer#492]
Before i use Mod Organizer,i use Nexus Mod Manager.Then after the 0.61.5 Update,it doesn't work. so i change to Mod Organizer.But everytime i install a mod it always install to D:\ModOrganizer2\Mods. And my Fallout 4 is in D Drive too.

**Comment by Percephere** [comment]
That's normal - in fact, that's one of MO's best features.
