### ISSUE TITLE
[MO2a3] Fo4Edit Access Violation

### ISSUE THREAD

**Issue by Nephatrine** [TanninOne/modorganizer#493]
I have MO2 installed using the Portable option and it's inside a filder in my FO4 directory (not in a protected place like Program Files). When trying to load up FO4Edit to test the unstable 32-bit support, I get this access violation and it doesn't read any of my mods:

Using Fallout4 Data Path: D:\Steam\SteamApps\common\Fallout 4\Data\
Using ini: C:\Users\Nephatrine\Documents\My Games\Fallout4\Fallout4.ini
Using plugin list: C:\Users\Nephatrine\AppData\Local\Fallout4\Plugins.txt
Using settings file: C:\Users\Nephatrine\AppData\Local\Fallout4\Plugins.fo4viewsettings
Loading active plugin list: C:\Users\Nephatrine\AppData\Local\Fallout4\Plugins.txt
Found BOSS load order list: C:\Users\Nephatrine\AppData\Local\Fallout4\loadorder.txt
**Fatal: Error loading plugin list: EAccessViolation: Access violation at address 65E2F608 in module 'MSVCR120.dll'. Read of address 00F63000**

When I close out of FO4Edit, it crashes MO2.

Due to other user posts here in the issues section, I tried to delete/rename the MSVCP120.DLL and MSVCR120.DLL files but got the same error.

I've also tried running MO2 as Administrator both with and without those DLLs to no avail.

**Comment by rdunlap** [comment]
This issue appears to be fixed in Alpha 4 just released. I have had FO4Edit opened and closed several times with no issues at all.

Robert

**Comment by TanninOne** [comment]
Thanks for the feedback.

**Comment by Schizosaccaromyces** [comment]
I am having this issue on Alpha 4, with the code "Fatal: Error loading plugin list: <EAccessViolation: Access violation at address 7400F20C in module 'MSVCR120.dll'. Read of address 011BA000>"
