### ISSUE TITLE
Mods inside another mod

### ISSUE THREAD

**Issue by MeesterYellow** [TanninOne/modorganizer#494]
Hello,

Idk if this is a bug or not but when I install a mod using an achive, it was put the mod inside another mod. Please help. Thanks.
![help](https://cloud.githubusercontent.com/assets/16705057/12327623/a0e2608e-baa5-11e5-9230-55e7e4a21c5f.JPG)

**Comment by TanninOne** [comment]
You have mod grouping active (drop down box below mod list).
