### ISSUE TITLE
[Mo2a3] Failed to request file info from nexus: Connection timed out

### ISSUE THREAD

**Issue by abermuffin** [TanninOne/modorganizer#510]
When downloading links from Nexus using the NMM link, the file begins to download in the Downloads tab and then states "Failed to request file info from nexus: Connection timed out".

I know, 100%, that I am entering the correct password. I've changed my workarounds NMM version to 0.61.5 with no success.

Strange thing is, it was downloading yesterday without problem. Perhaps it's Nexus' fault but I downloaded the same file manually without issue. Anyone else experiencing this problem?

**Comment by sr383** [comment]
Same issue. Worked fine yesterday. I can't download or update information directly in MO. Conversely,  I can select a mod in MO and select Visit on Nexus with no problems. I'm taken directly to the mod page, where I'm still logged in.

Tried reinstalling and re-entering passwords, but no dice.

**Comment by TheGreenDragon** [comment]
The Nexus was having problems with the NMM servers earlier. All appears resolved at this time. It was not a MO issue.

**Comment by TanninOne** [comment]
Thanks for clearing that up!
