### ISSUE TITLE
Mod organizer not connecting to nexusmods

### ISSUE THREAD

**Issue by jmadp** [TanninOne/modorganizer#511]
Hello guys,

I'm having trouble with connecting my Mod Organizer to nexusmods. I can't connect to my nexusmods account from within the application, also I get this error message whenever I start Mod Organizer: 
14:24:58 [W] QSslSocket: cannot resolve TLSv1_2_client_method
14:24:58 [W] QSslSocket: cannot resolve TLSv1_1_server_method
14:24:58 [W] QSslSocket: cannot resolve TLSv1_2_server_method
14:24:58 [W] QSslSocket: cannot resolve SSL_select_next_proto
14:24:58 [W] QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
14:24:58 [W] QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
thanks for the help in advance :]

**Comment by TheGreenDragon** [comment]
See the following posts for more information: 
http://forum.step-project.com/topic/7735-mo-wont-start/
http://issue.tannin.eu/tbg/modorganizer/issues/1098

There is likely other OpenSSL software on your system that may be causing a conflict or may need to be updated.

**Comment by Leer0x** [comment]
What did you set your Nexus version to in the workarounds? Make sure it is a working version or the newest one.

**Comment by TanninOne** [comment]
As TheGreenDragon said this is caused by an incompatible openssl version globally installed.

**Comment by jmadp** [comment]
Thank you for you responses guys. The problems have fixed itself somehow when I started Mod Organizer after a couple of days. It was surprising actually because I had searched for a solution for quite a while. I hope more people with this problem find this helpful as well!
