### ISSUE TITLE
I want to go back to using NMM, but when I download mods from Nexus it doesn't work

### ISSUE THREAD

**Issue by spymann** [TanninOne/modorganizer#512]
I downloaded MO and I liked the concept of it, but it got way too technical. So I decided to go back to NMM, but now when I download a mod from Nexus they automatically get transfered to MO instead.
How do I fix this?

**Comment by TheGreenDragon** [comment]
Inside NMM click on the gear icon at the top of the window. In the General tab ensure Associate with NXM URLs is checked. Then click the Download Options tab and click the Fix It button under the Download Fix/Tweaks section. Does this resolve the issue?

**Comment by spymann** [comment]
No, it did not. It still downloads it in Mod Organizer

**Comment by spymann** [comment]
No, it did not. It still downloads it in Mod Organizer

**Comment by TheGreenDragon** [comment]
What browser are you using?

**Comment by TheGreenDragon** [comment]
I found this link that should help you set NMM back to default:

http://forum.step-project.com/topic/3619-you-can-now-open-nxm-files-using-multiple-programs/

**Comment by spymann** [comment]
Oh nevermind I fixed it myself, I just reinstalled NMM, but thanks for your help, TheGreenDragon ^^

**Comment by TheGreenDragon** [comment]
Glad to help.
