### ISSUE TITLE
I lost all my mods and load orders for no reason and I dont know how to get them back.

### ISSUE THREAD

**Issue by Blancer** [TanninOne/modorganizer#514]
I turned my computer on and opened up mod organizer only to read that the files modorganizer.exe was missing, so I opened it from the rar file i had stored and it opened a completely clean slate of plugins and mods. Idk what happened but Id really like to know so I can get back to playing skyrim.

**Comment by Percephere** [comment]
ModOrganizer2 Alpha is mostly for Fallout 4. I'm not really sure it's connected to Skyrim in any way by default. Re-download ModOrganizer from the Skyrim Nexus and install it back into it's usual place. Your mods and load order should be untouched unless you deleted them.

**Comment by Blancer** [comment]
Well I honestly don't know what you mean by modorganizer  2 alpha. I don't see anything like that on the nexus page. And I did reinstall it but didn't have anything  there

**Comment by Percephere** [comment]
Here's a link for Skyrim, v1.3.11 - http://www.nexusmods.com/skyrim/mods/1334/?
This is the link for Fallout NV, v0.9.3 - http://www.nexusmods.com/newvegas/mods/42572/?
The version here on github is v2.0.3a and is intended for Fallout 4 (specifically 64x compatibility)

You may notice that the version for each game is different, as it reflects the game it is intended for.

I assume you're using MO2 Alpha because that is the most recent release

**Comment by Blancer** [comment]
So I checked and I have that version installed already, I got impatient and I downloaded the mods back to it. but now my load order is pooped, any way I can still get that back?

**Comment by Percephere** [comment]
I don't think so. It is possible your anti-malware or firewall program might've gotten rid of MO for no good reason - they do that sometimes.

**Comment by Blancer** [comment]
well thats... sheit, thanks for your help though!

**Comment by TanninOne** [comment]
MO reads its settings, mods, ... from the current working directory. If you run MO directly from an archive then that cwd is in some temporary windows dir. Of course there is no mods there... That doesn't mean your mods are gone, they may just be in a different directory.
As to why the exe was missing in the first place, yes, crappy AV software is a good bet.
