### ISSUE TITLE
ModOrganizer Alpha 3 Crashes on mod installation

### ISSUE THREAD

**Issue by reignofterr0r** [TanninOne/modorganizer#517]
Every time I install a mod, it successfully installs (unless it is a FOMOD with a custom installer) but then MO proceeds to crash every time. Attached is the dump.

[ModOrganizer.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/98072/ModOrganizer.exe.dmp.zip)

**Comment by Percephere** [comment]
This has been addressed before. In "ModOrganizer2\plugins" there is a file called "bsa_extractor.dll"

Rename it to "bsa_extractor.dll.bak" before you install mods, then back to "bsa_extractor.dll" before you launch the game through MO.
