### ISSUE TITLE
MO2 Alpha 3 stumped by large number of files for mod

### ISSUE THREAD

**Issue by FrostByghte** [TanninOne/modorganizer#519]
Using MO Alpha 3. When using query info on Armorsmith Extended a match to the file name cannot be found.  So I was thinking this might be a parsing issue.  AE has 96 files to be sorted through and this is a bit massive as far as mods are concerned.  Mod can be found here:

http://www.nexusmods.com/fallout4/mods/2228/?

To reproduce simply download the mod and query info.

**Comment by TanninOne** [comment]
This is a known problem but nothing i can fix. Nexus reports only 30 files through the api, to my knowledge i can't influence that
