### ISSUE TITLE
MO2a3 Settings-Nexus-OfflineMode not working correctly

### ISSUE THREAD

**Issue by jerry7890** [TanninOne/modorganizer#522]
Win7 64
MO2a3 try to connect to Nexus when "Offline Mod" is checked and entering NexusID in mod info tab by hand.

**Comment by TanninOne** [comment]
As the documentation for "Offline Mode" states: Disable automatic internet features. This does not affect features that are explicitly invoked by the user (like checking mods for updates, endorsing, opening the web browser)

**Comment by jerry7890** [comment]
My bad. I  didn't use "Check for updates" or anything of the above.
I only entered the NexusID (for sorting purposes to see mod & updates together in the mod list) in the information window and closed it.
It should not accept closing the info window as request for update or whatever,
Anyway its minor and not really important.
Tnx for the answer.
