### ISSUE TITLE
MO2 Fallout 4 CTD

### ISSUE THREAD

**Issue by Arthur-Neto** [TanninOne/modorganizer#524]
The game doesn't open anymore, I disabled every mod and the game still CTD on main menu, I managed to get the crash log, I don't understand a thing: 

[01/26/2016 - 02:33:15PM] Papyrus log opened (PC-64)
[01/26/2016 - 02:33:15PM] Update budget: 1.200000ms (Extra tasklet budget: 1.200000ms, Load screen budget: 500.000000ms)
[01/26/2016 - 02:33:15PM] Memory page: 128 (min) 512 (max) 153600 (max total)
[01/26/2016 - 02:33:15PM] Maximum stack depth: 100

**Comment by rdunlap** [comment]
do you have esp's in your fallout 4 data folder as well as in MO2? I have revealed a bug i was outlining before posting that includes what MO2 will call in the right pane "Unmanaged" esp/esm's

Robert

**Comment by rdunlap** [comment]
even disabled this issue can and will raise.

**Comment by Arthur-Neto** [comment]
Well, I tried moving the unmanaged esps but nothing, but before I used unmanaged esps and they work, so I don't think it's the problem.
Before, the game crashes before entering on main menu, but after some tries it worked, now I keep trying, nothing.

**Comment by rdunlap** [comment]
Ok I had to check. It seems that MO2 is not handling unmanaged esp's well sometimes. I write mods and since I am not running xEdit in MO2 yet I have to do a lot of esp's in my data folder sometimes and MO2 don't like it when I do. Without fail it crashes over a certain amount.

**Comment by Arthur-Neto** [comment]
Oh, I moved everything that isn't from the game on data folder and now it works, strange...

**Comment by rdunlap** [comment]
ok so it is the same issue. :) Great, just do like me and make a mod just for your orphans. Its not terribly consistent about how many is too many but it will nosedive for sure. I just cant seem to get MO2 to give me a log that gives any info for Tannin to review. He may have to run it up in his debug environment and recreate it. Not terribly hard to do just put about 10-15 esps into the data folder of the game and try to run it. *(sometimes 4 is too many)

Robert
