### ISSUE TITLE
humbly requesting color based grouping feature.

### ISSUE THREAD

**Issue by inkwhiz** [TanninOne/modorganizer#527]
Hello Tannin.

just want to know if it is possible to add a way to assign a color code to installed mods, so each mod with the same color code is in a group.

At the moment in the left column rows alternate between white and grey all the way down the list.

As we can shift-click and Ctrl - click to select multiple mods at once I thought it would be pretty neat (idea wise) to right click on one of the installed mods and when the menu appears their is an entry field or box for typing in a hex decimal color code, then either the color of the row (or rows) behind the text is altered or inactive colored (web) buttons appear behind the text.

I thought about being able right click on a mod and left click on information and having a color picker tab added to that window could be another approach, but at present that means repeating the process for every single mod in order to group them.

**Comment by TanninOne** [comment]
There already is a grouping feature called categories.
