### ISSUE TITLE
MO2 Alpha3 Crash at Start

### ISSUE THREAD

**Issue by SoulBeaver** [TanninOne/modorganizer#535]
Hello,

these are my steps (Win10, x64):

1. Download MO2.A3 from GitHub.
2. Extract contents in a newly created folder C:/Users/Christian/Documents/Fallout Utilities/ModOrganizer
3. Run MO
4. Select "One MO per Game."
5. Crash on Splash image, dump included (can I post it here?)

Alternative try:

1. Delete MO2.A3 from folder
2. Redownload from Github
3. Extract contents in folder C:/Users/Christian/Documents/Fallout Utilities/ModOrganizer
4. Run MO
5. Select "One MO for all Games."
6. Select "FO4" from Dropdown menu
7. Crash on Splash image, dump included (can I post it here somehow?)

Suspecting that it might be because of filenames with spaces in them, I changed my folder to C:/Users/Christian/Documents/FU/ModOrganizer, but that did not fix the issue.

**Comment by TheGreenDragon** [comment]
See the following thread:

https://github.com/TanninOne/modorganizer/issues/486
