### ISSUE TITLE
Crashes when closing F04 Edit after using it through MO

### ISSUE THREAD

**Issue by KeltecRFB** [TanninOne/modorganizer#536]
Heya Tannin,

Good to see MO for FO4, here are some issues having thus far.

1,  MO was crashing after installing each mod but the renaming of bsa_extractor.dll to bsa_extractor.!dll stopped that which someone else posted about in here.  I renamed it back and attempted to install mod, received the error, and dump ...

[ModOrganizerInstallMod.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/119434/ModOrganizerInstallMod.exe.dmp.zip)

2.  MO also Crashes after using F4Edit to check load order, create patches, and etc.  For the log post, specifically after checking load order.

[ModOrganizer.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/119421/ModOrganizer.exe.dmp.zip)

In Re Features:

When are you going to add Configurator in?

Thanks!

KeltecRFB

**Comment by TheGreenDragon** [comment]
FO4 Edit issues are known. See the following thread for what we have found thus far:

https://github.com/TanninOne/modorganizer/issues/513
