### ISSUE TITLE
[Feature Request] Add an option to specify mod category during install

### ISSUE THREAD

**Issue by nikolay-borzov** [TanninOne/modorganizer#541]
Rarely user leaves a mod without a category(ies) assigned.
It could be the same category widget as in the Mod Info dialog.
Would be great to make it optional (can be disabled in settings)

**Comment by TanninOne** [comment]
This would be a lot of work for very little gain. The different installer mechanisms (depending on the format of the mods) are implemented as separate plugins (6 currently), each one would have to be modified. With the c# scripted installer I don't even have control over the ui as the installer itself controls the dialog design.

**Comment by nikolay-borzov** [comment]
We can add support only for the simplest installer mechanisms - archive of files (not FOMod or BAIN).

**Comment by TanninOne** [comment]
No, sorry, this is not worth the effort. This would simply be a functionality duplication. I see no problem with setting categories after installation.
