### ISSUE TITLE
[Feature Request] Add mod generic url/version fields

### ISSUE THREAD

**Issue by nikolay-borzov** [TanninOne/modorganizer#542]
Currently MO supports only nexus url/versions. 
It would be great to add a generic field to keep non-nexus mod url/version.

1. Rename `Nexus Info` to `Mod Info`
2. Rename `Mod ID` to `Nexus Mod ID`
3. Add a new section on the top of the tab:
    1. `Mod Url` (if nexus url is specified `Nexus Mod ID` updates)
    2. `Version` (existing field)

Also context menu item `Visit on Nexus` can be renamed to `Visit on Web`

**Comment by ThosRTanner** [comment]
Same as #308 I think. However it's harder to do version as other sites will probably not make version numbers accessible in the same way (though if the mod is an fomod file then the version information in that will be used)

**Comment by nikolay-borzov** [comment]
Agree about versions check. It could be implemented later and not so necessary.
Closing the issue.
