### ISSUE TITLE
Mod Organizer not downloading Nexus Mods via download with manager

### ISSUE THREAD

**Issue by akiresenpai** [TanninOne/modorganizer#545]
when I was trying to download mods the "download with manager" option doesn't work for my MO and yes I said yes to handle Nexus Links/Mods and associated with NMM . I end up having to download the mods using manual download

**Comment by TanninOne** [comment]
If this is all the information you're going to provide my answer has to be: "umm, ok."

Please check out the step forum, there are plenty of threads about this kind of problems.
