### ISSUE TITLE
No MO2A4 Profile INI files being used.

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#546]
Just downloaded the Alpha 4 and it appears to be using the games default ini. I have only 2 profiles. one set for 5760X1080 resolution and one set up for 1920X1080 so I can run small when working on mods. When I start up I am getting the generic setup with 1920X1080 and none of my custom INI settings no matter which profile I select.

NB: it would appear that the 32bit support is much more stable. I was able to open FO4Edit and make an edit and save with no crash.

Tannin the installer was perfect. It went online and grabbed the dependency's it needed with no issues. Offered me the portable option on first run. NIce. :)

Robert

**Comment by rdunlap** [comment]
Just verified it. Placed the Default profile INI's into Documents\my games\Fallout4 and it was used. I have checked to be sure the folder and files are writable but it was not a problem an hour ago for Alpha2 *(I skipped 3 after testing and posting due to the need to use FO4Edit stable fashion) So is this due to a change in the Interface or the VFS that broke it?

Robert

**Comment by rdunlap** [comment]
This issue is still open as of Beta 1

Robert

**Comment by TanninOne** [comment]
Please use issue #681 to track this as it contains more information
