### ISSUE TITLE
Thank you Tannin and One Issue Persists

### ISSUE THREAD

**Issue by KeltecRFB** [TanninOne/modorganizer#551]
Thank you for working on this project for FO4, we all appreciate it and see progress with the latest release!

The one issue that is persisting, is the **bsa_extractor.dll** issue in which you have to rename it to **bsa_extractor.dll.bak** to install a mod to prevent any crashing and then rename it back to bsa_extractor.dll to launch the game through MO without any possible issue.

Thank you for your work and time!

**Comment by TanninOne** [comment]
The problem with bsa_extractor.dll is that it's outdated and no longer compatible. Unfortunately the plugin mechanism I use doesn't appear to support version checks or I haven't figured out how to use them.

I'm currently not distributing bsa_extractor (and nmm_import) with the installation package so as long as you install fresh or over an installation with bsa_extractor deleted you should be fine.

**Comment by KeltecRFB** [comment]
Thanks Tannin!

I moved the dll to a newly created folder, unused plugins, and keeping it there just in case.  I'll close this for you since it is not an issue.
