### ISSUE TITLE
Saving new data in FO4Edit is writing the esp back to Data instead of the mod folder.

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#553]
As stated I open an esp to edit and make some change. Save the esp in xEdit and instead of writing back to the original file or writing back  to overwrite its writing back to Data. Interestingly The original file goes away as expected during a save since xEdit appears to delete the old file then write new. Is overwrite functionality not live yet?

Robert

**Comment by TanninOne** [comment]
Correct, this is currently the expected behaviour as no re-routing to overwrite happens yet.

**Comment by rdunlap** [comment]
Ok cool. I knew it was expected up to and including Alpha 3 so I tested it for 4. :) Thanks for the response. You guys made large steps forward with this release.
