### ISSUE TITLE
Installer issue

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#555]
The installer will not properly overwrite or clean out old versions of executable's and or plugins. I chose to leave the original MO for Skyrim in place and do a update/overwrite install so that all my mods and such would be in place. Got a hard error on MO2A4 start. Cleaned out the folder of all the files/folders contained in the installer and ran it again. This time no error and everything runs well.

Conclusion is that the installer is not overwriting something that it needs to or that some file is left from the old version that is conflicting with the new code. I suspect its in the QT stuff. Maybe the older MO uses an earlier version and the new one needs updated and the installer is not recognizing this.

Robert

**Comment by TanninOne** [comment]
The MO2 installer does not support upgrading from MO1, I don't think I will be changing that.
I don't want the installer to delete any files that the user installed manually. I.e. I won't be bundling bsa_extractor.dll any more but if someone else chooses to create builds, the installer shouldn't force you to re-install it every time.
