### ISSUE TITLE
"unknown game" error

### ISSUE THREAD

**Issue by RageRaptor** [TanninOne/modorganizer#558]
Trying to install "Configurable New Dialog English" or "Easier Hacking with Options" for fallout 4 with MO results in an error box popping up with the text "unknown game" in it, followed by another error message saying "installation failed (errorcode 1)"
I'm using alpha 4.
Both mods seem to be using scripted installers, so that might be the issue.

NMM install works fine.

**Comment by TurboCartPig** [comment]
Configurable New Dialog English has an alternative installmethod in the form of an entire interface.ba2 file. As long as you have no other mods modifying that file it should work. At least it is for me. Of course this removes the "Configurable" part of the mod. Which is a bummer.

**Comment by Win52D** [comment]
I have seen this as well with  "Configurable New Dialog English"  and "Configurable Fusion Cores"

**Comment by TanninOne** [comment]
This is nothing I can fix. Scripted installers are handled by ncc (bundled in mo) which is derived from nmm. Now the nexus guys haven't updated their public repo in several months, so i can't build a ncc version that supports fallout 4.

**Comment by Ugachaga** [comment]
I'll just leave this here:
https://github.com/Nexus-Mods/Nexus-Mod-Manager
