### ISSUE TITLE
[Enhancement] I made a couple logos.

### ISSUE THREAD

**Issue by ogrotten** [TanninOne/modorganizer#559]
http://imgur.com/a/U6lT5
 
So I tried to create something for branding. A simple graphic that can be used consistently as an icon, web favicon, and startup screen; with a friendly, but techy, typeface.
 
The blue is a placeholder color. Can use any color you want. Can make any changes you want, or hell even take another evening making other candidates by trying something different. I had a couple hours and thought I'd see what I could poke out. obtw. . . I won't be heart broken if they're not used (=
 
I was thinkin about going back over the 1st one (big-m) and making it so that it's a right-triangle and fat line, rather than the L shape and the fat line..

**Comment by darthbdaman** [comment]
They look great. I don't like the white haze around the text though. It just doesn't look good to me. But otherwise nice work.

**Comment by LawLeewer** [comment]
It would be nice if we could choose between these logos like we can choose themes.

**Comment by TanninOne** [comment]
@ogrotten Thanks for the logos! I made a version of the second without the text in the center, would you mind if I use that for the icon?
I'd love to use the first one for the splash screen, could you maybe create a variant with transparency?

@LawLeewer This will be in the next release. Basically each instance can have its own splash screen and the game plugins can have a default splash.

**Comment by ogrotten** [comment]
@TanninOne @Tannin I tweaked it up for you a bit. Made some icon sizes, and added transparency and a variant.

Would you like something else? It seriously doesn't take long to do it at all, I can out something additional in this theme or spend some time doing another 3 completely different. whatever you want.

**Comment by TanninOne** [comment]
Logos are integrated in the current Betas. Thanks a lot ogrotten! You're also mentioned in the credits section of the about dialog. Please let me know if you'd like to be listed under a different name.

**Comment by ogrotten** [comment]
I saw the icons in 205. Glad to be of help! If you need any other art assets, I'll be more than happy to oblige.

Have considered doing style sheets in the themes of the various games MO supports.
