### ISSUE TITLE
MO fails to launch FO4

### ISSUE THREAD

**Issue by Osiragi** [TanninOne/modorganizer#560]
When I try to launch FO4 it just stops at (setting file times on esps) any ideas

**Comment by John16** [comment]
Have the same problem; looks like an problem with usvfs_x64.dll 




[usvfs_x64.dll_1455294036.dmp.zip](https://github.com/TanninOne/modorganizer/files/128262/usvfs_x64.dll_1455294036.dmp.zip)

**Comment by Osiragi** [comment]
Is there a solution for it?

**Comment by John16** [comment]
Restarting the PC, at least it fixed my problem

**Comment by Osiragi** [comment]
Nope, mine is still stuck

**Comment by John16** [comment]
Do you have any dump files in your Modorganizer directory from today?

**Comment by Osiragi** [comment]
No I don't have any

**Comment by John16** [comment]
... I don't know what this problem might be.
Maybe there are some more information in your log files ([PathToMO]\logs\usvfs-*.log)

**Comment by Osiragi** [comment]
its a clean install, and the logs folder is empty

**Comment by rdunlap** [comment]
it sounds like your AV is preventing the process from starting. Try this. Pause your AV for the shortest time it allows *(usually 10 mins) then right click the icon of MO2 and select run as Administrator. If it starts and it starts Fallout then you need to look up how to add exceptions to your AV for the folder and for the exe's and dll's. I had to do this for it to work. 

Robert

**Comment by Osiragi** [comment]
what is AV?

**Comment by Osiragi** [comment]
Nevermind

**Comment by Osiragi** [comment]
thank you Robert it works now

**Comment by rdunlap** [comment]
Not a problem. Your Antivirus product should allow you to set up exceptions for the folder and the exe's and dll's each dll and exe in the main MO2 folder needs its own exception and then one for the overall folder for some reason. Avast and AVG both required this of me.

Happy to help. Thats what the forum is all about.
Robert

**Comment by ogrotten** [comment]
@John16 how do you make MO write to the /logs dir?

**Comment by rdunlap** [comment]
it will do it when you run MO2 unless something like AV prevents the exe from operating. Usually when you shut down MO2 it will write out the log i think.

**Comment by ogrotten** [comment]
This is not the case. MO2 runs fine on it's own and the log dir is empty.

**Comment by John16** [comment]
I'm not sure but it can be possible that MO only write an log when you have set log level to Debug, but honestly idk

**Comment by ogrotten** [comment]
Log level is set to debug.

**Comment by TanninOne** [comment]
@ogrotten then you must be looking in the wrong directory. If you have created a portable install the log directory will be in your mo install dir, in case of a regular install it will be in C:\Users\<username>\AppData\Local\ModOrganizer\<game name>

**Comment by TanninOne** [comment]
So this issue was solved by rebooting/configuring AV to allow MO to run?

**Comment by ogrotten** [comment]
@TanninOne i was indeed looking at the main MO install dir. on my system, it's `b:\gameshit\mo 2a4\` that contains the exe. There's a `\logs` dir there.

This is confusing.
