### ISSUE TITLE
Mod Organizer assumes F4SE based mods are installed incorrectly

### ISSUE THREAD

**Issue by Stomp23** [TanninOne/modorganizer#562]
http://i.imgur.com/dJe3x08.png Not a huge issue, but Mod Organizer doesn't seem to recognize the folder layout for F4SE mods yet, 

Similarly to NVSE and FOSE, The F4SE folder goes inside the data folder. 

Mod Organizer recognizes NVSE and FOSE based mods with a similar structure so I assume it's just a matter of adding the F4SE to the "list" of things it counts as correct installation. (you can probably tell I'm clueless about this stuff)

I'm using Alpha 4( v2.0.4a ) In case that's important.

**Comment by rdunlap** [comment]
With Script Extender plugins I have always just treated those as an exception and manually placed the plugin folder into the actual data folder of the game. I had some issues with the extender in skyrim with MO 1.x and that was the solution given on S.T.E.P. and I have treated it as a blanket answer.

Robert

**Comment by Stomp23** [comment]
While I've never really had an issue with script extenders in MO before this, that does seem like a good thing to do until this is addressed.

Thanks!

**Comment by rdunlap** [comment]
Yea its a simple folder instead of a whole mess of stuff added to the game.

**Comment by rdunlap** [comment]
By the way you "Should" be able to click Okay at the screen shown and MO2 will go ahead and create the mod for you. It may be that it will just work. Worth trying and posting back about anyhow. 

Robert

**Comment by Stomp23** [comment]
Just tried in game, the mod seems to work fine, so the only real issue is Mod Organizer realizing that the file structure is correct it seems.

**Comment by rdunlap** [comment]
Cool its a UI issue then since everything is working under the hood so to speak. :)

**Comment by TanninOne** [comment]
resolved in current beta.
