### ISSUE TITLE
Mod Organizer.exe Deleting itself

### ISSUE THREAD

**Issue by jonny420** [TanninOne/modorganizer#563]
Hi, before i turned off my pc the program was working fine but then then when i turned it on in the morning, the mod organizer.exe was completely gone. What should i do?

**Comment by TheGreenDragon** [comment]
It sounds like your antivirus software may be to blame. Exclude the MO folder in it and see if the problem persists.

**Comment by TanninOne** [comment]
How plausible do you think it is that MO would delete itself? This is either a virus or antivirus or user error.

**Comment by jonny420** [comment]
ok thanks
