### ISSUE TITLE
[MO2A4] .esp plugins not being loaded

### ISSUE THREAD

**Issue by UrbanCMC** [TanninOne/modorganizer#564]
I'm having an odd problem with Alpha 4 on my Windows 10 system, in that most texture mods are working fine, although some aren't (most likely related to #532), but none of my .esp mods are loaded.  

This problem occurs with both Fallout 4 and LOOT, where nothing except for Fallout4.esm is displayed.
I've taken a look at the [usvfs-log](https://github.com/TanninOne/modorganizer/files/129711/usvfs-2016-02-14_13-22-41.txt) and it looks like they are found and redirected fine, but I don't know enough about the library to be sure.  

I hope it'll be of some help in figuring out what's going on, and if you need any additional information just say the word.

**Comment by LtRskn** [comment]
I am having the same problem with Alpha 4 on Windows 10. A custom texture mod I made (no esp) for my pipboy is loaded onto my character. No other mods that have esm's or esp's are being loaded in either Fallout 4 or LOOT.

I did not have this issue with Alpha 2.

**Comment by rdunlap** [comment]
Can you both check something? I have had some pretty strange things happen with my AV interfering with MO2 all Alpha's temporarily suspend your AV and run MO2 and the game and what is the result? The file activity from MO2 seems to hit AV programs where it panics.

Robert

**Comment by UrbanCMC** [comment]
Just gave that a try but at least for my part there's no difference, whether my AV is running or not.

**Comment by rdunlap** [comment]
Ok it was worth checking though. I have had to even delete my exceptions and re-do them when A4 released. Every time the footprint changes the AV program goes nuts.

Robert

**Comment by LtRskn** [comment]
I tried creating an AV exception for MO -- didn't make a difference. Then tried disabling AV entirely, also no change to the esp's not loading....

**Comment by Dragon02022003** [comment]
I had this same problem before with MO Alpha 3. My issue ended up being with NMM. Once I took everything out of NMM and setup MO as my main mod manager I have not had any issues with textures or ESP's. I currently still have NMM installed on my PC but it is not used.

**Comment by Freso** [comment]
I'm seeing this occasionally (though fairly frequently - between 25% and 50% of the time, I'd guess.) too. Closing LOOT/FO4 and starting it again will usually make the program see the VFS properly. Does this happen for you every single time, or just occasionally like for me?

**Comment by klausman** [comment]
I switched to the beta channel for FO4 about three weeks ago and with FO4 v1.4+ the problem is gone entirely.

There still are non-MO issues (like Reshade/ENB stuff not working properly if you nuke the intro videos(!)), but ESPs load just fine now.

**Comment by LtRskn** [comment]
I am happy to report that all is working again -- esp's from mods are now loading again after I did two things -- I switched to the beta per klausman's suggestion, and I moved my game install back to the C: drive from an alternate install location. One or the other, or a confluence of both, have led to success. Funny thing is that the alternate install location (using Windows symlinks) worked previously, so I didn't think it was an issue.

**Comment by UrbanCMC** [comment]
I can confirm that it definitely is an issue with symlinks. When using with symlinks, .esp's are still not loaded. As far as I'm concerned the issue is resolved, since it works just fine without it.  
It would, however, still be nice to see symlink support some time in the future.
