### ISSUE TITLE
MO adding lines to skyrim.ini

### ISSUE THREAD

**Issue by WalrusInAnus** [TanninOne/modorganizer#566]
I don't know when it started (I am sure it didn't happen in past, but what exactly past is I have no idea), but since unknown time ago, MO has been adding

bInvalidateOlderFiles=0
SInvalidationFile=ArchiveInvalidation.txt

into my skyrim.ini. I have the inis always open in Notepad++, and everytime I run MO, I get this popup that the file changed and whether I want to reload it, which is annoying.
I am using MO 1.3.11.
[Here](http://forum.step-project.com/topic/9262-mo-adding-lines-to-skyrimini/) is a discussion about the problem.

**Comment by TanninOne** [comment]
Yes, so? How are these lines in an ini file a problem? A problem is when functionality doesn't work as expected.
MO has do update bInvalidateOlderFiles and SInvalidationFile to enable/disable archive invalidaton. The lines you quote are added when archive invalidation is disabled in MO

**Comment by WalrusInAnus** [comment]
...except for the fact the files are being added regardless of settings.
This wasn't happening in previous versions, and everything worked just fine, which is why I believe it's a bug of some sort. At the very least it's extremely annoying.

**Comment by TanninOne** [comment]
Nope, I just checked the source code and tested, there are only two situations where MO will set bInvalidateOlderFiles=0
a) When you manually uncheck the "Archive invalidation" box
b) When you switch to a profile where AI is disabled

If bInvalidateOlderFiles=0 is set in any other situation then it isn't MO.

**Comment by WalrusInAnus** [comment]
My default profile has the AI checked and the ini file is still being rewritten with these two lines. I don't switch profiles. This happens on MO startup. I have no idea what else could be doing this when the only thing touching the files is MO.
