### ISSUE TITLE
[Feature Request] Option to always write to overwrite folder for executables

### ISSUE THREAD

**Issue by lampuiho** [TanninOne/modorganizer#568]
Please add this option to the executable edit menu.
This way, FNIS files or other modding tools will generate files to only the overwrite folder and not overwrite the original files.

**Comment by Mengmoshu** [comment]
I second this feature. My main reason for not using FNIS was the difficulty in understanding how it would behave when using Mod Organizer. An option like this would make it easy to explain in guides how to use FNIS and similar tools with MO. I know I'd be likely to use it with xEdit next time I'm setting up a Skyrim instance.

**Comment by TanninOne** [comment]
This has been discussed here: https://github.com/TanninOne/modorganizer/issues/457
And there I also explained why what you're requesting can't be implemented.

**Comment by lampuiho** [comment]
The difference here is I am suggesting to make it a togglable option. If you make a copy of files for files that are all opened for write and read access to the overwrite folder, disable the delete api for files in mod folders, and hook the rename function to redirect files put inside data folder to overwrite folder, it should work. Finally, add another sub-option for comparison of files opened for write access would be a plus too.
