### ISSUE TITLE
MO 2.0.4 installer displays 'Error message'

### ISSUE THREAD

**Issue by JPBt** [TanninOne/modorganizer#570]
Hi Tannin, couldn't install MO 2.0.4 (installer).
I deactivated firewall and anti-virus. The internet connexion is OK.
I tried the day after, after rebooting, same problem.
I disabled everything in the install except 'Qt DLLs'.

I realise other people don't seem to have that bug but still it happens...
Maybe a problem with GitHub servers?

Anyway, maybe you should put a **zip** version too...

![error on install with mo 2 0 4 installer](https://cloud.githubusercontent.com/assets/17249039/13046398/ce8b1098-d3d8-11e5-8549-cd1f04c83644.jpg)

**Comment by TanninOne** [comment]
This is a network problem, nothing I can fix. Certainly is very robust, it certainly didn't fail two days in a row just for you. Also I assume you got the installer from github as well?
I'm willing to bet your firewall is preventing the installer from downloading.

Also the optional downloads are all available for manual download.
