### ISSUE TITLE
MO2

### ISSUE THREAD

**Issue by LordNino215** [TanninOne/modorganizer#571]
While running the application a log file was created in the 'logs' folder which continuously swelled up. it reached 30 some odd gigs before i noticed. Started over, tried again and the same thing happened. Just thought yous would want to know.

**Comment by TanninOne** [comment]
Of course i know my tool creates a log, but it shouldn't be this big. However, since you're not writing anything about the content of the file (i.e. Which messages appear a lot) there is nothing else I can say.
Also, as you might guess "MO2" isn't the greatest title for an issue report.

**Comment by LordNino215** [comment]
Sorry for not being more specific. When I tried to see what info was being
logged, (and I shouldn't have been surprised) the 30-some gig
log file crashed notepad ++, then wordpad, then Word. I never got to see
the contents. should have put that into the original post.
Thought you would like to know.
