### ISSUE TITLE
[MO2A4] Path Selection Does Not Include Overwrite

### ISSUE THREAD

**Issue by antimodes201** [TanninOne/modorganizer#572]
Note sure if this is truly a bug or pending feature.

You can redirect Downloads, Mods, Caches, and Profiles per instance but you cannot set overwrite, defaults to appdata location.

**Comment by TanninOne** [comment]
It's neither. Is there a particular reason you want to be able to change that directory?

**Comment by antimodes201** [comment]
For those who have limited os root drives.  Also in the event you wanted to
backup the directory if you moved the others it would be missed.

Personally I do all of my development out of overwrite as its easier to
drop in and out changes there.  Once Im happy with a release I can rclick
and turn it into a mod and then incorporate it into one of my profiles.

Cheers,

Bob Krause
NetApp System Engineer

**Comment by TanninOne** [comment]
Ok.
I usually consider "overwrite" a temporary folder, mo even gives a warning if there are files in overwrite so i don't think of overwrite as taking up space in the regular case or containing anything you need to backup.

I do however see how it will be easier to keep mods there during mod development so I will add this in the next release.

**Comment by TanninOne** [comment]
fixed in beta 2
