### ISSUE TITLE
Nothing works at all 

### ISSUE THREAD

**Issue by sirxup** [TanninOne/modorganizer#573]
I'm beyond frustrated at this point. I can't get any of the versions to work what so ever be it MO2 alpha 4 or alpha 2. Alpha 2 will load up perfectly but it just won't run the game it sits.. I switched to Mod Organizer because I couldn't get Nexus to work, and Alpha 4 was working flawlessly but then I decided to change the download directory/mod directory and cache. After doing so I received a "Default profile error" when trying to load it back up.    Now I can't get any of the mod organizers Nexus, Mod organizer, and even other organizers that were made by users on Nexus to work no matter what it is it's extremely frustrating and I've been at it for hours with no solutions at all, and reading various forums with 0 return. I just want to know is anyone in this boat. I've had problems in the past with games but I've always been able to solve them I'm all out of ideas on this one.

**Comment by TanninOne** [comment]
Maybe you should consider the problem is on your side if you can run neither nmm nor mo.
Maybe you should post a bit of details about your problem that we can analyse instead of an endless tirade that just says "doesn't work"
This is an issue tracker not the wailing wall.

**Comment by sirxup** [comment]
I apologize,  I did not mean to sound angry or come off as making accusations.
