### ISSUE TITLE
alpha 4 installer stopped working today

### ISSUE THREAD

**Issue by darkconsole** [TanninOne/modorganizer#575]
fresh install of windows 10 oem trying to get back up and running. it attempts to download something, fails instantly.
![capture](https://cloud.githubusercontent.com/assets/9095897/13206319/68f3ad76-d8b0-11e5-8608-1f7ae1889a8a.PNG)

**Comment by darkconsole** [comment]
14th attempt (not a joke) it went through. not sure. maybe that repo was just inaccessible for a while.

**Comment by vwspeedracer** [comment]
I've experienced this as well on two separate computers/networks.

**Comment by Freso** [comment]
GitHub is sometimes down. It doesn't happen very often, but it does happen. This sounds like it was one of those times.
