### ISSUE TITLE
Failed to initialize Plugin?

### ISSUE THREAD

**Issue by Elllvis** [TanninOne/modorganizer#579]
I get this error everytime I open up mod organizer:

failed to initialize plugin F:/Steam/steamapps/common/Fallout 4/ModOrganizer2/plugins/pyCfg:py: An unexpected  C+ + exception was thrown in python code

Also I cannot check off Auto archive invalidation! and I think that's why some of my mods aren't appearing in game!

I switched over from nexus mod manager because I wanted the auto archive invalidation and also to check everything to make sure they work better and it actuall works worse. I really like this program so I thought it would be worth signing up on this thing and reporting the issues.

sincerely James(Elllvis)

**Comment by Elllvis** [comment]
oops wrong place to post this

**Comment by Elllvis** [comment]
Ok I fixed the error but still have no Auto Archive invalidation

**Comment by TanninOne** [comment]
a) please only report one problem per issue
b) there is currently no archive invalidation for fo4
