### ISSUE TITLE
Fallout 4 Beta support [NOT A BUG]

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#582]
NOT A BUG

Just a fast note to let Tannin know that the new beta which included a new fallout4.exe v 1.4.125 is working as expected and apparently there were no memory alignment changes. All my plugins and meshes, Textures, Materials are loading and working properly. 

Side note:
I use an ENB most of the time and when i took it out due to an issue he had with one version ALL my crashes went away. He says compatibility with other injection is not expected to be stable yet so no surprise there but I just wanted to throw it out for others who may be using ENB and or other post process methods. 

Have been running for a week and a half now with nothing for post processing and have had zero crashes or issues loading the game.

Robert

**Comment by kstarler** [comment]
I cannot get profiles to load with the latest FO4 beta. The default profile will load fine, but specific profiles all freeze at the "Press any key to continue" screen as the intro music starts. The music will continue to play, but the game simply stops loading anything beyond that point. Using Win 7 64 bit.

**Comment by rdunlap** [comment]
Let me try it on my Win 10 machine. I have a couple of profiles i use to test my mods using specific resolutions. 
Do you have a single game profile or a multi game install?

**Comment by kstarler** [comment]
Multi-game. I may have figured it out. It looks like nVidia FleX may have been the culprit preventing it from loading, as my default is using old .ini files.

**Comment by LeFlemard** [comment]
You're lucky, mine only load the esp ;_;
