### ISSUE TITLE
Launching SKSE through MO opens in a tiny window

### ISSUE THREAD

**Issue by Aiwenyar** [TanninOne/modorganizer#583]
Following the instructions here: https://www.reddit.com/r/skyrimmods/wiki/beginners_guide  I added the skse_loader.exe launcher to MO.  However, whenever I run SKSE through MO, the game opens in a tiny window, impossible to play in.

My resolution is set at 1920x1080.  I do not have this issue when launching SKSE outside of MO.  Any help would be appreciated, as this is preventing me from using Mod Organiser,

**Comment by GSDFan** [comment]
Run the game launcher from inside of MO and set your resolution. Each profile in MO has its own ini files.

**Comment by Aiwenyar** [comment]
Cheers, mate!
