### ISSUE TITLE
[MO 1.3.11] Skyrim - Tools not creating patches/files 

### ISSUE THREAD

**Issue by Skibidibbydibyodadubdub** [TanninOne/modorganizer#589]
Howdy,

My MO has been working normally up until the most recent update on the Nexus version. After this when running tools such as Skyproc for Requiem or Duel Sheath, or even FNIS - the program does not save the files that these tools create. This error occurs across all three programs, so it isn't really attributed to a single one of them. 

In the case of Skyproc:
The tool is launched, and the patcher runs normally without error - however the patched esp never appears. 

In the case of FNIS:
The updated animations do not occur, and no settings, such as "do not show this message again" are not saved.

I've tried running the program with administrator rights, reinstalling all effected programs (skyprocs/FNIS) but nothing seems to be working. It might be an issue with the override folder? Would using the most recent version alpha here (2.0.4a) resolve this? I really don't know. Any help on solving this would be greatly appreciated.

**Comment by Skibidibbydibyodadubdub** [comment]
Figuring that the first suggestion would be 'Use the Alpha version' I updated to 2.0.4. Upon trying to use skyproc for requiem and/or duel sheath - with the current alpha neither will launch java after loading the vfs, and FNIS provides the error during patching of: >>Warning: Bad installation. Generator not run from <Skyrim_Data>\Tools\GenerateFNIS_for_Users.<<

Not sure what is happening still.

**Comment by TanninOne** [comment]
Without any other information (like logs or where you're even expecting the modified files to show up) and considering this has been working for thousands of users for months I assume you're looking in the wrong place for the file.
