### ISSUE TITLE
Mod Organizer file collapse into single folder 

### ISSUE THREAD

**Issue by Eaglebane06** [TanninOne/modorganizer#590]
Running Mod Organizer with Skyrim. Game working normally, and I shut down normally. When I reopen Mod Organizer the Mod list (on the left side) have collapsed into single folders. So lets say BetterShapedLoingbows now has about 20 mods listed inside its folder. I cannot move them out. They are not tied to each other by category, priority listing, or any other link (that I can find). Dragging and dropping them out of the folder does not work. 
This happened a few time with the result was to rebuild the game from scratch in Mod Organizer. 
Is this an issues that others have seen and is there an easy fix??? help!

**Comment by GSDFan** [comment]
You most likely have the view sorted by Categories. To change it select No groups from the drop down in the center bottom of the pane.

**Comment by Eaglebane06** [comment]
I have removed all the categories links. There were only a few that had the boxes checked and I double checked to see if it was sorting by Categories and it is sorted by priority. Not sure if I can get a screen shot to show the issue... may have to take a picture.
The plugin side (right side) is still correct... Mod order (left side) still has correct priority order but for example Detailed bodies mod (pri 189) is grayed out and now sits at Pri 10 but, has a > carrot. 
When you open the carrot, an indented list of mods shows starting with ApachiiSkyHair (pri 10) SKYUI (pri 14) Remodeled Armor (pri 21) ect, etc, with Detailed Bodies at 189 (not grayed out) - a total of almost 30 mods. then it picks up with unmanaged HighRes Texrure Pack01 in the normaly list. 

I will try and get a screen shot...

**Comment by Eaglebane06** [comment]
![img_1336](https://cloud.githubusercontent.com/assets/17505949/13375138/26913986-dd55-11e5-931e-f4c233739c2d.JPG)

Here is an image of the load order (Left Side) Hope this works...

**Comment by Eaglebane06** [comment]
I also tried to delete Detailed Bodies but then a new Mod heads up the list. When I reinstall Detail Bodies, it goes right back to the grayed out...

**Comment by TanninOne** [comment]
Look below the mod list. Change "Categories" to "No groups"

**Comment by Eaglebane06** [comment]
Alright got it... I rebooted and then selected No groups and they went back to normal... thank you for your help!!!!!
