### ISSUE TITLE
Tab index is wrong in Settings > Paths (Alpha 4)

### ISSUE THREAD

**Issue by vuoriliikaluoma** [TanninOne/modorganizer#596]
Tabbing through the fields in Settings > Paths, it goes:

1. Mods button
2. Caches
3. Downloads
4. Caches button
5. Mods
6. Downloads button
7. Profiles
8. Profiles button
9. OK
10. Cancel
11. Tab

Checked the other settings pages as well, they seem fine.

**Comment by TanninOne** [comment]
fixed in beta 2
