### ISSUE TITLE
Unable to obtain public key for StrongNameKeyPair; installation failed (errorcode 5)

### ISSUE THREAD

**Issue by Jathar** [TanninOne/modorganizer#597]
When attempting to install SkyUI and other mods that use a fomod installer while using Mod Organizer I get this error [Unable to obtain public key for StrongNameKeyPair; installation failed (errorcode 5)]. I've tried running as administrator as many people with the same problem have done to fix it but that doesn't seem to work. I've also made sure that .NET Framework v3.5 is enabled in Windows and also tried downloading Mod Organizer away from any AC folders such as where I currently have it installed (F:\Program Files (x86)\Steam\SteamApps\common\Skyrim\ModOrganizer)

http://i.imgur.com/I8cYshg.png

**Comment by TanninOne** [comment]
See here for proposed solutions to the error: http://stackoverflow.com/questions/5659740/unable-to-obtain-public-key-for-strongnamekeypair

Please pet me know what (if annything) worked for you.

**Comment by GrantSP** [comment]
Not sure exactly what that page has to offer with regards to users trying to fix this issue.
The only things I could see that may be available for them is to check for low disk space or creating a dummy file in C:/ProgramData/Microsoft/Crypto/RSA/MachineKeys/
Neither of which seem very likely.

**Comment by TanninOne** [comment]
Is this still a problem in the beta 2?

**Comment by Jathar** [comment]
I'm still having the problem with mod organizer, I resorted back to NMM for the time being.

**Comment by TanninOne** [comment]
I'm not actually interested in which mod manager you use, the question (which you didn't actually answer) is: can you reproduce this exact issue with mo version 2.0.6

**Comment by Jathar** [comment]
After updating to 2.0.6 when installing fomods I get the error "Object reference not set to an instance of an object" "installation failed (error code 5)"

**Comment by TanninOne** [comment]
As I thought. This is a separate issue tracked in #719 . There's also a workaround in the comments.
