### ISSUE TITLE
MO2 Download failed: SendRequest Error

### ISSUE THREAD

**Issue by Gavrilian** [TanninOne/modorganizer#598]
Tried to install, but when it tried to download, it came up with a SendRequest error. I am clearly connected to the internet, and its run as an administrator, so I'm not sure what I could do to get around this. If I try to start Mod Organizer from there, it says its "side by side configuration is incorrect." I'm fairly new to bug reporting, so I'm not sure what other information you will need. Using Windows Vista

**Comment by TanninOne** [comment]
Either you firewall is blocking the installer or the dl from github is far less reliable than i expected.
During install, disable the packages that require a download (check out the list of extra files in the github files section like qt, ...), then, after install, download & unpack them manually.
