### ISSUE TITLE
MO 2 Alpha 4 NewDialog mod gives unknown game error

### ISSUE THREAD

**Issue by SadisticLquid** [TanninOne/modorganizer#600]
Trying to install http://www.nexusmods.com/fallout4/mods/619/?
Configurable New Dialog English ver0.6

when i click install it start's external installer but it gives error unknown game and then it it give's option to force close 
so cant install the mod

**Comment by LawLeewer** [comment]
Look at issue #558 
Seems like we will be seeing this error until NMM guys decide to update their repo
