### ISSUE TITLE
[Question] Export mods from 1.3.11 to 2.0.4a

### ISSUE THREAD

**Issue by LawLeewer** [TanninOne/modorganizer#601]
I was thinking of using 2.0.4a to manage my Skyrim mods aswell as the Fo4 ones.  
Is there any way to export the priority order AND the load order from MO1.3 to MO2?

**Comment by TanninOne** [comment]
The file formats didn't change so you should be able to use mo1 profiles in mo2. But mo2 will currently not run skyrim stablely.

**Comment by LawLeewer** [comment]
I have managed to import everything to MO2, but indeed it is not very stable, gave me lots of weird bugs ingame and took a shit-ton of time to launch.
Guess I'll stick to 1.3 for now :L
