### ISSUE TITLE
Using MO2 Alpha4 does not locate my FO4 files

### ISSUE THREAD

**Issue by Sneaks911** [TanninOne/modorganizer#602]
within my .../Steam/steamapps/common/Fallout4 folder.  It does locate my FO3 files, and my non-Steam Oblivion.  It hasn't located Steam Oblivion, Skyrim, or FO4.

![2016-03-05 2](https://cloud.githubusercontent.com/assets/16995276/13549540/e2db73c8-e2cc-11e5-8561-da9760a364ab.png)

**Comment by TanninOne** [comment]
Then your fo4 is not correctly registered in the registry. Use the browse button.
