### ISSUE TITLE
Mod Organiser v2.0.4 no longer loads F4SE or Standard Client

### ISSUE THREAD

**Issue by Waldoman** [TanninOne/modorganizer#603]
Hello just signed up to github :-)

I recently installed and ran the latest version of mod organiser 2.0.4 alpha for a few days it worked perfectly fine could run vanilla and modded games in fallout 4 but allas this has now stopped.

Please find attached the log file from a recent attempt to run the game through mod organizer showing the errors it encountered.

My system is windows 10 64bit, it should be noted that there was a few updates to windows 10 recently one being just at the beggining of march, it was shortly after this update that i could not get the game to run through mod organizer, this could just be coincidence but might be worth looking to see what changed and if it is to blame.

http://windows.microsoft.com/en-us/windows-10/update-history-windows-10

[usvfs-2016-03-05_21-59-31.zip](https://github.com/TanninOne/modorganizer/files/160077/usvfs-2016-03-05_21-59-31.zip)

**Comment by rdunlap** [comment]
check your AV. Turn it off for the shortest time allowed *(usually 10 mins) and try to start the game. If it works you will have to set exceptions for all the exe's and dll's in the MO2 folder

Robert

**Comment by Waldoman** [comment]
Thanks for the advice but my antivirus does not interfere with mod organizer (bit defender) I have checked its logs it has never interfered silently nor actively with it, as stated it worked before a windows update and to clarify windows defender also does not interfere with it either.

I have however disabled all antivirus and for good measure anti malware, and can confirm that it has made no difference sadly still a no go. :-/.

Again I have attached the latest log this being from the run with no antivirus and anti malware active, the results seem to be the same.

[usvfs-2016-03-06_16-44-11.zip](https://github.com/TanninOne/modorganizer/files/160443/usvfs-2016-03-06_16-44-11.zip)

**Comment by rdunlap** [comment]
yes seems the same. here is the problem i have with it being the update. I am on win 10 pro and got the same update and like you i have my game and MO2 on NON system drives and i have no issues from the update.

**Comment by rdunlap** [comment]
what we have to figure out is what is different in our cases and we will reveal what is your issue i am hoping.

**Comment by Waldoman** [comment]
Tist strange tist, i will go over everything else on my setup see if anything else has changed that could of caused the problem, fallout 4 has updated as well a while back but was working fine even after that so im not sure if the issue is there.

ill report back on here on what i find.

**Comment by rdunlap** [comment]
check to see if the permissions tokens changed after the update.

**Comment by Waldoman** [comment]
I have scowered my windows 10 logs in event viewer and found the error report for when mod organiser fails to load fallout 4 using f4se, but it does not say much new (attached)

User rights file permissions seemed to be normal i have access rights to all assosiated game files.

I did find problems with the sppsvc service or Software Protection Service (ties into windows security and activation) for some reason it had become disabled there is reference to issues with the service and tokens.dat i have read online. 

Rebuilding tokens.dat and reactivating the service then restarting seemes to have (for the time being) fixed the issue i can now run fallout 4 through mod organiser legacy and modded.
 
Why this fixed the issue i do not know as the service and assosiated tokens.dat is more to do with windows 10 activation of windows and other microsoft applications.

All i can say is wierd (my head herts lol)

[f4secrash.zip](https://github.com/TanninOne/modorganizer/files/160504/f4secrash.zip)

**Comment by rdunlap** [comment]
It still ties into basic User security tokens somehow. I have had some strange Windows reactions when any of the security services fails or faults. I am glad to see it up again and do post back if it happens again. I am watching windows 10 like the new creature it is. ;P  This is good information for Tannin to track and possibly when a knowledge base of issues and resolutions gets assembled this should go into it. Its not an intuitive fix.

Robert

**Comment by Waldoman** [comment]
Will do 

if anyone else has the same issue this is the guide i followed to fix it http://www.thewindowsclub.com/rebuild-tokens-dat-activation-file-windows.

I do not know if this would work for anyone else but its worth a try.

William.
