### ISSUE TITLE
MO 2 Alpha 4 Trying to install Fallout 4 Seasons Winter 3.0 but it's not working 

### ISSUE THREAD

**Issue by SadisticLquid** [TanninOne/modorganizer#604]
Downloaded and installed FO4 Seasons Winter 3.0 but there's no change's ingame
http://www.nexusmods.com/fallout4/mods/5810/?

has someone got it to work with MO?

also would mo need that new Fallout4Custom.ini
so we can do

http://wiki.tesnexus.com/index.php/Fallout_4_Mod_Installation
Open Fallout4Custom.ini with your favourite text editor.
* Note that this file was changed from Fallout4.ini following update 1.2
Add the following lines to your Fallout4Custom.ini
[Archive]
bInvalidateOlderFiles=1
sResourceDataDirsFinal= 

or is it needed?

put it in the data folder of Fo4 and started it with the normal fo4.exe and it worked in vanilla game so there is something with MO that makes it not work

**Comment by LawLeewer** [comment]
Are you sure there is no other mod overwriting it's textures?   I just downloaded the Seasons - Winter to test it and it is working.

And no, there is no need to change the .ini

**Comment by SadisticLquid** [comment]
quite sure since it's at the last place in the list and mo shows that it's not conflicting with anything

**Comment by TanninOne** [comment]
Is this resolved? What was the problem?
