### ISSUE TITLE
Add button (or similar) to deselect/reset categories

### ISSUE THREAD

**Issue by Freso** [TanninOne/modorganizer#605]
The current way to reset/deselect all categories, is to "click blank area". However, if your screen/window height is limited, there may be no blank area to click. It would be good to have a button (or other dedicated UI element), preferably with a keyboard shortcut, to do this.

**Comment by TanninOne** [comment]
There is always a at least a very narrow space (few pixels) at the very right of the list that is treated as empty area.
Also, you can deselect using the right-click menu. But I do agree this is not optimal...

**Comment by victorsegall** [comment]
This flew under my radar for a while, partly for the mentioned "click blank area" text in the UI.

From v1.3.11:
![Image of Category Deselection](https://i.imgur.com/qZEALEn.png)

"Deselect filter" is part of the context menu for category filter items.

That said, the same screen space used for the instructive text should be a button that does what the context menu entry does.

**Comment by TanninOne** [comment]
fixed in current version
