### ISSUE TITLE
[MO2a4] Create profile dialog warning about running game first.

### ISSUE THREAD

**Issue by GrantSP** [TanninOne/modorganizer#607]
The installer version of MO2 alpha4 with the option to use "instances" for multiple games is installed and I select a game. One of the first things I check is the 'Profiles' dialogue.

I notice there are no default profiles anymore and I'm reminded to create at least one along with the notice:

> ATTENTION: Run the game at least once before creating a profile!

Okay, fair enough I'll close this dialogue and run the game at least once. However, clicking 'Close' immediately brings the ATTENTION notice back up and the dialogue is now unable to be closed,
except by creating a new profile, but that then contradicts the instruction in the notice!

**Comment by TanninOne** [comment]
This is normal, though I admit it's inconvenient. closing the profile dialog would take you to the main ui of MO, but without a profile active the UI would break, so there is no way to close that dialog without a profile. Nothing is stopping you from leaving the profile dialog open while you start the game regularly though.
