### ISSUE TITLE
[2.0.4a] Windows installer does not create an uninstaller entry for programs/features

### ISSUE THREAD

**Issue by SierraKomodo** [TanninOne/modorganizer#609]
OS: Windows 10, 64-bit

Program was installed in E:/Games/Mod Organizer. The uninstaller exists in the folder, and functions properly, but when using Programs/Features or Add and Remove Programs in windows 10, Mod Organizer isn't shown in the list to uninstall.

Discovered while attempting to do a clean reinstall for another possible issue.

**Comment by TanninOne** [comment]
Duplicate of issue #550
