### ISSUE TITLE
Alpha 4: Mod Organizer crashes xEdit

### ISSUE THREAD

**Issue by fireundubh** [TanninOne/modorganizer#610]
VFS log tail ([full log](https://gist.github.com/fireundubh/e1df44e9928086c2fbf8)):

```
03:28:21.423 [C] windows exception c0000005
03:28:21.423 <10932:16644> [D] end hook of process 10932
<snip>
03:28:21.423 [I] releasing hook context
03:28:21.423 [I] 2 users left
03:28:21.424 [W] windows exception c0000374 from C:\Windows\SysWOW64\ntdll.dll
```

Here are the exception messages from VS.

```
Unhandled exception at 0x77BDE00B (ntdll.dll) in FO4Edit.exe:
    0xC0000374: A heap has been corrupted (parameters: 0x77C14270).

First-chance exception at 0x50276E6D (usvfs_x86.dll) in FO4Edit.exe:
    0xC0000005: Access violation reading location 0x010E000C.

First-chance exception at 0x77B439E8 (ntdll.dll) in FO4Edit.exe: 
    0xC0000005: Access violation reading location 0x00000004.

Unhandled exception at 0x77B439E8 (ntdll.dll) in FO4Edit.exe:
    0xC0000005: Access violation reading location 0x00000004.
```

Windows 7 SP1 (x64)
xEdit v3.1.3 (latest dev build)

**Comment by rdunlap** [comment]
An experiment for you. 

I have had crash logs look like that evolve from having to many esp's in the data folder instead of in the mod organizer structure. Make a folder in the mod organizer mods folder and move those esp's into it temporarily and enable them from there and see if it behaves better. Be sure to close and reopen MO2A4 once you move the esp's since refresh of the VFS tree is not wired up yet. 

 The number of esp's in the "Unmanaged" area that is required to cause this crash is not consistent. Since Alpha 4 I have only had it one or two times but it still happens. It does not appear to be related to overwriting of esp's its like there is not enough space allocated to list out and handle them in the Unmanaged list. "HUGE GUESS". Cant hurt to try it. 

Others have had issues with Win 7 with the previous alpha's but it has seemed to be straitened out with this one so I would not expect you to have any particular issue running it. Can also disable your AV for a run to make sure its not hitting the process and preventing the hook at runtime.

Robert

**Comment by fireundubh** [comment]
> I have had crash logs look like that evolve from having to many esp's in the data folder instead of in the mod organizer structure. 

Unfortunately, I have no other plugins than `Fallout4.esm`.

I redownloaded Fallout 4 and ran the launcher, which resets the `DLCList.txt`, `loadorder.txt`, and `plugins.txt` files in the `AppData\Local\Fallout4` directory. Alpha 4 was able to run xEdit this time. I'd attribute my fix to the launcher resetting the .txt files.

**Comment by fireundubh** [comment]
I didn't want to create more issues, so here are two more ways Mod Organizer crashes/freezes xEdit:

When trying to load a single plugin in xEdit:

1. Check only Fallout4.esm.
2. Click OK.
3. Crash.

Log:

```
FO4Edit 3.1.3 EXPERIMENTAL starting session 2016-03-15 21:12:09
Using Fallout4 Data Path: D:\SteamGames\Fallout 4\Data\
Using ini: E:\Users\fireundubh\Documents\My Games\Fallout4\Fallout4.ini
Using save path: E:\Users\fireundubh\Documents\My Games\Fallout4\Saves\
Using plugin list: C:\Users\fireundubh\AppData\Local\Fallout4\Plugins.txt
Using settings file: C:\Users\fireundubh\AppData\Local\Fallout4\Plugins.fo4viewsettings
Loading active plugin list: C:\Users\fireundubh\AppData\Local\Fallout4\Plugins.txt
Found BOSS load order list: C:\Users\fireundubh\AppData\Local\Fallout4\loadorder.txt
[Fallout4.esm] Loading file
[Fallout4.esm] File loaded
[Fallout4.esm] Start processing
```

When trying to load all plugins in xEdit:

1. Check all plugins.
2. Click OK.
3. Freeze.

Log:

```
FO4Edit 3.1.3 EXPERIMENTAL starting session 2016-03-15 21:14:44
Using Fallout4 Data Path: D:\SteamGames\Fallout 4\Data\
Using ini: E:\Users\fireundubh\Documents\My Games\Fallout4\Fallout4.ini
Using save path: E:\Users\fireundubh\Documents\My Games\Fallout4\Saves\
Using plugin list: C:\Users\fireundubh\AppData\Local\Fallout4\Plugins.txt
Using settings file: C:\Users\fireundubh\AppData\Local\Fallout4\Plugins.fo4viewsettings
Loading active plugin list: C:\Users\fireundubh\AppData\Local\Fallout4\Plugins.txt
Found BOSS load order list: C:\Users\fireundubh\AppData\Local\Fallout4\loadorder.txt
Fatal: Error loading plugin list: <EOSError: A call to an OS function failed>
[Fallout4.esm] Loading file
[Fallout4.esm] File loaded
[Fallout4.esm] Start processing
[SettlementKeywords.esm] Loading file
```

Note: `D:\SteamGames\` is a directory junction.

**Comment by Schizosaccaromyces** [comment]
I kind of fixed the issue with xEDIT (have this exact same problem myself). Basically, under MO, xEDIT seems to draw upon the base Fallout4 plugins.txt files, hosted in Appdata/Local/Fallout4. You need to copy the contents of the plugins.txt file in your MO profile folder to that one, set it as read-only, and it should allow you to launch xEDIT now. Bear in mind that ANY change in your load order implies that you will need to redo this procedure before being able to launch xEDIT again. It worked for me under alpha 2.0.4.

**Comment by Sneaks911** [comment]
Using 2.0.4, I cannot open LOOT, or FO4Edit.  This is the error I keep getting for FO4Edit.
![2016-04-19](https://cloud.githubusercontent.com/assets/16995276/14648588/a6d43430-0628-11e6-9b10-2f1a5221680c.png)
I have made sure my files are not Read Only.  Loot doesn't even bother to load FO4 mods.  I get Oblivion load, even though I am running it through MO2.0.4
![2016-04-19 1](https://cloud.githubusercontent.com/assets/16995276/14648730/56272dca-0629-11e6-8fb3-adbd52442a2e.png)

**Comment by itunlimited** [comment]
Also, make sure that you don't have erroneous ESP in your data folder. I noticed when making patches, the saved ESP from xEdit will get saved in the games' data folder instead of overwrite. XEdit gets confused when trying to read ESP files from both the MO mods, and the games' data folder.

**Comment by TanninOne** [comment]
Does this still occur in beta 3?

**Comment by fireundubh** [comment]
I ran a few smoke tests:

* Loaded no plugins and closed xEdit
* Loaded a plugin and closed xEdit
* Loaded all plugins and closed xEdit
* Loaded a plugin, saved a new plugin, and closed xEdit
* Loaded a plugin, saved plugin with changes and backup, and closed xEdit

All passed. No crashes.
