### ISSUE TITLE
Alpha 4: Unlock after closing xEdit delayed on first launch

### ISSUE THREAD

**Issue by fireundubh** [TanninOne/modorganizer#614]
After closing xEdit launched through Mod Organizer for the first time, Mod Organizer will remain in the locked state for a longer duration than expected. Subsequent launch-and-close cycles produce significantly faster unlock times.

1. Open Mod Organizer.
2. Launch xEdit through Mod Organizer.
3. Close the application.
4. Observe: Mod Organizer will remain in the locked state for 15-16 seconds and then unlock automatically.
5. Launch xEdit again.
6. Close the application.
7. Observe: Mod Organizer will remain in the locked state for 4-5 seconds and then unlock automatically.

Windows 7 SP1 (x64)
xEdit v3.1.3 (latest dev build)

**Comment by TanninOne** [comment]
Who knows, this doesn't sound like an issue at all.
