### ISSUE TITLE
Alpha 4: Only Fallout4.esm is loaded into LOOT

### ISSUE THREAD

**Issue by fireundubh** [TanninOne/modorganizer#615]
When running LOOT v0.8.1-132-g1af3bc9 or [LOOT v0.8.1-243-g5f13072](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAB5c9dps_MhRTvBXEjW3sB8a/LOOT%20v0.8.1-243-g5f13072%20%2832%20bit%29.7z?dl=0) through Mod Organizer, only Fallout4.esm is loaded into LOOT.

**Comment by fireundubh** [comment]
pStyl3 was able to get all plugins loaded into LOOT [using LOOT's --game parameter in MO](http://forums.bethsoft.com/topic/1588424-rel-loot-thread-22/?p=25061624), but I was not.

**Comment by fireundubh** [comment]
New finding.

When I run LOOT through MO, a new folder is created in the root folder.

* Root: `D:\Games\`
* Mod Organizer: `D:\Games\Mod Organizer - Fallout 4\`
* New Folder: `D:\Games\Mod\`

I would guess that there's an issue where you need to enclose a path variable with quotes to handle paths with spaces.

**Comment by fireundubh** [comment]
Another finding.

I have a directory junction named `SteamGames` that links to `D:\Steam\steamapps\common\`.

LOOT was configured to use the directory junction to find Skyrim and Fallout 4 at:

* `D:\SteamGames\Skyrim\`
* `D:\SteamGames\Fallout 4\`

When I changed these paths in LOOT's settings to:

* `D:\Steam\steamapps\common\Skyrim\`
* `D:\Steam\steamapps\common\Fallout 4\`

All plugins loaded into LOOT when run through MO.

**Comment by fireundubh** [comment]
Unfortunately, subsequent attempts to run LOOT through MO produce this error in LOOT:

```
Error code: -1; Failed to get game data. Details: boost::filesystem::file_size: The request is not supported: "D:\Steam\steamapps\common\Fallout 4\Auto Loot.esp"
```

Notice the reported path is incomplete. The `Data` directory has been omitted.

**Comment by fireundubh** [comment]
Finding 4

LOOT's generated load order isn't shared with Mod Organizer.

**Comment by TanninOne** [comment]
Is this still a problem with Beta 2?

**Comment by fireundubh** [comment]
No.
