### ISSUE TITLE
Mod Organizer v1_3_11 The application was unable to start correctly (0xc000007b). Click OK to close the application

### ISSUE THREAD

**Issue by SadisticLquid** [TanninOne/modorganizer#616]
After installing MO alpha 4 for fallout 4 Skyrim's MO give's error 0xc000007b when trying to start it

should i just reinstall MO for skyrim? if i do will anything happen to mods or setups that are installed?

**Comment by TanninOne** [comment]
MO and its dlls are fully self contained. This could only happen if you overwrote MO1 with your new installation or if you had deleted one or more of the dlls shipped with MO and thus forced MO to use a dll from a global location.
