### ISSUE TITLE
[MO 2.0.4]Multiple issues, each detailed. Inc Installation-dotnet and saving via executeables.

### ISSUE THREAD

**Issue by neiljwd** [TanninOne/modorganizer#621]
### BACKGROUND
I had MO install just fine once, however had to reinstall windows, so I'm now on a **100% fresh Windows 10 Pro 64bit install, **so it's very likely im missing some common core components. I am the only PC user, and an admistrator. MO is run as an administrator. Each of its 4 "paths" in preferences are NOT set as read only.

### Problem 1, install/dotnet. (fix in below post)
MO Installation gets to [THIS POINT](http://i.imgur.com/OUZUclP.jpg) And fails evey time.
I have a second PC, so I installed there, fine, and copied the folder accross to the PC where it wouldn't install, location:_C:\Program Files\ModOrganizer._  MO now works(Fo4 plays with the mods), however it reports an issue with [dotnet (for NCC)](http://i.imgur.com/mwGLNtr.png). Microsoft .NET Framework 4 (Web Installer) I've tried that, and Microsoft .NET Framework 4.5 but both don't install as "_The .NET Framework 4.5 and this update are already installed on your computer._"
So that's problem one, any idea what I'm missing or how to fix?

### Problem 2, saving via executable.(work around in below post, but NOT fixed)
My second issue is in regards to Bodyslide executable opened via ModOrganizer, I can't [save as](http://i.imgur.com/Q5QMLp2.png).
No matter where to or what I name a Preset- I cannot save a new preset. Says[ "The filename is not valid".](http://i.imgur.com/Icn4kZw.jpg). I can save tho, overwiting a preset, just not create my own. I've tried both versions  of bodyslide, normal and 64bit.exe, both set to run as administrator.

It should be noted- this problem existed PRIOR to my above installation issue, when I'd installed fine.

So apologies for this long winded double problem,  tried to be thourough, please help!

**Comment by neiljwd** [comment]
**Problem 1 fixed! **Turned on .net framework 3.5 via "Turn Windows Features on or off". This was following GrantSP's(STEP forum) advice to follow [THIS GUIDE.](http://wiki.step-project.com/Guide:Mod_Organizer#Prerequisites).

**For problem 2 no fix**, but a work around for bodyslide presets in Mod Organizer 2, in case anyone encounters similar.
Go to   \Caliente's Beautiful Bodies Enhancer -CBBE-\Tools\BodySlide\SliderPresets within you MO Mods folder. Make a backup copy of CBBE.xml.

Now you can edit  CBBE.xml. Add new presets by copying a full preset, then just give it a new name. Or just change the names of some presets you don't use. You can now edit these sliders as normal, and just save to overwrite the main file with you editided in names.

**Comment by inedenimadam** [comment]
Just wanted to raise my hand and say "Me Too" for the 404 during installation.  I have both .net 3.4 and 4.5 installed, so that is not the issue.  It appears to fail during auto-download of C++ packages.  Maybe the link is incorrect in the installer (MS might have moved it?).  This is on a fresh W10 install.

**Comment by TanninOne** [comment]
Problem 1: fixed
Problem 2: please create one issue per thing you want to report because I otherwise can't track them separately
