### ISSUE TITLE
Alpha 4: Installer returning 404 Error

### ISSUE THREAD

**Issue by NexusAU** [TanninOne/modorganizer#625]
Hey, so today I did a fresh windows install so I had to reinstall Mod Organizer. However I'm getting a 404 Not Found error in the installer when it's trying to download the additional packages needed. I was wondering if there's a way around this.
http://i.imgur.com/Kcmg2et.png

**Comment by neiljwd** [comment]
Sounds exactly like the issue I had.
[Solution in here.](https://github.com/TanninOne/modorganizer/issues/621)

**Comment by NexusAU** [comment]
Enabling .NET Framework 3.5 fixed the issue, thank you so much

**Comment by TanninOne** [comment]
duplicate
