### ISSUE TITLE
[Error] Could not use configuration settings for game "Fallout 4"

### ISSUE THREAD

**Issue by Moronmaster** [TanninOne/modorganizer#627]
![](http://i.imgur.com/JTGQhqT.png)

I am presented with this upon launching MO2 and selecting my Fallout 4 instance.
This issue is not present when attempting to launch an instance for Skyrim, for example.

**Comment by Skyshayde** [comment]
I believe Mod Organizer doesn't support Fallout 4 yet.

**Comment by TanninOne** [comment]
Does this still occur with beta 2?

**Comment by Moronmaster** [comment]
@TanninOne No, the issue has been fixed. Good job!
