### ISSUE TITLE
Special characters in mod names

### ISSUE THREAD

**Issue by WalrusInAnus** [TanninOne/modorganizer#628]
Today I tried installing mod called "Northfire's Photoreal Mountains". When I doubleclicked on the file in the downloads tab, the name changed to "Northfire&#39;s Photoreal Mountains". Apparently MO has problem "translating" some of the characters (I presume an apostrophe is not the only one).
Version 1.3.11.

**Comment by ThosRTanner** [comment]
Fixed by #328
