### ISSUE TITLE
MO alpha 4 F4se crashes after installing automatron

### ISSUE THREAD

**Issue by SadisticLquid** [TanninOne/modorganizer#629]
I had a working setup before automatron released and now neither F4se or fallout 4 exe work in MO
but both start game outside MO

tested Creating new profile with just fallout4.esm and DLCRobot,esm same issue so it's not load order or mods that do it something must have changed and it just wont work anymore

**Comment by emilykmb** [comment]
I'm having the exact same problem, uninstalling Automatron worked initially but after rebooting my comp it wont start again.

**Comment by SonicBog** [comment]
I had it working if I only had the Automatron esm checked and nothing else.
But when I enabled my mods, CTD.
Starting a new game with Automatron as top of list and other mods in my normal load order fixed the problem. Did not bother checking which mod was the culprit as I had only just restarted a new game anyway.

**Comment by SadisticLquid** [comment]
this was really weird bug i tested automatron using nmm and today tested starting my old modded game with MO and it just started with automatron and everything
