### ISSUE TITLE
Feature Request/information

### ISSUE THREAD

**Issue by primem0ver** [TanninOne/modorganizer#631]
I am writing/programming a utility that will make managing and creating merges easier (for when merged mods are updated).  All I REALLY need right now is to be able to refresh the plugins list so that changes to the load order and the plugins files are reflected in the plugins window (without MO recreating these files themselves).  A feature to refresh the mod list would also be nice so that mod folders I create manually would show up on the mod list (when I am separating the "overwrite" folder into more than one mod for example).

While I am at it, it would be nice to have a MO plugin interface so that we can write plugins for MO.  (I have written programs in Qt before).

**Comment by TanninOne** [comment]
When you run an external application from mo then mo automatically reads the changed plugins.txt and loadorder.txt, that's also how it works together with loot/boss.
Refreshing the mod list is not possible from an external tool, that is mo-specific data. I want to have the option to change my data structures and stuff without having to consider third party tools so you're on your own there.

Mo does however have a plugin api and with it you can change load order and add mods which will be immediately reflected inside mo.

**Comment by primem0ver** [comment]
Thanks for the info.  Which project is the API part of?  I tried looking around and I think I found the base class name(s) but having trouble locating the actual header file(s).  Is there a "getting started" guide/pointer/etc? I can figure out the needed methods from the interface(s) but 1) where are they? and 2) is there a core API plugins have access too?

**Comment by TanninOne** [comment]
You can find an intro to writing plugins here in the wiki. The relevant header files with apis you can access are in the modorganizer-uibase, mostly the ones starting with an i (for interface).
A lot of mos functionality is already implemented as plugins so many of my repos serve as samples

**Comment by primem0ver** [comment]
One more off topic comment.  I would like to have a pm conversation with you about your background and current professional situation if possible.  I am currently working on a large qt project that you may or may not have an interested in... but just thought I would run it by you since I am impressed by your approach to this project.  Your approach shares some similarities to my own.

**Comment by TanninOne** [comment]
Please contact me by PM or email if you want to discuss something off-topic.
