### ISSUE TITLE
Loot External Program Launching

### ISSUE THREAD

**Issue by Herbertofury** [TanninOne/modorganizer#632]
This mod organizer has worked perfectly for me so far, I have over 300 mods working perfectly fine with automatron dlc thanks to mod organizer. Only problem I have run into is its inability to launch loot for fallout 4 every once in a while, But it still does on occasion work perfectly fine. I have wrye bash, Fallout 4 script extender, and loot running perfectly fine when I launch them. Another error I have run into is its inability to open a FOMOD for the mod artillery but IDK what the error message was. usual just states unknown game and wont finish.

**Comment by Herbertofury** [comment]
I was also superized it detected FSE and Loot right away and I didn't even have to add them to launch EXEs

**Comment by Sneaks911** [comment]
While using Sort in MO2 v2.0.4 I get an error message every time. It 
![2016-03-24 1](https://cloud.githubusercontent.com/assets/16995276/14018560/7081661e-f19c-11e5-950a-1ae4979c56b7.png)
Then, when I try to launch LOOT through MO2 v2.0.4, I get these  
![2016-03-24 2](https://cloud.githubusercontent.com/assets/16995276/14018897/13c98738-f19e-11e5-9f24-c52b8ae5a558.png)
![2016-03-24 3](https://cloud.githubusercontent.com/assets/16995276/14018903/1a6e31ba-f19e-11e5-97ec-864ddf6de2a0.png)

**Comment by TheGreenDragon** [comment]
LOOT still fails occasionally on my end as well. I find that if I click "Unlock" in MO just after LOOT launches it succeeds more often than not.

**Comment by Sneaks911** [comment]
Unlock doesn't work for me.

**Comment by vrynex** [comment]
I worked with the LOOT creator, and we were able to figure that the 294 snapshot (now available as a separate download on the Nexus) works fine MO2v4.  I'm not saying that the two play nice with each other now, but at least now if LOOT locks up, it'll crash properly.
On a side note, if you were having the issue of having to close and Unlock LOOT but it still wasn't working, you would've had to go into Windows Task Manager and kill it from there.

**Comment by adamb70** [comment]
I managed to get it working with LOOT 294 by using the "Unlock" button workaround just after the LOOT progress bar finishes. Then once loot loaded and gave me the "Error code -1. Failed to get game data..." error, I closed the error message and went to the LOOT menu and chose "Clear user metadata". Next time I tried opening LOOT it worked as expected.

Not sure if this is just some coincidence on my end though.

**Comment by BobbyLee3294** [comment]
> Then once loot loaded and gave me the "Error code -1. Failed to get game data..." error, I closed the error message and went to the LOOT menu and chose "Clear user metadata". Next time I tried opening LOOT it worked as expected.

Does not seem to be a coincidence as I was able to do this numerous times with the same results. My only problem now is that after clearing the metadata, LOOT crashes when I hit the sort plugins button.

**Comment by TanninOne** [comment]
Is this still a problem in Beta2?

**Comment by Herbertofury** [comment]
Nope its fixed, works fine on my version, had to reinstall all mods once with random plugins unchecked using loot however so be careful  😊
________________________________
