### ISSUE TITLE
Suggestion: Allow us to add download link to a mod that isn't nexus mod

### ISSUE THREAD

**Issue by SadisticLquid** [TanninOne/modorganizer#636]
let's say for example u download a mod from somewhere else than nexus and said mod get's an update would be nice if visit link would open the download page for the mod

**Comment by TanninOne** [comment]
There is rudimentary support in mo to add support for other modding pages via plugin. This would be the right place to add this, but to my knowledge nobody is actually working on such a plugin so I have little interest in working on an api that nobody is using.
