### ISSUE TITLE
Suggestion: Add Markers, like in Wrye Bash

### ISSUE THREAD

**Issue by RhapsodySL** [TanninOne/modorganizer#639]
In Wrye Bash there's a feature called 'markers'. Markers were essentially marks for groups of mods that you could categorize into a particular section. It's a bit different than Nexus' own categorization system, and doesn't have to be bound to that list.

To be clear, I'm not suggesting custom categories; I'm basically suggesting a fake that stands out so you can see the break between different setups.

**Comment by TanninOne** [comment]
There are custom categories and you can group your mod list by categories which has this exact effect.
