### ISSUE TITLE
Coloumn Order

### ISSUE THREAD

**Issue by JingJang** [TanninOne/modorganizer#640]
I just did a clean install of MO and first thing I tried was to get get the priority column to the left corner, but I am unable to. I tested on alpha and version 1.3 and in both cases I failed. In some old version I was able to do that and I am not sure if this current behaviour is intentional or bug.

Attached is an image of the Priority column on the left side from my old MO which was upgraded from really old version to current 1.3.11 overtime.

![182](https://cloud.githubusercontent.com/assets/13469628/14117120/0b46781e-f5db-11e5-9d4c-927b1c7b7596.jpg)

**Comment by TanninOne** [comment]
Columns can be drag&dropped
