### ISSUE TITLE
DLC & unofficial patches' installation order changed without consent

### ISSUE THREAD

**Issue by PeggleFrank** [TanninOne/modorganizer#642]
I haven't realized until just now, but some key mods have been moved around in my installation order. Dawnguard, Dragonborn, and Hearthfires, as well as their respective patches (I'm waiting until my next playthrough to swap to USLEEP) have been moved down about halfway through my installation order. The high-resolution DLC hasn't moved, but the unofficial patch was moved above it.

This is extremely concerning. Unless there's something critically wrong in my installation order that's encouraging MO to do this, it shouldn't be messing with the installation order like that.

**Comment by TanninOne** [comment]
Mo doesn't move mods on its own
