### ISSUE TITLE
C++ Exception was thrown?

### ISSUE THREAD

**Issue by Sneaks911** [TanninOne/modorganizer#643]
Just downloaded and installed MO 2.0.2.  When I try to run it, I get an error message saying
![2016-04-05](https://cloud.githubusercontent.com/assets/16995276/14288248/829a8aa0-fb1b-11e5-9695-4f935f5427d1.png)
After the third time trying to open it, I still got the above message, but it did open.

**Comment by TanninOne** [comment]
Please try searching before creating a new issue.
Also: 2.0.4 is the current alpha.
Also: Please don't formulate reports as a question ;)
