### ISSUE TITLE
Another Feature Request/Information

### ISSUE THREAD

**Issue by primem0ver** [TanninOne/modorganizer#645]
Hello Tannin,
This is related to my last feature/information request.

In my experimenting with writing an external tool to select mods given a preset, or merge identity (and because of my general laziness in deselecting mods I am not using... rather I just deselect the esp), I have discovered an undocumented, hard-coded limit in Skyrim.  I honestly don't know if this is a limit of Skyrim itself or if it is a check performed by SKSE but if there are more than 508 esms/esps (500 beyond the official DLCS installed) mapped to the Skyrim\Data folder, Skyrim will not load **ANY** mods.

This presents a potential problem when merging esps (which my utility is designed to facilitate).  My utility is designed to be used with the Plugin Merger utility on Nexus and activate only the mods that one desires to merge so that loading and user management time is drastically reduce.  Now, with this new discovery, I also need a way to get information from MO.  I am assuming the only way to do this is to convert my exe into a plugin.

Is it possible for a plugin to request information for an esp/esm in the load list?  Specifically, what mod it is part of and/or its folder name?  I know that MO has a function to do this since it shows in the info tip when you mouse-over an esp.  Also... is there a way to deactivate the mod using a plugin?  I think I asked that before about external executables but I don't remember asking about plugins themselves.

**Comment by primem0ver** [comment]
One additional question.  Can I remove dummy esps from the data folder?  (i.e.will MO detect the BSA and load it/allow me to check and uncheck it even if there is no esp for it?)

**Comment by TanninOne** [comment]
Yes, a plugin can query the origin of a plugin among other things and enable/disable mods.

And no, I would advice against deleting dummy mods as when you do that, mo won't know that the bsa would be enabled by that plugin. There is a checkbox in settings->workarounds that has mo hide unused esps from the application. MO still sees the plugin, skyrim doesn't. This should fix this 500 plugin limit (which is news to me as well)
