### ISSUE TITLE
LOOT snapshot(s) 296 and later are not working under MOv2 Alpha 4

### ISSUE THREAD

**Issue by pStyl3** [TanninOne/modorganizer#650]
https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0

While snapshot "LOOT v0.8.1-294-g8e44d82 (32 bit).7z" still works under MOv2 Alpha 4 "more or less" (there are some error messages, but eventually you can get it to work), snapshot "LOOT v0.8.1-296-gd7bbff8 (32 bit).7z" and later seem to definitely hang repeatedly on startup at "Parsing, merging and evaluating metadata..." under MOv2 Alpha 4. When brought to @WrinklyNinja 's attention, he replied that there is nothing he can do about it. The problem occurs only in combination with MOv2 (and not with MOv1.3.11).

The change between snapshots 294 and 296 was probably [this one](http://forums.bethsoft.com/topic/1588424-rel-loot-thread-22/page-6#entry25120468).

Since this problem occurs with every version after snapshot 296, it will probably also be a thing with the upcoming official version of LOOT, version 0.9.0. Hence, it would be great if this could be looked at as soon as you have the time to update MOv2, Tannin. Thanks!

**Comment by alexjet85** [comment]
since the new update LOOT v0.8.1-294 don't work anymore on FO4, so no LOOT possible From MO right now :(

**Comment by pStyl3** [comment]
Using MOv2 Beta 1, LOOT will now **work**. To mention is though, that the startup process does take a couple of extra seconds at "Parsing, merging and evaluating metadata..." compared to "vanilla LOOT" .. but as it seems it will no longer hang itself up at that point!

Wonderful. :+1:

**Comment by alexjet85** [comment]
yeah i just saw that this morning (France here) :+1:

**Comment by TanninOne** [comment]
Seems to be solved
