### ISSUE TITLE
Sort left pane by installed/not-installed mods

### ISSUE THREAD

**Issue by shankarramr** [TanninOne/modorganizer#652]
Can we have an ability to sort the left pane my mods installed/not-installed? Maybe something like moving the checkbox to it's own column from the 'Mod Name' column and then letting the new column be sorted by checked/unchecked. Thing to note though, 'Non-MO' mods won't have the checkbox to begin with.

**Comment by GrantSP** [comment]
You are aware of the Filters aren't you?
