### ISSUE TITLE
MO CommandLine Information

### ISSUE THREAD

**Issue by Zagiel80** [TanninOne/modorganizer#659]
Is there a documentation to MO command line? I've noticed it does parse an argument with a subdirectory, tho I'm not sure of its exact purpose.

It would be awesome if I could launch MO from a command line in a way, which would trigger MO internally defined executable right after its start-up. I need to rerun FNIS from a batch. And there's no way to access MO's virtual directory from outside I suppose.

**Comment by GSDFan** [comment]
The only way that will work is to add the .bat file as an executable inside of MO like any other executable.

**Comment by TanninOne** [comment]
You can start an executable immediately. The easiest way to get the command line right is to use the "create shortcut" button inside mo (i.e. desktop shortcut) and then check out the link that was created.
You can also specify the profile to be used: "ModOrganizer.exe -p my_profile". There is another one used internally to start a download from nexus in another instance of MO.

**Comment by Zagiel80** [comment]
That's amazing. Exactly what I needed. You thought of everything :) Thanks.
