### ISSUE TITLE
Status on FO4 with version 1.5 beta

### ISSUE THREAD

**Issue by wmcook32** [TanninOne/modorganizer#660]
I'm just curious about the status of MO2 now that 1.5 has been placed in beta. Not just the survival mode the entire update. With this update comes a new way for FO4 to load mods. Also how is the saving going? ie local saves being placed in the correct location and not FO4 default.

**Comment by bizzclaw** [comment]
I hate using Nexus Mod Manager. Hopefully it won't be much longer, but we just have to stay patient.

**Comment by TanninOne** [comment]
Unfortunately, reallife in april has been very busy and stressful for me so i didn't get a lot done. Mai should be a lot better. Profile local save games and several other problems should already be fixed and ready for testing. The new plugin.txt format in fo4 is what I'll get to next.

**Comment by TanninOne** [comment]
Please use issue #663 to track this.
