### ISSUE TITLE
Fallout 4 in-game mod manager disable mods in mod organizer.

### ISSUE THREAD

**Issue by Sarg3ntRecker** [TanninOne/modorganizer#662]
With mods now in open beta. The load-order in-game and the load-order in mod organizer aren't the same. Only one can be enable. In-game I have to enable the mods in the in-game load order but it disables the load order for mod organizer. When I re-enable the load order in mod organizer it disables the in-game load order. Either way I can't access any mods I download with mod organizer in-game.

**Comment by GSDFan** [comment]
See issue [660](https://github.com/TanninOne/modorganizer/issues/660) .Tannin will be working on the plugin.txt issue next.
