### ISSUE TITLE
Lookup Failed

### ISSUE THREAD

**Issue by NomenNescio92** [TanninOne/modorganizer#664]
So since the new update I'm getting Lookup Failed in the game with no particular regularity or patterns emerging. It pops up on loading screens, active effects, notifications you name it. I've tried just about everything and the only thing that seems to work is to launch the game without using MO. If you need any information from me, by all means, I'm not sure exactly what would be relevant.

**Comment by Schizosaccaromyces** [comment]
That's probably a bug with any of the dialogue interface mods. The new update requires those to be updated as well. It happened to me with Full Dialogue Interface, and running the game without MO fixes it as the mod is not running anymore.

**Comment by NomenNescio92** [comment]
Oh you're right, Dialogue Interface was updated today and that fixed the issue.
