### ISSUE TITLE
It seems mo does not detect f4se plugins.

### ISSUE THREAD

**Issue by lswfhd** [TanninOne/modorganizer#668]
And 1.5 killed MO mod activations.

**Comment by EmberQuill** [comment]
MO doesn't see the F4SE folder as a valid mod data folder, so it thinks there's nothing in the mod folder. F4SE plugins should still work without issues, even though MO doesn't see them. As for activating plugins in MO, the 1.5 update made a slight change to how mods are activated, but there are a couple of workarounds for that in the comments on #663.

**Comment by TanninOne** [comment]
This has been fixed in the meantime
