### ISSUE TITLE
Beta 1 - missing LIBEAY32.DLL and SSLEAY32.DLL error

### ISSUE THREAD

**Issue by pralima87** [TanninOne/modorganizer#678]
Just a small report on the Beta 1.
The app won't start showing a error of missing files:
LIBEAY32.DLL and SSLEAY32.DLL.

**Comment by manguz** [comment]
+ 1

**Comment by chazwarp923** [comment]
copy the contents of https://github.com/TanninOne/modorganizer/files/255758/openssl.zip into your mod organizer folder and rename the "libssl.dll" to "ssleay.dll"

**Comment by azchar111** [comment]
In my install, both files were found in the created DLLs folder but the program couldn't see them - after copying them to the base folder, program worked as expected.

**Comment by Toriko69** [comment]
I followed the above instructions and am now getting the ERROR "Failed to create Default"

**Comment by Toriko69** [comment]
Never mind deleted the folder in appdata and it worked

**Comment by TanninOne** [comment]
This has been discussed in #663
