### ISSUE TITLE
Does not start. Says missing SSLEAY32.dll

### ISSUE THREAD

**Issue by rogerdatsir** [TanninOne/modorganizer#687]
I see that I can download this dll from shady looking sites. But, I think it would be preferable for MO to supply it or point to a legit dependency if it needs it.

**Comment by MuhBalls** [comment]
That DLL can be found in the Qt5.5.7.z file. Extract it into your MO directory. It also gave me the same error but for the libleay32.dll after words. That is also in the same archive.

**Comment by GSDFan** [comment]
That was addressed [here](https://github.com/TanninOne/modorganizer/issues/663#issuecomment-217967830)

**Comment by TanninOne** [comment]
should be fixed in the current beta
