### ISSUE TITLE
Mods that have meshes seem to crash game on start up

### ISSUE THREAD

**Issue by ErraticFox** [TanninOne/modorganizer#696]
I've noticed that a couple of armor mods, one being Wasteland Sniper by Hoth, crashes FO4/F4SE on startup using MO Beta 1. Can anybody confirm?

**Comment by rdunlap** [comment]
I have several mods with meshes and have no crashes in game. I will go get that one and try it. It may have some other or related issue that is raised by MO2.

Robert

**Comment by ErraticFox** [comment]
I disabled all my mods to find out which one does crash it. When I only have that armor mod selected, it crashes.

**Comment by kstarler** [comment]
Have you tried loading a save where the mod is not currently active? I ask because I've had similar experiences after updating mods, but disabling the mod and saving the game with the mod disabled allowed the new save to be loaded with the mod active afterwards.

**Comment by ErraticFox** [comment]
The problem is, it crashes the game at start up.

**Comment by kstarler** [comment]
I misunderstood the issue. i don't believe this is the mod, as I am able to load the game and load a save with the most recent version of Wasteland Sniper installed and enabled. I seem to recall having a similar problem though because I had a dummy Meshes folder in the base game\Data folder. Do you have any errant files there?

**Comment by GSDFan** [comment]
> I had a dummy Meshes folder in the base game\Data folder.

I had the same thing happen to me. The folder was empty and when I deleted it the game loaded.

**Comment by ErraticFox** [comment]
I'll reinstall FO4 when I get home, because I had to use nmm (eww I know) because of similar problems in earlier versions of  MO for FO4
