### ISSUE TITLE
usvfs logging trashing hdd space of useless info

### ISSUE THREAD

**Issue by TwistedByte** [TanninOne/modorganizer#698]
usvfs logging is trashing hdd space and cannot be disabled even on set error logging

endless entries like :
04:39:04.555 <1528:4300> [W] GetFileAttributesExA called
04:39:04.555 <1528:4300> [W] GetFileAttributesExA called
04:39:04.555 <1528:4300> [W] GetFileAttributesExA called
04:39:04.578 <1528:4300> [W] GetFileAttributesExA called
04:39:04.578 <1528:4300> [W] GetFileAttributesExA called
04:39:04.678 <1528:4300> [W] GetFileAttributesExA called
04:39:05.263 <1528:5908> [W] GetFileAttributesExA called
                                              .
                                              .
                                              .
                                              and so on

**Comment by TanninOne** [comment]
If you set logging to error and restart mo (!) this should not happen anymore. Out of curiosity: how large does the log file get?

**Comment by TwistedByte** [comment]
even with logging set to error usvfs is created. every time i start mo a new instance time-stamped
of usvfs is created usually the losh is small but if i do not close mo and start multiple times game 
experimenting with different mods and ini setting log can get 1GB+ in size (that i mean on heavy modding and trials) and that 1GB file is not erased or overwrite. On new startup of mo an new log 
is created with different time stamp an 1GB prev log remain on hdd.
  it will be nice if we can disable log for usvfs or at least overwrite itself by deleting previous file

**Comment by TanninOne** [comment]
It should only keep the 5 most recent logs around.

**Comment by Maxunit** [comment]
No issue here with the logs. So far, there are only 6 usvfs logs and 1 mo_interface log. (Re-)Starting MO2 won't create a new log, but overwrite the oldest.

**Comment by TwistedByte** [comment]
i checked indeed no more than 6 logs but my problem is with size they get sometimes too big
