### ISSUE TITLE
Plugins Restore Backup not working

### ISSUE THREAD

**Issue by kstarler** [TanninOne/modorganizer#699]
I have generated several backups of my profile specific Plugin load order, but I am unable to restore from any plugin backup inside MO 2.0.5.

Additionally, when I switch profiles, the load order and selected plugins are completely overwritten by the newly selected profile when switching back to the originally selected profile.

~~Also, possibly related, LOOT fails to run through MO every other time I run it. It shows up in the task manager, but MO immediately unlocks after it runs, and it never shows any sign of loading. Killing the process in Task Manager allows it to load and run normally on the second attempt.~~ This was caused by an old version of LOOT, and is not related to the primary issue.

Using Windows 7 Home Premium 64-bit and the latest version of FO4 and F4SE, and running MO as Admin.

Workaround: I keep manual backups which, when copied over the MO generated files fixes the issue.

**Comment by michaelrw10** [comment]
What I have found is this: If youre trying to use a backup that was made with a previous MO2 release, it will not work at all. You have to open the backup file manually, add an asterisk to the beginning of each plugin name in the list, then save it.
If you are trying to restore a load order that was made with the current version of MO2 (v2.0.5), or if you're restoring a backup that you manually edited as described above, you have to close MO2 after you do the restore and then reopen, and the load order should then be applied. Simply restoring and refreshing the mods window is not sufficient. You must re-launch the program.
YMMV, these are my own experiences, thus far

**Comment by kstarler** [comment]
Works correctly in 2.0.6
