### ISSUE TITLE
Crash when disabling a mod with multiple .esp files

### ISSUE THREAD

**Issue by neokio** [TanninOne/modorganizer#702]
v2.0.5b

I can reliably cause the crash with these steps:

1. I installed "Mr. Handy Make-A-Bot Reinvented" (nexus id 13044).
2. The FOMOD installer has an optional patch, which I install (so 2 .esp files are installed).
3. I enable the mod, then disable the mod, and crash.

**EDIT: Sometimes it takes 2-3 toggles to crash.**

The FOMOD installs two files:
- Mr. Handy Make-A-Bot Reinvented.esp
- Mr. Handy Make-A-Bot Reinvented BMD.esp

If I install ONLY ONE .esp file in the FOMOD, disabling the mod does NOT crash.

... BUT ...

If I rename both .esp files from "Mr. Handy ..." to "Mr Handy ..." (removing the period), it does NOT crash with both .esps installed. In other words, it's possible that when there are more than 1 .esp files, IF they have a "." in the filename, it will crash. **EDIT: It still crashes without the period, just less often**

**Comment by neokio** [comment]
I've enabled and disabled a bunch of mods, recording crashes as they happened.
Here are some more mods that install multiple .esp files, which (probably?) is what causes them to crash when toggled (sometimes it takes 2-3 toggles to crash):

**Commonwealth Shorts**
http://www.nexusmods.com/fallout4/mods/7898/?
![mo_commonwealth_shorts](https://cloud.githubusercontent.com/assets/146623/15220569/44acd8e6-1868-11e6-8b92-2bb1c400966f.png)

**Mr. Handy Make-a-Bot Reinvented**
http://www.nexusmods.com/fallout4/mods/13044/?
![mo_mrhandy](https://cloud.githubusercontent.com/assets/146623/15220633/741bf1fc-1868-11e6-9825-0d115a4e8230.png)

**Arbitration**
http://www.nexusmods.com/fallout4/mods/2037/?
![mo_arbitration](https://cloud.githubusercontent.com/assets/146623/15220650/7efe8d6e-1868-11e6-80fc-5cbccc80d7d8.png)

**Comment by neokio** [comment]
I noticed that after the crashes, several totally unrelated plugins had been disabled.
For example, when toggling Commonwealth Shorts 3 times to cause a crash, I relaunched MO, and found that the unrelated DYNAVISION.esp ([link](http://www.nexusmods.com/fallout4/mods/12411/?)) had been disabled (and added to the end of my load order).

**Comment by SonicBog** [comment]
I found that if you manually uncheck the plugins for the mod before unchecking the mod, it does not crash.

**Comment by TanninOne** [comment]
Fixed in beta 2
