### ISSUE TITLE
[MO 2.0.5 beta 1] Skyrimprefs.ini

### ISSUE THREAD

**Issue by wmcook32** [TanninOne/modorganizer#706]
This sort of thing was mention in #681 but for Fallout. The ini's are not for me at least being read from the Profiles folder but from the Games default MyDoc folder. I changed the mo ini to show a different location for where I wanted the profiles and such to be. That didn't  fix the issue either. I haven't yet tried loading mods yet as I want to get the settings in MO to take effect first.

**Comment by TanninOne** [comment]
Duplicate of #681
