### ISSUE TITLE
CTD on new game (MO2 b1)

### ISSUE THREAD

**Issue by Fed13** [TanninOne/modorganizer#714]
It started after update 1.5.157 (that was the last fallout4 update, right?) - with alpha4.
It still crashes now, with beta1 (installed over alpha4 if that matters).

Here's what I tried and the results I got:
**alpha4:**
MO + f4se (the last one I could get, of course) + 60 (or so) mods + savegame (from before latest fallout4 update, with all the mods, run through MO) = ctd
MO + f4se + all mods disabled (in the left panel of MO) + savegame = ctd
f4se + savegame = loads fine

**beta1:**
MO + f4se + 60 (minus a couple) mods + new game  = ctd
MO + f4se + all mods unticked (in the right MO panel since for some reasin MO hangs when I try to disable all mods in the left panel) + new game  = ctd
f4se + new game = starts fine

P.S. It's my first trying to report a problem on github, so be gentle. :D
Also I have to say switchng to mod organizer was one of the best mod-related things that happened to me - it worked magic with skyrim.

P.P.S. I have no dlcs in case it matters.

**Comment by TanninOne** [comment]
Please provide the usvfs.log from directly after the crash

**Comment by Fed13** [comment]
[crash log.txt](https://github.com/TanninOne/modorganizer/files/264941/crash.log.txt)
I tried to make a smaller log, with no mods enabled in the left panel but but after doing it I got MO just crashing all the time (I'll make a new ticket on that).
So this log is the only one I could miraculosly save.

**Comment by Fed13** [comment]
Well, it seems I found the mod that is guilty of that crash.
It's not an .esp mod, it's interface.
Terribly sorry. I did try loading a game with properly disabling mods - not just unticking .esp/.esm - while I was using MO2a4, and it did crash.
So I guess the crash I had was fixed in MO2b1 and I had a new one because of a mod. And I got them mixed up.
So I'm closing this ticket.
