### ISSUE TITLE
Cannot run 2 instances of MO2 (NOT simultaneously)

### ISSUE THREAD

**Issue by Fed13** [TanninOne/modorganizer#715]
I have MO2 installed twice - in different directories.
At first I used it to play Fallout4. But since I have a predicament with Fallout4, I decided to try MO2 with Fallout NV.
I remember MO 1.x worked this way - you install it in different directories and set it up for different games.

But now when I run MO2 executable in the second directory it still runs as if I ran it in the first one - it shows me the mods I installed for FO4 and it is set up to work with FO4.

**Comment by TanninOne** [comment]
When you install mo2 into a directory you have write access to, you get the choice to do a "regular" install or "portable". Portable is like in mo1 where each installation is separate, regular puts all data into a common location and you can create different "instances" through the settings dialog.
