### ISSUE TITLE
Remove enabled Mod (multiply esp) causes crash

### ISSUE THREAD

**Issue by disi** [TanninOne/modorganizer#716]
If I right click and choose "Remove Mod" on Super Helpful Item Tidying, while it is active, I can reproduce a crash every time.
[ModOrganizer.exe.zip](https://github.com/TanninOne/modorganizer/files/264643/ModOrganizer.exe.zip)

If I first disable it, no problem.

**Comment by TanninOne** [comment]
This has the same cause as #684
