### ISSUE TITLE
[Beta 2.0.5] Cannot Launch any version of Loot

### ISSUE THREAD

**Issue by Leer0x** [TanninOne/modorganizer#720]
When I try to launch LOOT: failed to spawn "LOOT.exe": failed to start process (The parameter is incorrect. [87]). 
Whether from Mod Organizer's integrated Loot, or any other version of Loot, problems are the same with same error messages.

After reinstalling and deleting all Mod Organizer residue, problems still persist.
Restarting PC has no effect.
Turning off Anti-Virus has no effect. 
Running as admin has no effect.

**Comment by calintay** [comment]
Ive been having the very same problem. Loot says parameter is incorrect, 87. MO [Beta 2.0.5 also crashes when the sort button is clicked.

**Comment by TanninOne** [comment]
please double check the parameters you set in the "edit executables" dialog. This error message says that either binary path, arguments or current working directory for LOOT.exe have been set incorrectly. Maybe someone can help if you attach a screenshot.

**Comment by RPINerd** [comment]
Sorry about the cluster created in the last thread Tannin!

So I still have yet to have the physical "Sort" button work, instead I found instructions on how to properly install the standalone LOOT application and run it through MO much like you would F4SE or the Fallout4.exe itself.

wiki.step-project.com/Guide:Mod_Organizer  (Just do a ctrl+F for LOOT)

After following this simple setup I can run LOOT as it's own application just fine and everything is wonderful. Leer0x and calintay, is this the way you currently have it installed as well?

**Comment by Leer0x** [comment]
All I did was add the executable in the "Modify Executables" menu.
I simply added it by clicking the ellipsis (...) across binary to add Loot.exe, for v0.8.1-823 of loot.
I titled it "LOOT", successfully added it. 
When I tried to run loot it did not work, giving me the errorcode.
HOWEVER, when I added --game=Fallout4 in the arguments box, it actually started and works fine, I believe. Now this is a fix, however, a new user will still ahve to add --game=Fallout4 in the arguments.
No matter what I do now I can get Loot to run, but the problem may be that Mod Organizer is not 100% naturally compatible with Loot. I figured this out my deleting all my Mod Organizer, Loot, and modding residue (All files related), re-downloading everything in pristine condition, adding loot, and then it gives me the errorcode
Thanks for the help @TanninOne and @RPINerd if I hadn't changed my arguments I wouldn't have fixed it.

**Comment by MysticDaedra** [comment]
I've tried this, doesn't work at all for me. Running LOOT through the executables doesn't throw any errors, it just doesn't do anything. Sort throws Exit code 1.

**Comment by calintay** [comment]
Thanx for the quick reply, got it to finally open up in mod organizer.  The only problem is when ever loot opens in mod organizer it starts loading then it crashes saying loot has stopped working.  Im able to get this far by turning off my AVG when doing these functions,yet this is the latest obstacle.

**Comment by Leer0x** [comment]
@calintay Haven't ever crashed loot like that. I think a PC restart...or simply waiting for an update will help..

**Comment by calintay** [comment]
Agreed, one more thing, now when I click sort I get the message loot failed exit code was 1. A little more progress any possible work around for this issue. Thanx

**Comment by ChristopherC71** [comment]
New version of Loot 9.0 came out today and I am able to get that to work standalone launch from MO2. I still get the same error from the internal MO2 Loot button.

**Comment by Leer0x** [comment]
I recommend using Loot 0.9.0.

**Comment by ChristopherC71** [comment]
Sorry, yes it was 0.9.0 I installed.

**Comment by Leer0x** [comment]
@ChristopherC71 Yes I know I was saying I recommend it to anyone trying to use LOOT hahah

**Comment by sbroadbent** [comment]
I'm getting a similar issue except with f4se (v0.1.13).  I last played FO4 a day or two ago, and nothing should have changed.

"failed to spawn "ModOrganizer 205": failed to start process (Access is denied. [5])."

I can load up the game without f4se by using the default executable.  I can also load and sort with Loot, but what could be going on here?

I've set the f4se loader (in the FO4 directly, as well as Mod Organizer) as Run as Administrator, but I don't think that would have made much of a difference since my games are installed outside the typical protected directories (ie C:\games\steam\... etc)

**Comment by drumanagh** [comment]
Running on Windows 10, I get an alert with "usvfs_proxy.exe has stopped working", followed by the "The parameter is incorrect. [87]" alert from LOOT. This is with ModOrganizer in `C:\Program Files\ModOrganizer` and LOOT in `C:\Program Files (x86)\LOOT`.

**Comment by dt78** [comment]
Usvfs_proxy seems to be unable to work on Win 10 when launching any 32bit programs through MO2b/a. For example, the current version of Bodyslide has two executables you can choose from. If you launch the 32 bit version, you'll get "usvfs_proxy.exe has stopped working". If you run the 64bit exe, it seems to work without crashing. 

As far as I know there is no 64bit version of Loot we can test with yet.

**Comment by MysticDaedra** [comment]
Something must have changed either in LOOT or in MO2 since Alpha 4 because LOOT used to work fine for me back then.

**Comment by dt78** [comment]
"usvfs_proxy.exe has stopped working" Seems to be fixed now in MO2 Beta2. However when running Loot (Version 0.9.0 (build 44a0d85)), only the core and DLC .esm plugins appear in the list. It doesn't seem to see the virtual data folder. 

Win10 Pro x64
MO2 b2
Loot (Version 0.9.0 (build 44a0d85))
UVSF logs are empty.

**Comment by dt78** [comment]
Update:

GTSlayer's comment in [this thread](https://github.com/TanninOne/modorganizer/issues/803#issuecomment-225652918) got Loot finally launching and working for me through MO v2.0.6.

**Comment by sr383** [comment]
It seems to work fine, for me, if I stick with Tannin's suggested paths (..]AppData\Local\ModOrganizer\). I moved my downloads folder off the SSD, but I left the rest alone.

**Comment by Leer0x** [comment]
Version 0.10.3 of LOOT and Mod Organizer 2.0.8.2b are compatible, thread closing.
