### ISSUE TITLE
2.0.5 Beta 1: Local Saves and INIs don't work

### ISSUE THREAD

**Issue by uhh186** [TanninOne/modorganizer#722]
Having 'Local Save Games' and 'Local Game Settings' checked for profiles does not work. The game will still load whatever INIs and saves are in the Documents directory, instead of inside the profile's directory.

**Comment by uhh186** [comment]
Things I've tried:
1) making new profiles
2) renaming profiles
3) toggling the settings for the respective profile

The INI editor will edit the correct INIs for each profile. There are save games present in the profile's save directory. A few months ago with 2.0.4 alpha 4, when I tried playing last, using local files worked fine.

**Comment by TanninOne** [comment]
please start the game, go to the load-dialog, then quit and send me the newest usvs_<date>.log

**Comment by uhh186** [comment]
[usvfs-2016-05-16_15-10-54.zip](https://github.com/TanninOne/modorganizer/files/266367/usvfs-2016-05-16_15-10-54.zip)
Here. It's inside the ZIP file.

**Comment by wmcook32** [comment]
This is the same issue I'm having but my issue was closed since it was to them a duplicate. But not much help was given.

**Comment by TanninOne** [comment]
This is indeed the same as #681 . I wanted to make sure because that issue doesn't mention save games.

@wmcook32 a) I'm one person, not "them". and b) this is not a help forum, it's an issue tracker. The purpose here is for users to help the developer(s) fix bugs **not** for users to get help.
