### ISSUE TITLE
Mod Organizer 1.3.11 ".Exe Bug" 

### ISSUE THREAD

**Issue by xenbirth** [TanninOne/modorganizer#723]
I have no idea Why, but i'm getting the "non-touchable .exe bug" I cannot modify or add any executables, through the ini or the drop down menus.

**Comment by TanninOne** [comment]
permission problem.

**Comment by xenbirth** [comment]
Could you explain more?? I have no idea how to fix it still.

**Comment by TanninOne** [comment]
The information you provide is extremely slim, you don't say what you mean by "non-touchable .exe bug" or how modifying/add fails (do you get an error message?) but the only problem I know why this would fail is the account you run MO with has no permissions to change the ModOrganizer.ini. If you need further help, please visit the step forum, this is **not** a support channel.
