### ISSUE TITLE
[Beta 2.0.5] Failed to request file info from nexus: empty response

### ISSUE THREAD

**Issue by NexusAU** [TanninOne/modorganizer#731]
I'm getting "Failed to request file info from nexus: empty response" while trying to download. 
I tried changing the NMM Version number to the latest in the workarounds section of MO but that didn't seem to fix it.
Any way to fix this or do we have to wait until the next MO update?

**Comment by Akzyra** [comment]
Only on some mods? It takes some time for new files to be downloadable, the name of the file is white during that time until you can download (normally blue/game colour for the site). But sometimes nexus bugs out and it is still impossible after hours.

**Comment by NexusAU** [comment]
Ah that makes sense. I'm pretty sure they were just updated as it's working
fine now. This can be closed
On 20 May 2016 12:06 pm, "Akzyra" <notifications@github.com> wrote:

Only on some mods? It takes some time for new files to be downloadable, the
name of the file is white during that time until you can download (normally
blue/game colour for the site). But sometimes nexus bugs out and it is
still impossible after hours.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/TanninOne/modorganizer/issues/731#issuecomment-220499868>

**Comment by TanninOne** [comment]
There may also be problems querying info om mods that have more than 30 files. This is a limitation of the nexus protocol and can't be fixed on my end afaik.
