### ISSUE TITLE
[Beta 2.0.5] Uninstalling deletes all mods even when "X"ing out the message box

### ISSUE THREAD

**Issue by AlexxEG** [TanninOne/modorganizer#735]
When uninstalling the installer ask if you want to delete all files (including installed mods etc...) and only gives you the OK option. Naturally I assumed pressing the X top left would decline this, instead it proceeded to uninstall all my mods while all I could do was watch.

This was for Fallout 3 GOTY, Windows 10. Directories was changed from %localappdata% to the ModOrganizer installed path inside the Fallout 3 folder:

> D:\Steam\...\Fallout 3 GOTY\ModOrganizer\mods/overwrite/profiles/etc...

**Comment by michaelrw10** [comment]
yeah same thing happened to me.. it gave me the warning about removing the user settings but it also indicated that certain things would NOT be deleted.. every one of my mods, many of which are my own custom plugins with months of work on them (yes, i shouldve had a backup but hadnt done it yet).. all of them deleted without any chance of recovering them.. just sat and watched in horror

**Comment by gerbilOFdoom** [comment]
@michaelrw10 you should try using a recovery program. The files were not scrubbed from your system and as long as you haven't done too much a file recovery program should be able to locate the files and undelete them.

**Comment by Geotan00** [comment]
Sme happened to me... file recovery did not work. I lost more than 100 mods.

**Comment by TanninOne** [comment]
Fixed in v2.0.6
