### ISSUE TITLE
[MO2 v2.0.5b] [FO4Edit] edited plugin files are being renamed with all lowercase characters

### ISSUE THREAD

**Issue by michaelrw10** [TanninOne/modorganizer#736]
**Running FO4Edit via MO**: 
load up your plugin (ThisIsForTesting.esp) into FO4Edit, make your changes, save the plugin and exit FO4Edit. Your plugin, ThisIsForTesting.esp, will now be titled thisisfortesting.esp

**Running FO4Edit normally, outside of MO**:
Repeat the above steps, but plugin will retain the correct name and character case.

**Comment by rdunlap** [comment]
This is fixed for me in Beta 3

Robert
