### ISSUE TITLE
Enhancement: Easy change from Regular to Portable

### ISSUE THREAD

**Issue by Akzyra** [TanninOne/modorganizer#737]
The Regular mode is confusing for people who are used to MO1. And probably new users as well.
And if you choose it, there is no fast and easy way back.

Either reinstall (and download everything you already have) or fiddle with files and registry.
Both require manual moving of files from appdata into the Mo2 installation.

Maybe a system that can move one "supported game instance" to a MO2 installation folder?

**Comment by Geotan00** [comment]
I tried reinstalling stuff multiple times and could not change it to portable... very difficult. There is also no easy way to change games for Regular.

**Comment by Akzyra** [comment]
Yeah, found out Reinstall won't always work.
**Regular -> Portable:**
 1. (Re-) Move all files inside %appdata%\ModOrganizer (All instances, can me moved into MO2 for Portable Mode) If you have ANY folder inside this, it will not work.
 2. Set this Value in the Registry to nothing: HKEY_CURRENT_USER\SOFTWARE\Tannin\Mod Organizer\CurrentInstance

Other way around just delete/rename the ModOrganizer.ini.

To change Games: Settings -> Change Instance (First panel at the bottom)

**Comment by Geotan00** [comment]
Yeah I know how to change games, it's just very not obvious especially if you will be able to have 1 installation for all of your games.

**Comment by TanninOne** [comment]
Done in v2.0.6
