### ISSUE TITLE
[MO2 v2.0.5b] Cannot change path directory

### ISSUE THREAD

**Issue by xNine** [TanninOne/modorganizer#738]
I created an identical path by copying and pasting the original created directory to my other drive (SSD was default so I want to migrate the mod directory to my HDD). After this I went to the settings and tried to select the new path; typing and manually entering the address do not work. As I select the new address, the log at the bottom just says the mod directory was changed to the default directory. No change.

**Comment by disi** [comment]
This only happens for the Base Directory variable in my installation. I am able to set the others (mods, profiles etc.) manually to a full UNC path and they are not reset.

p.s. wow, I have Skyrim and Fallout4 installed. Now it even asked to handle multiply games, LOOT runs out of the box asking which game. You are great people!

**Comment by alexjet85** [comment]
you can just add : base_directory="your custom path" to modorganizer.ini under [settings].

**Comment by iSupersniper** [comment]
https://github.com/TanninOne/modorganizer/issues/686

**Comment by xNine** [comment]
Oh wow looks like this well covered. Thank you gentlemen.
