### ISSUE TITLE
MO won't login to Nexus

### ISSUE THREAD

**Issue by Mekahs** [TanninOne/modorganizer#739]
I had roughly 150 mods and AVG said there was a problem w/ MO so I went ahead and let it do its thing, when I tried to re-open it it was completely deleted. Anyway, I went ahead and started to get all my mods back after re-downloading MO and it kept opening NMM to download it, but I'd correctly put in my nexus login, set it up to handle the "download with manager" links, but it still wouldn't log me in, or download any of the mods.

**Comment by GSDFan** [comment]
This is not a bug, you should be looking in the support forum and asking there.
[MO support ](http://forum.step-project.com/forum/62-mod-organizer-support/)
