### ISSUE TITLE
MO 2 does not use any profile specific files

### ISSUE THREAD

**Issue by IIIuminator** [TanninOne/modorganizer#740]
As the title says, Mod Organizer 2 does not use any kind of profile specific files. I tried the local savegame feature (brilliant idea btw) and FO 4 didn't list them.
Same with ini's. I changes the resolution in the localized and the general ini's and it always used the standard files.

**Comment by GSDFan** [comment]
This has been mentioned in issue [681](https://github.com/TanninOne/modorganizer/issues/681)

**Comment by TanninOne** [comment]
duplicate of #681
