### ISSUE TITLE
[2.0.5] ba2 archive mods installation without esp

### ISSUE THREAD

**Issue by disi** [TanninOne/modorganizer#744]
Will Mod Organizer handle those?

I tested the [Texture Optimization Project BA2 Edition](http://www.nexusmods.com/fallout4/mods/13889/?), that comes in one single ba2 archive. I manually set the data folder so the ba2 would be in the Data directory, but MO still complained and said it most likely fails (no Looks Good).

Will it work if I just put the ba2 into the Data folder and the guide is false positive saying it is not good?
Or does it not load and the guide is correct?

The mod installation implements adding the archive to the Fallout4.ini option. Will Mod Organizer handle it and I do not need to add it?

p.s. OK, the mod went offline, but the question remains ;)

**Comment by kevlar646** [comment]
Right-click on the mod. and select 'Ignore missing data'.  Or go into the mod in windows explorer and add an empty 'textures' folder, which is what 'Ignore missing data' seems to do anyway.  

I had this problem with the 'NewDialog' mod, which has an alternate installer with a single .ba2 archive.

**Comment by TanninOne** [comment]
Fixed in 2.0.7

**Comment by Justioc** [comment]
I'm using 2.0.7, how would I load a ba2 without a plugin? I'm just adding it in the ini now.
