### ISSUE TITLE
[Solved] MO freezing when launching programs

### ISSUE THREAD

**Issue by Palpou** [TanninOne/modorganizer#746]
Hi there !

I have an issue with MO.
MO is installed in my Fallout 4 folder located here: H:\Program Files (x86)\Steam\SteamApps\common\Fallout 4
But the path of the directories were on C:\[...]

The problem is that I downloaded too many mods today (armor and clothes - nearly 155 .ESPs).
I didn't install them because I found that FO4edit could not handle merging of mods like in Skyrim. Furthermore, C:\ was full. So I had to move the folders to H:\. I reinstalled MO too (just in case I missed a part where it asked me where I want to put the files).
I cut-paste the directories, and change the path that I found actually in the settings (MO could not locate the profile without that). Then I launched the game, but I had a CTD after the loading screen. Trying a new game, I had an infinite loading.
Then I realized I didn't launch Bodyslide since my reinstallation, so I did that, but I found out that Bodyslide didn't launch, Mod organizer was freezed.
Trying to reinstall Bodyslide, didn't work either.
Then I realized I didn't launch Fallout 4 launcher. Didn't work either, Mod Organizer freezed.
The same for Loot : http://img11.hostingpics.net/pics/612641Capturedcran20160525194353.png (the famous freeze), which actually worked earlier (after the crash ingame, but before MO freezing).

Then I checked the directories to find out that MO put the main directory back on C:\, but I was able to fix that thanks to your explanations ( https://github.com/TanninOne/modorganizer/issues/738 ). Didn't work, still freezing.

Then I unchecked all mods, didn't work either.
I'm going to re-install MO, but I'm going to save MO (mods, download..) just in case. Because MO seems to ask a question but I can only select "ok".. ! http://img11.hostingpics.net/pics/502939Capturedcran20160525201026.png

If it doesn't work either, and if no one has a solution (but I hope you have \o/), I'm going to re-put back the folders on C:\, but it's pretty annoying.

Sorry for the long report, "I'm giving up my tongue to the cat" ;)

**Comment by Palpou** [comment]
Wait, I think I found !
I'm just looking and I come back to explain.

**Comment by Palpou** [comment]
I was uninstalling Mod Organizer, and I had the window with the "question": http://img11.hostingpics.net/pics/502939Capturedcran20160525201026.png .
Before answering "ok", I was saving my Mod Organizer folder (+/- 35 min), but I realized I didn't launch the game without MO... !!!

So I launched the game, and the game launched.
So I ctrl+alt+delete the uninstallation of MO, and re-install it. But there was a file, "usvfs_x64" that was already here and it could not replace (with an error message). I just ignored it.
Then I launched the game and.. Re-freeze....
So I decided to delete the file "usvfs_x64" to install it properly. And then an error message prompted, saying me that LOOT was already using the file OOOOOoooooooo !!!!!!

Ctrl + alt + del, and yes, LOOT was right there. Quiet, calme, peaceful, secure.
So I killed LOOT, and now everything works. No more freeze.
I'm ending to put everything properly, I'll try and I'll edit my post if that's ok.

**Comment by Palpou** [comment]
Another bug I ran into:
I launched Bodyslide x64 and it didn't run. I launched Bodyslide x32 and it told me that " BodySlide.xrc " was missing. I reinstalled Bodyslide, I installed the previous version, I tried to install it manually, I tried to launch the game through MO and without MO : nothing worked.

I just had to restart the computer. Now it works fine.
Load a game, works fine too.

**Comment by TanninOne** [comment]
you can close solved issues.
