### ISSUE TITLE
[Solved] Bodyslide not launching (x64) or BodySlide.xrc missing (x32)

### ISSUE THREAD

**Issue by Palpou** [TanninOne/modorganizer#747]
On a fresh reinstallation of Mod Organizer conserving all my mods, the time to change my directories from C:\ to H:\ (cf. my other issue: https://github.com/TanninOne/modorganizer/issues/746 )
I launched Bodyslide x64 and it didn't run. I launched Bodyslide x32 and it told me that " BodySlide.xrc " was missing. I reinstalled Bodyslide, I installed the previous version, I tried to install it manually, I tried to launch the game through MO and without MO : nothing worked.

**I just had to restart the computer**. Now it works fine.

_PS: Just to remind: By default, Bodyslide crashes a lot with MO.
We have to launch Bodyslide, then go to "Settings", and change Game Data Path from the default game to the virtual created by Fallout 4 (default: C:\Users\[...]\AppData\Local\ModOrganizer\Fallout 4\mods\BodySlide and Outfit Studio )._
===> In fact no (drives me crazy). We have to put the path in the right Data folder of the game (as by default). The virtual folder appears completely when running Bodyslide through MO... Otherwise (= like I said), there are "No images" on the body.
======> In fact, we have to use the Steam root in Settings, but MO root to save presets or batch files, otherwise it crashes.

**Comment by TanninOne** [comment]
If an issue is solved you can close it.
