### ISSUE TITLE
Enhancement suggestion for "Potential Mod order problem"

### ISSUE THREAD

**Issue by MichaelMondy** [TanninOne/modorganizer#750]
I haven't looked at the code, but while using MO 1.3.11, it appears that MO looks for the existence of scripts and does not take into account that the scripts might actually be identical.   This can result in false positives.

Obvious work-around is for the user to hide the lower priority conflicting-but-identical file.

**Comment by TanninOne** [comment]
It's unfortunately not that easy as the script may be inside a bsa and then comparing the files would involve extracting the bsa which would probably be too expensive. Also, in MO2 the PMOP check is no longer necessary anyway.
