### ISSUE TITLE
MO2B2 Strange characters and unexpected folders in overwrite when saving in xEdit

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#753]
When saving a plugin file in xEdit it creates a backup of the esp before changes at the same time it saves the changes. There is no error thrown by xEdit or by ModOrganizer B2 but opening the overwrite folder reveals the following.
1. the saved esp is proper and can be opened and used properly so no corruption is happening.
2. there are 2 folders created with several heiroglyphic symbols and then the remainder of the plugin name is proper *(US English) There should not be 2 folders created. There should be 1 file created in Data/fo4edit backups/espfilename.esp.backup.NumericalTimeStamp.

Lastly if you try to run an executable again whether it is xEdit or another will cause MO2B2 to throw an error. If you close then reopen MO2B2 before running another executable no error is thrown.

 Included is both the dump and a screen shot of the overwrite popup to show the unexpected file creations

Robert

[ModOrganizer.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/286968/ModOrganizer.exe.dmp.zip)

![mo2b2 error](https://cloud.githubusercontent.com/assets/16065686/15614527/4c461810-2407-11e6-9f6c-5f83a52eb65e.jpg)

**Comment by rdunlap** [comment]
The only needed workaround for anyone using xEdit is to remember to manually make backups of esp files you plan to work on and want to have a safe backup of the work. 

Robert

**Comment by TanninOne** [comment]
Additional Info posted by @TwistedByte:

beta 2 generate some weird folders in user home and appdata
and profile ini's still not work

<a href='http://postimg.org/image/641vpor7v/' target='_blank'><img src='http://s33.postimg.org/641vpor7v/Untitled.jpg' border='0' alt="Untitled" /></a>

it generate new random named folders when fallout 4 is launched
maybe something related to ntdll.dll  (  毤Ȁ耀ntdll.dll  was one of subfolders name )
some lines from usvfs ...

02:11:45.252 [I] create config in 1352
02:11:45.252 [I] 0 processes
02:11:45.268 [I] mod_organizer_instance_1 created in process 1352
02:11:45.268 [I] attached to mod_organizer_instance_1 with 1 nodes, size 65536
02:11:45.268 [I] inv_mod_organizer_instance_1 created in process 1352
02:11:45.268 [I] attached to inv_mod_organizer_instance_1 with 1 nodes, size 65536
02:11:48.415 [I] injecting to process 5948 with same bitness
02:11:48.458 [E] exception in usvfs::hooks::CreateDirectoryW: failed to create intermediate directory (The filename, directory name, or volume label syntax is incorrect. [123])
02:11:48.458 [W] 
02:11:48.614 [E] exception in usvfs::hooks::CreateDirectoryW: failed to create intermediate directory (The filename, directory name, or volume label syntax is incorrect. [123])
02:11:48.614 [W] 
02:11:48.675 <4872:2224> [W] GetCurrentDirectoryA called
02:11:51.174 [E] exception in usvfs::hooks::CreateDirectoryW: failed to create intermediate directory (The filename, directory name, or volume label syntax is incorrect. [123])
02:11:51.174 [W] 
02:12:02.813 [E] exception in usvfs::hooks::CreateDirectoryW: failed to create intermediate directory (The filename, directory name, or volume label syntax is incorrect. [123])
02:12:02.813 [W] 
02:12:03.370 <4872:2224> [W] windows exception c0000005 from C:\Windows\SYSTEM32\MSVCP120.dll

**Comment by TanninOne** [comment]
Please get this file:
https://github.com/TanninOne/modorganizer/releases/download/v2.0.6b/usvfs.7z
extract to your MO folder (overwriting the existing files) and let me know if this fixes the problem.

**Comment by rdunlap** [comment]
It fixes the problem of the unexpected folders with heiroglyphic symbols. However the backup file expected to be created is not.

Robert

**Comment by rdunlap** [comment]
Hold on. All behavior is as expected. I had unchecked the backup box yesterday and missed it on my first tests. When doing the next set of test (disable AV etc... ) I noticed it and went back to unaltered workflow and ALL behavior is as expected. MO2B2 will still crash after running xEdit *(same with Creation Kit or any exe that saves data back into the VFS) if I try to run anything without a restart but this behavior has existed since Alpha 1. 

Trying a normal workflow produces normal behavior and even seems faster in doing so.

Robert

**Comment by TwistedByte** [comment]
new usvfs looks good no weird names folders problem
logs looks ok but it show some "unknown" stuff 
...............

19:18:23.371 [I] hooked GetFileVersionInfoSizeW (0x7ff9141cba00) in C:\Windows\system32\KERNELBASE.dll type overwrite
19:18:23.371 [I] hooked GetFileVersionInfoSizeExW (0x7ff9141cc1d0) in C:\Windows\system32\KERNELBASE.dll type overwrite
19:18:23.371 [I] existing hook to 7ff916c30ed6 in unknown
19:18:23.371 [I] hooked NtQueryFullAttributesFile (0x7ff9171176e0) in C:\Windows\SYSTEM32\ntdll.dll type chained patch
19:18:23.371 [I] existing hook to 7ff916c30fd6 in unknown
19:18:23.371 [I] hooked NtQueryAttributesFile (0x7ff917115870) in C:\Windows\SYSTEM32\ntdll.dll type chained patch
19:18:23.371 [I] existing hook to 7ff916c30f16 in unknown
19:18:23.371 [I] hooked NtQueryDirectoryFile (0x7ff917115770) in C:\Windows\SYSTEM32\ntdll.dll type chained patch
19:18:23.371 [I] existing hook to 7ff916c30f56 in unknown
19:18:23.371 [I] hooked NtOpenFile (0x7ff917115730) in C:\Windows\SYSTEM32\ntdll.dll type chained patch
19:18:23.371 [I] existing hook to 7ff916c30f96 in unknown
19:18:23.371 [I] hooked NtCreateFile (0x7ff917115b70) in C:\Windows\SYSTEM32\ntdll.dll type chained patch
19:18:23.371 [I] hooked NtClose (0x7ff9171152b0) in C:\Windows\SYSTEM32\ntdll.dll type overwrite
19:18:23.371 [I] stubbed NtDeleteFile (0x7ff917116960) in C:\Windows\SYSTEM32\ntdll.dll type overwrite
19:18:23.371 [I] existing hook to 7ff913b374c0 in C:\Windows\system32\windows.storage.dll
19:18:23.371 [I] stubbed SHFileOperationA (0x7ff91575c860) in C:\Windows\system32\SHELL32.dll type chained patch
19:18:23.371 [I] existing hook to 7ff9137e8be0 in C:\Windows\system32\windows.storage.dll

**Comment by michaelrw10** [comment]
This does not fix the problem I am having. When I edit a plugin and save it, it is saved using all lower-case characters. Also, if the overwrite path has been manually changed to a folder other than %BASE_DIR%/overwrite (i.e. <PATH>\ModOrganizer\overwrite), the plugin cannot be accessed by opening the Overwrite folder from within MO (it shows as empty). The only way to get your plugin is to manually navigate to the directory and cut/paste. I then also have to rename the plugin with correct case-sensitivity.

**Comment by rdunlap** [comment]
Are you using Beta 2? I had this problem with overwrite in Beta 1 but Beta 2 cleared it up. 

Also, I am seeing the same Lower Case issue you note. I never set my casing until time to make an install so I never noticed it. You MAY want to instead make a new issue for that as it is easier for Tannin to track issues if they stay one issue per thread and this looks like a separate issue.

Robert

**Comment by michaelrw10** [comment]
yeah im on B2.. i figured id mention it here first and if it didnt yield a response id create a new one.. i feel bad for the guy.. 537 issues.. lol

not sure about the non-portable vs portable.. i know the difference.. but I dont remember ever being asked if I wanted a portable install.. as long as ive been using MO, it has been 'portable'.. at least, until some of the data began being stored in the appdata directories. 

but yeah, the case-sensitivity issue is annoying. its pretty common for me to edit other authors' plugins.. small tweaks here and there that are too small to warrant a patch.. so i make my changes, save it, then case is gone. Oh well.. Ill open a new issue

**Comment by rdunlap** [comment]
if the appdata directory is there you are on a multigame install. Portable is like 1.x did it and ALL the files and INI's are in the one directory. basically the same as you would get with an "Unzip" install. Some digging around on the forum you will find a thread that tells how to make your install a portable and i know that will fix the overwrite. But, like I say I am having no issues on the new kind this time around and my paths variables are populating correctly.

its actually easier for him if you have only 1 issue per thread. He can close them cleanly that way. I have seen him nudge people back on target to keep from having a lot of things in one thread.

Robert

**Comment by TanninOne** [comment]
Yes, please create a separate issue. The number of issues doesn't bother me, but it should be obvious I can't go through the comments of hundreds of issues to see if any unrelated problems were reported there...

**Comment by fireundubh** [comment]
Just encountered this issue. The 2.0.6b DLLs solved it. xEdit created plugin backups as normal, too.

**Comment by RS13** [comment]
I was having this issue, and while the DL'd files solved it, they made the game hang for several minutes on launch and most of the time it would never launch.  Putting the old ones back fixed this.

**Comment by rdunlap** [comment]
Fixed in Beta 3

Robert
