### ISSUE TITLE
MO2-FO4Edit 

### ISSUE THREAD

**Issue by Sneaks911** [TanninOne/modorganizer#762]
![2016-05-28](https://cloud.githubusercontent.com/assets/16995276/15629381/538eec88-24dd-11e6-95e8-937dbd23ca6b.png)
MO 2.0.6b running as admin.  Use FO4Edit 3.1.3.0 through MO2 pops this error: FO4Edit 3.1.3 EXPERIMENTAL starting session 2016-05-28 13:56:23
Using Fallout4 Data Path: 
Using ini: 
Fatal: Could not find ini

I don't know what ini. I have tried deleting the inis in the appdata/name/local/mo2/profiles.  That didn't correct the problem.  I had no problem with the 2.0.5 v.

**Comment by rdunlap** [comment]
looks like your paths are not right. set them like I have mine I have no errors.

![fo4edit config](https://cloud.githubusercontent.com/assets/16065686/15629544/52b06b82-24e9-11e6-96ad-3ab88403322e.jpg)

Robert

**Comment by Sneaks911** [comment]
Thanks.  I tried it after changing the paths but get the same error.   ![2016-05-28 2](https://cloud.githubusercontent.com/assets/16995276/15629969/eadd4e08-24ed-11e6-96f3-5b9bfba54ba7.png)
Rhonda

**Comment by rdunlap** [comment]
ok last difference I see is you have xEdit on a separate drive. As an experiment you should copy the whole xEdit folder into the root FO4 folder *(this is where mine is) it could be an issue. If it works from the FO4 folder but not from your F drive then you should post that here and leave the issue open for Tannin to see as its likely something he will want to know about. Permissions are a strange beast in Win 10.

Robert

**Comment by rdunlap** [comment]
Also you appear to still be running Beta 1. Beta 2 addressed many bugs.

**Comment by Sneaks911** [comment]
Thanks for your help.  It seems to be a  FO4Edit issue, as on their Nexxus mod page, someone with the same ini issue found that if you run FO4 Launcher, it reissues the ini.    I will be updating, then.

RHONDA

“When fascism comes to America it will be wrapped in the flag and carrying a cross.”

 Sinclair Lewis  (American Writer, 1885-1951)





Date: Sat, 28 May 2016 14:53:28 -0700

**Comment by fireundubh** [comment]
Yes, you have to run the launcher to set the appropriate paths in the Windows Registry.

This is not an issue with xEdit, or Mod Organizer.

**Comment by TanninOne** [comment]
Assumed to not be a mo2 problem
