### ISSUE TITLE
Beta 1/Beta 2: VFS crashes xEdit on application close

### ISSUE THREAD

**Issue by fireundubh** [TanninOne/modorganizer#763]
Running xEdit through Beta 2 works, but closing xEdit crashes xEdit with or without any plugins loaded.

I have been experiencing this issue in Beta 1, so it's not new to Beta 2.

Visual Studio reports this error:

```
Unhandled exception at 0x0F70BA7E (usvfs_x86.dll) in FO4Edit.exe: 0xC0000005: Access violation writing location 0x00090DC4.
```

[Here's the usvfs log.](https://gist.github.com/fireundubh/2e53209d338fe857e2bb2ab6874ecaf6)

**Comment by fireundubh** [comment]
This is probably a dupe of #741. I didn't search hard enough.

**Comment by rdunlap** [comment]
This seems to have been resolved in Beta 3. It is for me at least. 

Robert

**Comment by TanninOne** [comment]
Can you verify this is fixed fireundubh?

**Comment by fireundubh** [comment]
Seems to be fixed here.
