### ISSUE TITLE
MO Error:  None of the available installer plugins were able to handle that archive

### ISSUE THREAD

**Issue by aba42** [TanninOne/modorganizer#764]
I installed into Skyrim the Sephina Mod.  I then attempted to load the Sephina Customizer, by ClearanceClarence.  All of his other Customizers have worked flawlessly.  I asked ClearanceClarence about this one mod of his, vs. the others.  His response was he has no experience with MO.  Using Version 1.3.11.

Also, curiously, after 6 months of using MO for Skyrim, today I opened it, and all MO settings have reverted to brand-new install.  All my mods are there, but NONE of my tools, formats, NOTHING!

**Comment by aba42** [comment]
Never mind.  This all must have had something to do with MO COMPLETELY RESETTING ITSELF last night.  I got it all reconfigured again, tried the Sephina Customizer, and it worked like a charm.   So, now I'm just left to ponder why MO took it upon itself last night to totally reset itself...grumble, grumble...

**Comment by TanninOne** [comment]
Oh that, yes, that's the artificial intelligence I put into MO so it can make decisions on its own and random acts of destruction...

**Comment by aba42** [comment]
Works like a charm! Thanks!! Man, all these undiscovered benes...when will they EVER run out? 

----- Original Message -----
