### ISSUE TITLE
Windows Defender Considers Installer a Trojan

### ISSUE THREAD

**Issue by flaggro** [TanninOne/modorganizer#765]
After having MO installed for ~1 week, and the installer just chilling in the downloads folder, Windows Defender popped an alert and quarantined the installer file, calling it Trojan: Win32/Varpes.M!cl.  This was on Win10 Pro with WinDefender virus/spyware defininitions 1.223.12.0.

**Comment by WhiteZeroX** [comment]
[False positive](https://www.virustotal.com/en/file/28d122ebf329eaca54b889ac58f940d8318dd9f3ed125a745d237586ab182519/analysis/1464548828/), probably not something that Tannin can "fix" on the MO side. A [false positive report](https://www.microsoft.com/en-us/security/portal/submission/submit.aspx) should be submitted to MS.

**Comment by flaggro** [comment]
I did that before posting here, just posted it to raise awareness.

**Comment by TanninOne** [comment]
Av false positives have to be fixed in the av software so you ahould report them there, nit here. Every av company has a contact adress where you can report stuff like this.
