### ISSUE TITLE
[Mod Organizer v2.0.6 & LOOT 0.9] Loot doesnt open

### ISSUE THREAD

**Issue by HezPwner** [TanninOne/modorganizer#766]
Loot just doesnt open. No message, no log.

**Comment by TanninOne** [comment]
Yes it does

**Comment by HezPwner** [comment]
So, no help for me? :(

**Comment by TanninOne** [comment]
What exeactly do you expect me to do with "loot just doesn't open"???
Current loot with current mo seems to work for most users so there has to be something with your system that sets it apart to explain the diff but you provide nothing. No loot version, no mo version, no os version, no logs (mo creates a log the second it starts so don't tell me there isn't one), no indication if other software works from mo. If your report is lazy, why should I put more work into it?

**Comment by HezPwner** [comment]
Sorry, im very amateur in this type of thing and i didnt wanted to offend you by any means. I really wanted do resolve this problem and i havent seen any report like this one. The LOOT (v0.90) is configurated correctly on the MO (v2.0.6) and it locks the order but doesnt open. This is the latest log:

(sorry for my bad english)

> 20:11:19.411 [I] create config in 9308
20:11:19.411 [I] 0 processes
20:11:19.412 [I] mod_organizer_instance_1 created in process 9308
20:11:19.412 [I] attached to mod_organizer_instance_1 with 1 nodes, size 65536
20:11:19.414 [I] inv_mod_organizer_instance_1 created in process 9308
20:11:19.414 [I] attached to inv_mod_organizer_instance_1 with 1 nodes, size 65536
20:11:36.376 [I] mod_organizer_instance_2 created in process 9308
20:11:36.378 [I] tree mod_organizer_instance_2 size now 131072 bytes
20:11:36.452 [I] mod_organizer_instance_3 created in process 9308
20:11:36.453 [I] tree mod_organizer_instance_3 size now 262144 bytes
20:11:36.622 [I] mod_organizer_instance_4 created in process 9308
20:11:36.624 [I] tree mod_organizer_instance_4 size now 524288 bytes
20:11:37.211 [I] mod_organizer_instance_5 created in process 9308
20:11:37.215 [I] tree mod_organizer_instance_5 size now 1048576 bytes
20:11:37.689 [I] mod_organizer_instance_6 created in process 9308
20:11:37.696 [I] tree mod_organizer_instance_6 size now 2097152 bytes
20:11:38.746 [I] mod_organizer_instance_7 created in process 9308
20:11:38.760 [I] tree mod_organizer_instance_7 size now 4194304 bytes
20:11:41.110 [I] mod_organizer_instance_8 created in process 9308
20:11:41.136 [I] tree mod_organizer_instance_8 size now 8388608 bytes
20:11:43.052 [I] injecting to process 1968 with different bitness
20:11:43.132 [I] (proxy) instance: mod_organizer_instance
20:11:43.133 [I] (proxy) exe: 
20:11:43.133 [I] (proxy) pid: 1968
20:11:43.133 [I] (proxy) size: 8192
20:11:43.133 [I] (proxy) addr: 0xfb0000
20:11:43.133 [I] (proxy) objs: 1
20:11:43.133 [I] (proxy) injecting to process 1968 with same bitness
20:11:43.741 [D] inithooks called mod_organizer_instance in process 1968 (log level 0)
20:11:43.741 <1968:4680> [W] windows exception c0000005 from C:\WINDOWS\SYSTEM32\ntdll.dll
20:11:43.742 [D] process name: F:\Program Files\ModOrganizer\loot\LOOT.exe
20:11:43.743 [I] access existing config in 1968
20:11:43.743 [I] 0 processes
20:11:43.743 [I] mod_organizer_instance_8 opened in process 1968
20:11:43.746 [I] attached to mod_organizer_instance_8 with 1859782688 nodes, size 8388608
20:11:43.746 [I] inv_mod_organizer_instance_1 opened in process 1968
20:11:43.746 [I] attached to inv_mod_organizer_instance_1 with 13 nodes, size 65536
20:11:43.746 [D] context current shm: mod_organizer_instance_8 (now 3 connections)
20:11:43.746 [I] Windows version 6.1 sp 0
20:11:43.746 [D] kernel32.dll at 74950000
20:11:43.746 [D] kernelbase.dll at 770a0000
20:11:43.746 [D] allocated trampoline buffer for jumps between 0x40000000 and 7fffffff at 0x40000000(size 4096)
20:11:43.746 [I] hooked GetFileAttributesExW (0x771506b0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.746 [I] hooked GetFileAttributesW (0x7714fc40) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.746 [I] hooked SetFileAttributesW (0x7717b800) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked CreateFileW (0x7714d7e0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked CreateFileA (0x77164bc0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked CreateDirectoryW (0x77150130) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked DeleteFileW (0x77179ce0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked DeleteFileA (0x771785f0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] stubbed GetCurrentDirectoryA (0x771736b0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked GetCurrentDirectoryW (0x77165d10) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] stubbed SetCurrentDirectoryA (0x771de1a0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked SetCurrentDirectoryW (0x771721c0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked ExitProcess (0x77b27d40) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked CreateProcessA (0x771dbaa0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked CreateProcessW (0x7715fb70) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked MoveFileA (0x74973c90) in C:\WINDOWS\SYSTEM32\KERNEL32.DLL type overwrite
20:11:43.747 [I] hooked MoveFileW (0x7496b1d0) in C:\WINDOWS\SYSTEM32\KERNEL32.DLL type overwrite
20:11:43.747 [I] hooked MoveFileExA (0x7498bb20) in C:\WINDOWS\SYSTEM32\KERNEL32.DLL type overwrite
20:11:43.747 [I] hooked MoveFileExW (0x77165080) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked CopyFileA (0x7496f780) in C:\WINDOWS\SYSTEM32\KERNEL32.DLL type overwrite
20:11:43.747 [I] hooked CopyFileW (0x7716a900) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked CopyFileExA (0x7498c190) in C:\WINDOWS\SYSTEM32\KERNEL32.DLL type overwrite
20:11:43.747 [I] hooked CopyFileExW (0x7716a930) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] stubbed CreateHardLinkA (0x771a83f0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] stubbed CreateHardLinkW (0x771a8470) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked GetFullPathNameW (0x771619e0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked GetFileVersionInfoW (0x77165450) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.747 [I] hooked GetFileVersionInfoExW (0x7714cd50) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.748 [I] hooked GetFileVersionInfoSizeW (0x77166780) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.748 [I] hooked GetFileVersionInfoSizeExW (0x7714cfd0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.748 [D] ntdll.dll at 77ad0000
20:11:43.748 [I] hooked NtQueryFullAttributesFile (0x77b47ee0) in C:\WINDOWS\SYSTEM32\ntdll.dll type overwrite
20:11:43.748 [I] hooked NtQueryAttributesFile (0x77b46fa0) in C:\WINDOWS\SYSTEM32\ntdll.dll type overwrite
20:11:43.748 [I] hooked NtQueryDirectoryFile (0x77b46f20) in C:\WINDOWS\SYSTEM32\ntdll.dll type overwrite
20:11:43.748 [I] hooked NtOpenFile (0x77b46f00) in C:\WINDOWS\SYSTEM32\ntdll.dll type overwrite
20:11:43.748 [I] hooked NtCreateFile (0x77b47120) in C:\WINDOWS\SYSTEM32\ntdll.dll type overwrite
20:11:43.748 [I] hooked NtClose (0x77b46ca0) in C:\WINDOWS\SYSTEM32\ntdll.dll type overwrite
20:11:43.748 [I] stubbed NtDeleteFile (0x77b47820) in C:\WINDOWS\SYSTEM32\ntdll.dll type overwrite
20:11:43.748 [D] shell32.dll at 75760000
20:11:43.748 [I] stubbed SHFileOperationA (0x759bd2f0) in C:\WINDOWS\SYSTEM32\SHELL32.dll type overwrite
20:11:43.748 [I] stubbed SHFileOperationW (0x758710e0) in C:\WINDOWS\SYSTEM32\SHELL32.dll type overwrite
20:11:43.748 [I] stubbed ShellExecuteA (0x759cdee0) in C:\WINDOWS\SYSTEM32\SHELL32.dll type overwrite
20:11:43.748 [I] stubbed ShellExecuteW (0x758efc50) in C:\WINDOWS\SYSTEM32\SHELL32.dll type overwrite
20:11:43.748 [I] stubbed ShellExecuteExA (0x759cdf60) in C:\WINDOWS\SYSTEM32\SHELL32.dll type overwrite
20:11:43.748 [I] stubbed ShellExecuteExW (0x758f08e0) in C:\WINDOWS\SYSTEM32\SHELL32.dll type overwrite
20:11:43.748 [I] hooked LoadLibraryExW (0x7714e8b0) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.748 [I] hooked LoadLibraryExA (0x7714cd00) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.748 [I] hooked LoadLibraryW (0x77150e50) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.748 [I] hooked LoadLibraryA (0x7714c980) in C:\WINDOWS\SYSTEM32\KERNELBASE.dll type overwrite
20:11:43.748 [I] hooked GetModuleFileNameW (0x74969b00) in C:\WINDOWS\SYSTEM32\KERNEL32.DLL type overwrite
20:11:43.748 [I] hooked GetModuleFileNameA (0x7496a720) in C:\WINDOWS\SYSTEM32\KERNEL32.DLL type overwrite
20:11:43.748 [D] hooks installed
