### ISSUE TITLE
[MO2] Override Loose Files in Data\ not displayed

### ISSUE THREAD

**Issue by Kestatwala** [TanninOne/modorganizer#770]
Unlike its predecessor, MO2 doesn't display the "override" flag for mods containing files that overrides those located in the original Data\ folder. (They're still listed properly in the "conflict" tab).

Edit: Only "actual loose files" like textures have this issue. Overwriting an .esp still display the icon.

**Comment by michaelrw10** [comment]
ive actually had problems with having loose files in my data folder while using MO2, the least of which has been not having the override flag. Not sure if it still holds for the beta release, but back with the MO2 alphas, there were times that having loose files (textures, meshes, materials, etc) would cause ctd or would cause textures from MO not to be loaded at all. But, I digress. I will test with this current build and see what I find

**Comment by michaelrw10** [comment]
I can confirm that overrides of textures, materials, and meshes do not show up in MO2. 

(as far as the other problems i experienced in MO2 alphas, those no longer exist)

**Comment by TanninOne** [comment]
It isn't supposed to show the flags for conflicts with data and it didn't in the later MO1 versions. The conflicts of esps are displayed because/if the conflicting esp is not an official file and shows up as an "unmanaged" mod.
