### ISSUE TITLE
F4SE 1.5.157 obsolete

### ISSUE THREAD

**Issue by Kitsudragon** [TanninOne/modorganizer#775]
Update of FO4 just this evening has made latest "current build" of F4SE obsolete. Current issues with MO and F4SE may be unfixable until next version becomes common build.

(Information only, close if no comment.)

**Comment by rdunlap** [comment]
There is a build for 205 Beta that works fine.
http://f4se.silverlock.org/beta/f4se_0_01_14.7z

Robert

**Comment by michaelrw10** [comment]
yeah this happens each time there is an update from one version to the next.. the current version is the old beta, so the f4se for that beta will work just fine.. check back for the 'official' update later.

also, not sure what this has to do with MO..

**Comment by rdunlap** [comment]
me either but thought i would be helpful. They may be one of the ones that are having issues running F4SE with MO2.

Robert

**Comment by Leer0x** [comment]
Why posting this in the Mod Organizer issues? You shouldn't do that.

**Comment by Kitsudragon** [comment]
OKay, sorry about that. Is there a forum somewhere? Discussion type topics and a place to put them would help, I think.
