### ISSUE TITLE
MO 2.0.6 Configurator error.

### ISSUE THREAD

**Issue by GSDFan** [TanninOne/modorganizer#787]
When running the configurator from the tool drop down I get the following error in a pop up window:

---------------------------
Error
---------------------------
Plugin "Configurator" failed: Traceback (most recent call last):
  File "E:/PC Installed Programs/ModOrganizer/plugins/pyCfg.py", line 574, in display
    self.updateSettings(settings, iniFile)
  File "E:/PC Installed Programs/ModOrganizer/plugins/pyCfg.py", line 471, in updateSettings
    profile = self.__organizer.profile()
TypeError: No to_python (by-value) converter found for C++ type: class MOBase::IProfile * __ptr64

Sorry if this is a duplicate, I could not find any other reference to the configurator.

**Comment by RestedWicked** [comment]
configurator is not implemented yet

**Comment by KeltecRFB** [comment]
It worked in 2.0.4

**Comment by GSDFan** [comment]
This is now working in 2.0.7b3. Closed
