### ISSUE TITLE
Trojan Detected in Mod Organizer 2 Beta 2?

### ISSUE THREAD

**Issue by SomeTaffer** [TanninOne/modorganizer#788]
Today when starting up my computer, Microsoft Security Essentials stated that the Mod.Organizer-2.0.6.exe was a trojan called Win32/Varpes.M!cl.
I don't know if it is a false positive or whatever, but it has detected multiple instances of it as well
![image](https://cloud.githubusercontent.com/assets/19763574/15807005/a465f352-2b1f-11e6-937c-85f70fe31744.png)

**Comment by izak64** [comment]
Same problem, anything past 2.0.4a says it contains a trojan.

**Comment by WhiteZeroX** [comment]
False positive, same as Issue #765. Report the FP to Microsoft. Use VirusTotal before bothering to report these kinds of things.  :)

**Comment by TanninOne** [comment]
Yes, please report false positives to the AV company
