### ISSUE TITLE
[Feature request] Sorting left-pane logically

### ISSUE THREAD

**Issue by japp1egate** [TanninOne/modorganizer#789]
I'm not sure how feasible this feature would be to implement, but I recently had my profiles get clobbered by a filesystem issue.

In order to recover faster than a manual sort would allow, especially for setups with a very large number of mods (I have nearly 1500 installed for Skyrim), might it be possible to use a logical system similar to LOOT's masterlist, using Nexus ID info already there, to re-sort MO's left pane?

**Comment by TanninOne** [comment]
Not really, unlike with esps there is no way to unique identify a mod. You can rename them, you can get them from a non-nexus source so there may not be an id, ...
Also, loot usually determines the order automatically, using the masterlist only in special cases where the automatism fails, there is no way to do this for mods.

There is an ancient feature proposal I made myself (issue #13) that would allow you to set up mod dependencies based on which it can order the mods, but you would still have to define the dependencies yourself. And I never got around to implementing it yet.
