### ISSUE TITLE
When i ran FNIS Generator it creates a lot of weird folders

### ISSUE THREAD

**Issue by DRSXS** [TanninOne/modorganizer#792]
I assume it's some issue with charsets, but it shouldn't be making folders in the Users Folder anyways...
![capture](https://cloud.githubusercontent.com/assets/17381598/15901180/8a656c3c-2da2-11e6-8c47-335226fffb66.JPG)
![capture3](https://cloud.githubusercontent.com/assets/17381598/15901181/8a676f6e-2da2-11e6-83b8-3773046cd4be.JPG)

**Comment by BlazeOfHell** [comment]
Same here with BodySlide. Also ModOrganizer2.0.6b do not detect any files in overwrite folder

**Comment by michaelrw10** [comment]
Duplicate issue: please see #753 (post 4)

tannin posted some replacement files you can download. Place in your MO root directory. This will fix your issue

**Comment by TanninOne** [comment]
Exactly

**Comment by DRSXS** [comment]
Thank you, sorry for the duplicate. This fixed all my problems :)
