### ISSUE TITLE
F4 Overwrite files not creating

### ISSUE THREAD

**Issue by BlazeOfHell** [TanninOne/modorganizer#793]
Bodyslide reports that all files were created successfully, but there are no files in overwrite folder and even if I place fake files in that folder MO2.0.6b reports that it is empty.

**Comment by michaelrw10** [comment]
all the files were created.. somewhere. You need to track them down and maybe that will help you troubleshoot the issue
([Everything](https://www.voidtools.com/downloads/) search tool is preferred over windows search)

**Comment by BlazeOfHell** [comment]
Tried to create custom skeleton femalebody.nif, again said it was created, but only original CBBE skeleton was found

**Comment by Akzyra** [comment]
Yes it is. Thats how it works. Has to do with how apps and tools write files.
BS opens a file and then writes into it, which will just modifiy it. New file if it not exists.

**Comment by TanninOne** [comment]
Yes, this is the expected behaviour. There  was a lengthy discussion about this I would rather not repeat, please trust that I've thought about this and this is the best option currently.

**Comment by BlazeOfHell** [comment]
Ah, ok, thank you for an explanation
