### ISSUE TITLE
[Feature Request] Collapsible user groups/folders in the modlist

### ISSUE THREAD

**Issue by mfriendc** [TanninOne/modorganizer#797]
(Summary:) I feel like it would be incredibly useful to be able to be able to group mods into custom collapsible folders/groups in the modlist for easier sorting and tidying purposes

(Full:) I feel like this is a feature that probably would have been asked for in the past, but I can't seem to find it through searching

I recently noticed that it takes a while for me to scroll through my modlist because of how many things are in there. I thought it would be really cool to be able to group similar mods together into collapsible groups or folders in the modlist to not only group like mods, but to also tidy up the rest of the modlist

as an example, if I had some 30-odd playerhome mods (I don't, but bear with me) I could go in and right click in the mod list and do "create group", name it "playerhomes" and drag and drop all of my playerhome mods into that group, collapse the folder, and have a neater modlist instantly, all 30 would be contained in the folder/group and I wouldn't have to go past them when I'm trying to move other mods around or when I'm trying to find some elusive mod I lost in the menu somewhere

also some features that aren't important to the actual idea but i thought might be interesting if it were implemented:
  maybe show the number of mods in the group after the group name? ("playerhomes (30)")
  maybe a checkbox for the entire group for mass enabling or disabling of mods (the individual mods themselves would still keep their enabled/disabled status, but the folder's checkbox, when disabled, would override all of the content inside to disabled regardless of their own checkboxes, kinda like a layergroup in an image editing program)

**Comment by Aether89** [comment]
What you asked already exist merely under another name.
Use the Categories filter and the mod that fall under the same category will collapse together.
If the default categories are not to your taste, you can always change them or create new one.

**Comment by TanninOne** [comment]
Mod grouping is already supported. Using the drop-down box below the mod list you can choose to group by nexus id or category. Grouping by category should be exactly what you're looking for.

**Comment by mfriendc** [comment]
oh, that's perfect, I had no idea that that was how that worked, I thought ID view was the only one
