### ISSUE TITLE
Trojan Virus?

### ISSUE THREAD

**Issue by Kattmandu** [TanninOne/modorganizer#798]
Is it safe to assume that Beta 2 is free from viruses?  Antivirus program is flagging it as being infected with Trojan:Win32/Varpes.M!cl.  Is it just a false positive?

**Comment by WhiteZeroX** [comment]
https://github.com/TanninOne/modorganizer/issues?utf8=%E2%9C%93&q=is%3Aissue+virus

#765

**Comment by Kattmandu** [comment]
Thanks!  I tried searching for this very issue regarding MOB2 but couldn't figure out the search function on GitHub.  *sigh*
