### ISSUE TITLE
Mod Organizer 2 Will not load Bodyslide, fallout 4, fallout 4 launcher, and f4se is a different story.

### ISSUE THREAD

**Issue by oStarZ** [TanninOne/modorganizer#809]
So the title and also when I try to load F4SE in mod organizer 2 it pops up with the small black console window and nothing happens. It just stays there. I am unable to play with my mods atm because when you load the launchers outside of MO the mods don't work.

Edit- It works now. I just restarted my computer.

**Comment by GabrielWaynel** [comment]
This actually happens quite often. Most often after MO2 has crashed. The _ini_ file gets wiped or something. One has to then execute the game launcher _outside_ of MO and redo all the settings and exit launcher. Restart MO and all should work.
