### ISSUE TITLE
LOOT 0.9 not locating FO4 w/ MO2

### ISSUE THREAD

**Issue by drbeavi5** [TanninOne/modorganizer#811]
Hi, I'm getting the following error when trying to run loot 0.9

> Error code: -1; Failed to get game data. Details: boost::filesystem::directory_iterator::construct: The system cannot find the path specified: "E:\Steam2\SteamApps\common\Fallout 4\Data"

EDIT - I'm running the Insider's preview of W10 btw. SKSE and Fallout 4 work fine. I've tried the new files and methods mentioned in other threads and tried to use the LOOT included within MO2 to no avail.  

here is the log file. thanks in advance

[usvfs-2016-06-17_19-15-24.txt](https://github.com/TanninOne/modorganizer/files/321126/usvfs-2016-06-17_19-15-24.txt)

**Comment by TanninOne** [comment]
The log seems to have been created with log level set to "info". Please set the log level to "debug" and repeat.

**Comment by drbeavi5** [comment]
This is weird, my version of Windows updated yesterday and I no longer have the issue (which had been going on for about 2 months but I never reported it as I wasn't seeing anything wrong with my load order nor bugs ingame).
