### ISSUE TITLE
Migrating up from MO 1.x

### ISSUE THREAD

**Issue by ogrotten** [TanninOne/modorganizer#812]
There doesn't appear to be documentation on migrating from MO 1.x to MO 2.x

I have Skyrim setups that aren't necessarily fragile, but I don't want to fuck them up. And I don't think that I could duplicate them manually. Is there a link or text I missed?

**Comment by ChaosTherum** [comment]
Just 7-zip the mod organizer folder install the new one over it if it doesn't work you can revert.

**Comment by TanninOne** [comment]
Installing MO2 over MO1 should work. But even if it doesn't: I'm not developing a migration path and documentation would have to come from someone else.

**Comment by ogrotten** [comment]
If I were to take the task to write docs for a manual migration that worked in this version, would you be willing to attempt to fix bugs that may pop up in future versions?
