### ISSUE TITLE
MO2 not listing second game instance but saving directory's setting.

### ISSUE THREAD

**Issue by LeFlemard** [TanninOne/modorganizer#813]
Oyo/
While trying to prepare for upcoming new version of skyrim, I tried using the new instance thingymagic. It created a new instance and found the game files, I change the main directory location (using another drive), but when wanting to switch back to FO4 instance, I don't see it listed.
I try creating a new instance thinking it was an hiccup, but I'm surprised to see that the mods, main directory's location and plugin list of the disappeared instance is shown.
(tried switching back and forth and it still don't appear in the instance list.)
Thanks.

**Comment by TanninOne** [comment]
Did you originally have a portable install?

**Comment by LeFlemard** [comment]
I don't really remember, sorry, but I have MO installed in program files and MO folders in roaming folder... (on another subject, does overwrite works btw?)

**Comment by TanninOne** [comment]
Appears to be fixed. False positives you have to report to the av company
