### ISSUE TITLE
2.07b not merging with olde vrsn. install folders

### ISSUE THREAD

**Issue by LoneYukon6512** [TanninOne/modorganizer#816]
...I had to reconfigure my paths in settings after update....minor, I know...just a heads up

**Comment by LoneYukon6512** [comment]
...actually it seems I have to reconfigure all mod priorities also...
...am I supposed to do this with every new version? I know this is still testing and beta stuff....just seems like a hassle with 200+ mods

**Comment by RestedWicked** [comment]
didn't change anything for me

**Comment by LoneYukon6512** [comment]
changed everything here...actually looking at my install....previous install was to my game folder...update didn't search out install location...just created a new install in C:\ Program Filesx86
...uh...my bad?

**Comment by RestedWicked** [comment]
kek

**Comment by TanninOne** [comment]
If you create portable installs and install in different directory it will not use the same settings. That's the whole point of a portable install
