### ISSUE TITLE
Question/Issue with Configurator MO 2.0.7

### ISSUE THREAD

**Issue by mfeile1974** [TanninOne/modorganizer#818]
My apologies if this has already been addressed: 

I have been unsuccessful getting any textures/meshes to show up in game either using MO as install method or by manually installing (both methods using MO to launch SKSE)

However I noticed today while taking a look at the newest update that under the Configurator option under Archive:  the SArchiveList points to Skyrim - Textures.bsa?

I've check all .ini as well as all directories and everything appears to be in order.  Can anyone instruct me on how to fix or is this a common issue?

**Comment by rdunlap** [comment]
define what textures and meshes you are trying to get loaded. I say this because i have found an issue with one of the mods I have released where the precombined nifs are what is seen in the game on cells that are not edited. any cell that has been edited causing the precombined data not to be used and my nifs are in the game.

Robert

**Comment by mfeile1974** [comment]
Basically every texture/mesh is not loading correctly.  Here are just a few of the ones I was trying: http://www.nexusmods.com/fallout4/mods/12137/? ;  http://www.nexusmods.com/fallout4/mods/6825/? ; http://www.nexusmods.com/fallout4/mods/6176/? ; http://www.nexusmods.com/fallout4/mods/1934/?

**Comment by mfeile1974** [comment]
![image](https://cloud.githubusercontent.com/assets/20022567/16181289/21c472a4-3667-11e6-8dc9-343e361e348b.png)


I'm not sure if this makes a difference but this is the part that really has me stumped.

**Comment by rdunlap** [comment]
I do not think that would be causing your issue. That is the INI configurator and MO2 is still not using the profile ini files. The ini files used are the normal ones that the game creates. Likely that is why you are seeing some old default data in the configurator. 

Now, i have grabbed and tried those 4 mods and they load up fine for me. :| I don't know what direction even to suggest for you on it. If it were me I would make a backup copy of my Mods folder and my Profiles folder *(and downloads if there are any there you want to preserve) and then Uninstall the whole of MO2. Do a fresh clean install and see if that solves your issue with missing resources. Another couple of places to look is the Permissions MO2 are running under and temporarily disable your Anti Virus software and run like that once to see if it is causing an issue. Windows 10 has some strange permissions behaviors and several AV products seem to decide at random that MO2 is some kind of malware based on heuristics.

Robert

**Comment by mfeile1974** [comment]
Thank you Robert for the feedback.  I already verified permissions (Win 7), added MO to my Anti-Virus exceptions, etc.   I will try reinstalling in the AM.

**Comment by mfeile1974** [comment]
Reinstall did not help at all...still having issues with having textures/meshes showing

**Comment by mfeile1974** [comment]
I feel like a total a$$ now...totally forgot to install the Spring Cleaning Compatibility patch.  Now everything works as it should.  Closing now...thanks again for your assistance.
