### ISSUE TITLE
Permission locked?

### ISSUE THREAD

**Issue by AtomicAquarius** [TanninOne/modorganizer#819]
It seems like any mod I try to reinstall or update suddenly gets locked, saying that I need permission to modify or read the folder. I'm the admin and only user of my computer and I've launch MO in admin mode. The change only happens on the attempts to update or reinstall. This is currently only affecting a small number of my mods but I am afraid to change any others. I am using MO 1.3.11 for Skyrim.

**Comment by TanninOne** [comment]
If you're certain you have write permission to the directory the only other explanation is a foreign application that keeps an exclusive lock on the dir. You can use tools like lockhunter to find out which app it is.

**Comment by AtomicAquarius** [comment]
Thanks so much Tannin! The files seem to have disappeared after restarting my computer but I'll be sure to use this.
