### ISSUE TITLE
MO window low resolution help

### ISSUE THREAD

**Issue by hailsithisis** [TanninOne/modorganizer#821]
![capture](https://cloud.githubusercontent.com/assets/20043610/16193268/0090d2c2-3729-11e6-8d0b-1b122e3d3b7c.JPG)

as you can see in screenshot, resolution is low and MO window is hard to control ( buggy dragging)
when i used Mo few months ago, this problem didn't occured
sry for poor english
if anyone suffured or know the answer of this problem, help me!

**Comment by TanninOne** [comment]
The rendering resolution/dpi is not controlled by the application but by the os. Also: this is mo 1.3.11 which hasn't changed in many months so it has to be a change on your end.
