### ISSUE TITLE
Plugins not found in both Loot and FO4Edit

### ISSUE THREAD

**Issue by Archangelius** [TanninOne/modorganizer#826]
When running both loot and fo4edit through the executables in mod organizer, only the vanila esms show up (base game and dlc).
I have tried numerous different locations for mod organizer including portable installs. I have tried running both MO and loot/fo4edit as admin. This is running v2.0.7

**Comment by TanninOne** [comment]
Please attach an usvfs_<date>.log created when running loot or fo4edit

**Comment by Archangelius** [comment]
I am having trouble finding a log to post. I mean maybe I am looking in the wrong place, but under \AppData\Local\ModOrganizer\Fallout 4\logs my usvfs log is completely empty. I have tried to delete the logs folder, relaunch and run things to generate anything but nothing ends up in the log.

**Comment by Archangelius** [comment]
So this probably does not help, but out of nowhere Loot and FO4Edit work now. I didn't change anything minus a reboot earlier (reboots were not helping in the past?). Thanks for the help though.

**Comment by mscheetham** [comment]
hello,  I'm currently having this exact same issue in that loot and fo4edit do not seem to be receiving the plugin list

[mo_interface.txt](https://github.com/TanninOne/modorganizer/files/344530/mo_interface.txt)

The usvfs file is empty as above.  I've tried everything inc reinstallation, deleting and recreating profile, and removing mods. everything runs as admin.

The thing is, is that this was all working fine yesterday and then suddenly this.  Even te built in loot is not working, though i've never used it before so i dont know if it was before.
