### ISSUE TITLE
2.0.7 Windows Defender

### ISSUE THREAD

**Issue by yndrelbosch** [TanninOne/modorganizer#832]
For some odd reason, Windows Defender keeps putting the installer in quarantine, saying it has detected malware...

**Comment by KiPhemyst** [comment]
Same issue: Defender reports it as Trojan:Win32/Varpes.M!cl. I did manage to install MO without defender being angry at it, and the installed items appear to be clean, but after a reboot Defender quarantined the installer.

**Comment by RPINerd** [comment]
I'm running windows 10 and haven't had any issues with this; I am running Avast as well so maybe part of my Defender is disabled to avoid redundancy?

A stupid question, but you are downloading through the official github release page right?

**Comment by KiPhemyst** [comment]
Yep, it is definitely the official download. I did a Virus Total scan, if that helps: https://www.virustotal.com/en/file/a07e3cbbdabfadc1bb1bdba11b71fd7b528efb93e2e10c995c89065699e68085/analysis/1466795550/

**Comment by RPINerd** [comment]
And is Windows Defender the only AV you're using?

**Comment by KiPhemyst** [comment]
Yep. Also I just updated the definitions manually and it seems OK now (for me at least). Maybe faulty definition update from Microsoft?

**Comment by RPINerd** [comment]
Yeah I mean if you downloaded it straight from here, it's clearly a false positive. But annoying nonetheless haha

**Comment by yndrelbosch** [comment]
it is annoying, yeah, and yes, Windows Defender is the only AV I run, mostly because I don't trust the free AVs and can't afford a subscription to the paid ones XD.

As to where I downloaded it, straight from the releases page here on GitHub.

**Comment by Genaeve** [comment]
This did happen to me as well, I turned off Windows Defender for the few seconds it took me to dl and install. Then I turned it back on. But, I do have AVG which did not call it.

**Comment by TanninOne** [comment]
False positives are bugs in the AV and need to be reported to the AV company. I can't fix Windows Defender.
