### ISSUE TITLE
[MO 1.3.11] [Skyrim] "Visit on Nexus" button leads to main Nexus page, not to the mod page

### ISSUE THREAD

**Issue by VictorDragonslayer** [TanninOne/modorganizer#835]
I can view the mod page via "Nexus Info" tab, but when I click "Visit on Nexus", link `http://ww.nexusmods.com/skyrim/downloads/file.php?id=<mod ID>` is redirected to `http://www.nexusmods.com/games/?id=<mod ID>`, which is incorrect and leaves me at `http://www.nexusmods.com/games/?`. Current link format for mods is `http://www.nexusmods.com/skyrim/mods/<mod ID>/?`.

**Comment by TanninOne** [comment]
This is already fixed in MO2.

**Comment by yndrelbosch** [comment]
PS. I find this happens a lot, not with MO, but with mod authors who haven't updated the links on their nexus page, what i do is I just select the _/games/_ part and replace it with _/skyrim/mods/_ I'm posting this mainly for reference XD.
