### ISSUE TITLE
[Feature Request] Better mod organization by adding folders

### ISSUE THREAD

**Issue by CodePunk-** [TanninOne/modorganizer#850]
Could you add an option to create folders and able hide them? Similar to NMM but an easier way to move mods around. 
I have over 300 mods and it's getting harder to keep track. I think creating a folder and dropping mods into it would be easier than creating categories.

Thank you for the amazing program.

**Comment by RPINerd** [comment]
In general I think some organizational aids would be greatly appreciated.

As a stopgap in the meantime, I've taken to using empty mods to create "folders"
http://i.imgur.com/by64ogN.png

**Comment by TanninOne** [comment]
That's what the grouping option below the mod list is for.

**Comment by CodePunk-** [comment]
They are not that useful when the most are not related with each other, please reconsider.

**Comment by TanninOne** [comment]
Why would you put mods together into a folder if they are not related? How is that organizing anything?

**Comment by CodePunk-** [comment]
For example, the Skyrim step-project guide has about 12 categories, around 230 mods to install. Many mods require specific settings or patches to work well with different mods or ENBs. 

Armor textures use different body skin texture, CBBE, UNP, UNPB. 
Weapon textures require different settings for FNIS, animations, skeleton, etc. 
A few ENBs not working with a handful of weather, lighting, grass mods.

Mod Organizer gets cluster with so many mods. It's frustrating when something breaks and you have to search that long list to find the culprit. I'm not asking you to remove the grouping option list, I use it all the time. But I believe a more visual friendly expand/collapse tree-view to the main window could help a lot of folks like me.  

Please write this request on the future feature list or put a request and maybe someone else could write the code. Thanks for the reconsideration and many tanks for keeping mod organizer alive.

**Comment by TanninOne** [comment]
What is stopping you from creating categories in mo for the step categories?

This is not about the amount of work for the implementation, I wouldn't merge this feature if you already had this implemented, I just don't want two features for the same function because that just overloads the ui.
If I included every feature anyone ever proposed, the ui would just be a sea of buttons and controls and noone could use it.

Also, if grouping is active, which already turns the mod list into a tree, how would that interact with your folders? Would grouping add another tree level below folders or above them? Or would the two be mutually exclusive?

**Comment by RestedWicked** [comment]
what RPINerd said.
same thing I do. Useful specially when following guides like STEP. Use it to separate the STEP sections in addition to the categories and groupings. Even easier with the "create empty mod" feature of the latest beta

**Comment by RPINerd** [comment]
The grouping feature is something I didn't even know about until Tannin brought it up a couple days ago. Combining it with create empty mod is a pretty full featured organization system. The only addition that would be nifty is an option to color code mods in addition to giving them categories ^-^

**Comment by CodePunk-** [comment]
Sorry TanninOne, maybe I'm being a nonsense.

What I request is something similar to the "Nexus IDs" option. It only groups the mods with the same IDs and keeps the order in which they are. I'd like to create those groups (right clicking > create group.. maybe?) and keep their priority. 

The "categories" option already has the installed mods categorized and if one belongs to many, the priority becomes meaningless. Adding an additional option to the drop list for manual categorization and leave the others as is, is what I'd love to have as a feature. 

Would removing the default categories be possible? I think I can pull this off if I remove the default and make my own. Any thoughts?

**Comment by RestedWicked** [comment]
You do know that you can remove mod's categories by just un-ticking them right?

**Comment by CodePunk-** [comment]
Is it the one with the right-click > add/remove categories? if it is, I have 432 mods, please tell me there's an easier way?

**Comment by RestedWicked** [comment]
you could've removed default categories after each mod installation. If you didnt and want to do it now, sort your modlist by category, select all mods from each category and remove only once per category. repeat until there is no more default categories set. sort the modlist again by priority to show the order you installed through STEP. create the STEP categories (C-Extenders, D-Fixes, etc, etc) and add all mods of each section to its new category at once.

**Comment by CodePunk-** [comment]
Now I can't search by filter. All I want is an additional option where I can name the group, drop mods, and organize them. Keeping the priority as they're listed down the line. This feature could be just another option on the list and doesn't have to conflict with the others.

I appreciate your help RestedWicked, but it's now quite right what I want, thanks though.
