### ISSUE TITLE
Mod.Organizer-2.0.7.exe detected as Trojan:Win32/Varpes.M!cl by Windows Defender

### ISSUE THREAD

**Issue by Consequences** [TanninOne/modorganizer#851]
Title sums it up. Beta 3 detecting as virus.

Download the file, opened it up, only got to the first page where you select what components to install and Windows Defender started flagging it.

hxxps://github.com/TanninOne/modorganizer/releases/download/v2.0.7b/Mod.Organizer-2.0.7.exe

VirusTotal says the file is clean.

(md5=375aa16e031b062b490f3d17467a2d79, sha1=34d69d98b67c6ebd59088206451fc8422d75a721)

**Comment by RPINerd** [comment]
Same as another (now closed) issue #832 

If I remember correctly.. the solution was to just ignore it XD haha

**Comment by Consequences** [comment]
Appreciate the help, didn't see it when I searched. Closing.
