### ISSUE TITLE
Nexus Log In failing

### ISSUE THREAD

**Issue by Denomix** [TanninOne/modorganizer#861]
Not sure if it's just me, but recently stopped picking up mods due to other things being done, using version 2.0.7. Went to go hunt for more mods just now and couldnt get it to take the credentials for log in. Yes, i've made sure on Nexus that i didnt forget my password and I'm a tad confused. the workaround is set to the current version on NMM (habit from the original). For all I know it could be the fact i'm using it for both Skyrim and Fallout 4, but that is what is currently going on for me.

**Comment by ivlorgan** [comment]
Exactly the same issue using 1.3.1.1

**Comment by RiffyDivine** [comment]
Seems a few of us are having the issue now.

**Comment by kranky1260** [comment]
Hi i had the same issue as well tonight the login issue stopped after i
rebooted my computer now works just fine.

**Comment by Denomix** [comment]
Problem resolved itself. Riffy was correct.
