### ISSUE TITLE
Latest version of Fallout 4 no longer compatible with Mod Organizer

### ISSUE THREAD

**Issue by CJM7** [TanninOne/modorganizer#899]
With the release of DLC03, Mod Organizer can no longer launch FO4 without a CTD, attempting to launch FO4Edit results in the following error message:

Fatal: Error loading plugin list: \<EAccessViolation: Access violation at address 6594F20C in module 'MSVCR120.dll'. Read of address 01228000>

**Comment by kstarler** [comment]
I am able to load into the game through MO without issue in Win 7 64-bit Home. Is it possible this is load order related? DLC's always appear at the bottom of the list the first time MO is run after an install. If it's not the load order, have you tried disabling all mods and attempting to load into the game?

**Comment by ryunnsun** [comment]
I have the same issue. I disabled all mods (right pane first, then left to remove files from load order) and no matter what I do it causes a CTD with the same faulting library (msvcr120.dll) in the event log. I can launch the game without issue from steam.

I also tried repairing my Visual C 2013 installation, no change.

**Comment by SnowbankNL** [comment]
Do you run the achievements mod(http://www.nexusmods.com/fallout4/mods/12465/?)? That is crashing it for me. Guess its needs updating.

**Comment by ryunnsun** [comment]
I do run achievements, but I'm pretty sure I disabled it. Will try again when I get home from work.

**Comment by SnowbankNL** [comment]
Strange for me its specifically that mod. Whats even stranger is that the mod if already up to date for the DLC and when manually installed it everything works for me.

**Comment by ryunnsun** [comment]
Just double checked myself - Even when I uncheck all my mods on the left side, which removes them from the VFS when FO4 launches, I still get a CTD on loading up (please stand by intro). It also drops an event in my windows logs:

Faulting application name: Fallout4.exe, version: 1.6.9.0, time stamp: 0x57802071
Faulting module name: MSVCR120.dll, version: 12.0.21005.1, time stamp: 0x524f83ff
Exception code: 0xc0000005
Fault offset: 0x000000000003c3f9
Faulting process id: 0x2074
Faulting application start time: 0x01d1e778216f83e8
Faulting application path: E:\Games\Steam\steamapps\Common\Fallout 4\Fallout4.exe
Faulting module path: C:\WINDOWS\SYSTEM32\MSVCR120.dll
Report Id: 298c5aa0-5431-46b7-b0b7-623db2f3dc1e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by GSDFan** [comment]
With each DLC, Beth updates Fallout4 - interface.ba2. I am not getting the MSVCR120.dll problem but was getting CDT at start. I disabled DEF_UI and my problem went away. Traced it down to HUDMenu.swf. Hiding that file allows me to play.

**Comment by CJM7** [comment]
Apologies, forgot XMLs could cause CTDs.
In any case, it runs fine absolutly vanilla, so not an MO problem, I think.
