### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by stenenpelle** [TanninOne/modorganizer#909]
I downloaded MO, installed some mods, checked the load order, started skse, saw the bethesda intro, got to the next screen, clicked new, clicked yes, and then the skyrim logo just stood there on its own, with the dovahkiin music in the background and my mouse still visible, 
got my mods (left screen in MO) listed here:
[spoiler]

a quality world map and solstheim map

apocalypse, magic of skyrim

auto unequip ammo

become high king of skyrim

better sorting

bijin npcs

bijin warmaidens

bijin wives

cloaks of skyrim

convenient horses

dwemertech, magic of the dwarves

extended ui

falskaar

forgotten magic redone

guard dialogue overhaul

helgen reborn

hidden treasures

immersive hud

levelers tower

moon and star

moonpath to elsweyr

2k legacy of the dragonborn

morehud

racemenu

skyrim school of witchcraft and wizardry

skyui

spectraverse

thunderchild

unofficial skyrim legendary patch (got legendary edition btw)

alternate start

open cities skyrim

undeath

werewolf mastery

violens, a killmove mod

[/spoiler]

plugins list: [spoiler]

skyrim.esm

update.esm

dragonborn.esm

hearthfires.esm

dawnguard.esm

falskaar.esm

moonpath.esm

unofficial skyrim legendary patch

high res texturepack 1,2,3

dbm_mas_patch.esm

dbm_opencities_patch

legacyofthedragonborn

alternate start

apocalypse

auto unequip ammo

becomekingofskyrim.esm

Headbomb's better sort... (8x(think thats cuz of the rename thingies))

bijin npcs

bijin warmaidens

bijin wives

cloaks

convenient horses

dwemertech

extendedui

forgottenmagicredone

guard dialogue overhaul

helgen reborn

treasure hunt

ihud

levelers tower

moonandstar

moonpath

ahzmorehud

open cities skyrim

racemenu

racemenuplugn

skyrim school of witchcraft and wizardry

thunderchild

undeath

violens

werewolfmastery

[/spoiler]

any help would be much appreciated

**Comment by stenenpelle** [comment]
sorry for long post, didnt know that spoiler tags wouldnt work, mb

**Comment by writemorecode** [comment]
Have you sorted your mod order with [LOOT](https://loot.github.io)?

**Comment by stenenpelle** [comment]
Yes i have, but i figured it out just now, alternate start didnt wanna work for whatever reason
