### ISSUE TITLE
IOrganizer methods for python plugin

### ISSUE THREAD

**Issue by GandaG** [TanninOne/modorganizer#916]
I was trying to write a python plugin and access the virtual file system through the listDirectories or findFiles methods but they don't seem to be available. [These](https://i.imgur.com/s3AgDpe.png) are all the attributes I have access to on version 1.3.11 and according to #268 at least findFiles should have been available since 1.3.6

[The very minimal plugin.](http://pastebin.com/eKtByndx)

Am I missing something?

**Comment by TanninOne** [comment]
This function isn't exposed to the python-api yet.

**Comment by GandaG** [comment]
Ok :/ Just a follow-up question, does the vfs exposed to the plugins contain the contents of bsa's or do we still need to extract them?

**Comment by Gernash** [comment]
Can the default color of the Qt framework be changed?

https://doc-snapshots.qt.io/qt5-5.7/qtquickcontrols2-material.html#material-theme-attached-prop ???

Is is it set when compiled?

**Comment by GandaG** [comment]
@Gernash I'm guessing wrong issue :p

**Comment by TanninOne** [comment]
It doesn't. If you have to access the content of a bsa, you have to extract it. MO does ship with a minimal C++ library for doing that, you can look at the bsa_extractor plugin for a sample.

**Comment by GandaG** [comment]
Oh, thanks!
