### ISSUE TITLE
MO2 Style Sheets (qss)

### ISSUE THREAD

**Issue by Gernash** [TanninOne/modorganizer#918]
@TanninOne

does anyone know what section relates to unticked mods in the left pane?
Or if there is code relating to it?

**Comment by Gernash** [comment]
I'm assuming it's to do with this section
I want to have a #color when a mod folder only contanis meta.ini and not loose files or folders



/*
 * QAbstractItemView modifications
 */
QAbstractItemView {
    border: 1px solid #323232;
    selection-color: #bbbbbb;
    selection-background-color: #4b6eaf;
    alternate-background-color: #414547;
    show-decoration-selected: 1;
    outline: 0;
}
QListWidgetItem,
QTreeWidgetItem  {
    background-color: red;
    color: yellow;
    border: 1px solid purple;
}
QAbstractItemView::text {
    color: #bbbbbb;
}
QTreeView::branch:hover,
QAbstractItemView::item:hover {
    background-color: rgba(255, 255, 255, 0.05);
}
QTreeView::branch:selected:active,
QAbstractItemView::item:selected {
    background-color: #4b6eaf;
}

QTreeView::branch:has-siblings:adjoins-item,
QTreeView::branch:has-siblings:!adjoins-item,
QTreeView::branch:!has-children:!has-siblings:adjoins-item {
    border-image: none;
}
QTreeView::branch:has-children:!has-siblings:closed,
QTreeView::branch:closed:has-children:has-siblings {
    border-image: none;
    image: url(:/stylesheet/branch-closed.png);
}
QTreeView::branch:open:has-children:!has-siblings,
QTreeView::branch:open:has-children:has-siblings {
    border-image: none;
    image: url(:/stylesheet/branch-open.png);
}

**Comment by TanninOne** [comment]
I'm afraid you can't. The "mod contains no valid data"-state is not bound to a qt object state (not sure if that would even be possible or how to do it) so the look of that item (italics and dark gray font) is hard coded.

**Comment by Gernash** [comment]
Hard coded as a default style of Qt or MO itself?

**Comment by Gernash** [comment]
Can the default color of the Qt framework be changed?

https://doc-snapshots.qt.io/qt5-5.7/qtquickcontrols2-material.html#material-theme-attached-prop ???

Is is it set when compiled?

**Comment by Gernash** [comment]
@TanninOne 
Ahh been reading now know more... less noob

OK what Qt field is activated when you right click an empty mod and it shows the option Ignore Mossing data..

**Comment by TanninOne** [comment]
It's hard coded in MO. This means without re-compiling MO you cannot change the color of "invalid" mods.
I don't know what you mean by "what Qt field". When you click "Ignore missing data", all MO does is create an empty "textures" folder inside the mod so MO doesn't think it's invalid any more.

**Comment by Gernash** [comment]
@TanninOne 
does the download tab have an identifier?
QTreeView::branch:,QAbstractItemView::item:

**Comment by TanninOne** [comment]
a) QTreeView::branch is not an id of a specific item, its a class of items. It matches all branches in all QTreeViews of the application. You want the identifier of one specific item, right?
b) This question is to imprecise. What do you mean by "the download tab"? The handle with the text "Download"? Or the background pane? Or the list view that contains the saves and sits on the background pane? Or the individual item? And if the latter, than do you mean compact view or regular?

Please try to find your answers yourself, it's not that hard: Look at src/mainwindow.ui, it contains most of the ui (and references to other ui files).  It's an xml file so an xml viewer may be easier to use but you can also use a texteditor.
There you'll find something like <widget class="QTreeView" name="downloadView">
This is the control that contains the downloads (which is probably what you're looking for).
The selector "QTreeView" will match this widget and all other QTreeViews, while "QTreeView#downloadView" will match only this specific item.

If you're interested in the individual items, those are in downloadlistwidget.ui and downloadlistwidgetcompact.ui

**Comment by Gernash** [comment]
@TanninOne

Yep I worked out the QTreeView#downloadView earlier today Can't see how to manipulate it other then move the box around, I will look into the downloadlistwidget.ui etc and play some more.

I was looking at the how to compile MO2 in one of the branches, Is there a list of where to get the dependcies (with the correct versions) somewhere?

**Comment by Gernash** [comment]
@TanninOne 
OK, I've found most of the references eg #PreviewDialog
the ones I cannot find are the Overwrites window(OverwriteInfoDialog? dosen't work for me), configurator and ini Editor, are these tied to some sort of global <class> that controls/ overwrites them?

With QMenu dropdowns I can change the background and borders to the window itself, but the info displayed in them I cannot make transparent to view the QMenu background.

And lastly, I can affect the items in the Download window with #nameLabel but not interact with them i.e. hover,select etc Are these "locked" from mouse interaction other then 'double-click'

I hope this makes sense.

**Comment by Gernash** [comment]
Worked out the Inner frame of the overwrite box but cannot manipulate the main popup box.

**Comment by TanninOne** [comment]
To compile MO2 it's best if you use my "modorganizer-umbrella" project here on github. It's a python script to download and compile all dependencies and MO components automatically. Unfortunately it doesn't work 100% yet but it should get you started.

Regarding qss, I don't really have the answers, I usually work/start with existing sheets from the web.
But please realize that this isn't a html/css interface, styling via stylesheets was an afterthought in Qt afaik, you won't be able to do everything with it.

But when you ask for PreviewDialog or OverwriteInfoDialog you seem to be having a bit of a misunderstanding. The "dialog" is an empty control that hosts other controls, the same way the QTreeView is just a host for the actual data elements. If you want to change, say, a font size you have to change the font size in the actual QButton/QLabel/whatever that contains text! You can't set a fontsize in OverwriteInfoDialog and expect all texts within that dialog to change. Thus there is very little you can do styling a Dialog itself. 
And you don't need to style specific dialog separately. When you style a Button that style applies to all buttons including those in PreviewDialog, OverwriteInfoDialog, IniEditor and Configurator.
The only thing that won't and can't be styled is the external installer as it's a separate non-qt tool.

Regarding the download window: Yes, the download controls are a bit crap because I built them myself and in that code I don't handle a hover event.

**Comment by Gernash** [comment]
@TanninOne 
I'm using the Border to get around not being able to manipulate the Background so I'm attatching to it so if I can't find the frame name then I need to use the dialoge box.

this is it so far http://www.nexusmods.com/fallout4/mods/17375/?

**Comment by Gernash** [comment]
@TanninOne 
Yeay worked out the overwrite Dialogue....

configurator and ini Editor to go. Need hin on these 2 as i'm unable to find the box/dialogue for these

Now staring at the install dialogue box too.....

**Comment by TanninOne** [comment]
@Gernash: I still do not understand what you're doing, you're "using" the "border" to manipulate the "Background"??? I just don't get it. And I don't get why you insist on styling individual dialogues. OverwriteInfoDialog, IniEditorDialog, ConfiguratorDialog, they are ALL QDialogs. Style QDialog once and you're done.
If you need to see the ui files for IniEditor and Configurator: they are plugins so their ui description is in separate repositories. Configurator is in modorganizer_configurator where it has its own ui file.
IniEditor is in modorganizer_inieditor but it's really a single control called "TextViewer" which is defined in modorganizer_uibase.
The same is true for the different installer windows, they are all in plugins

**Comment by Gernash** [comment]
@TanninOne 
Sweet, that did all the main frames then.

Thank you for your assistance. It is greatly appreciated.

Note: I have to attach the pic to the border to be able to scale the picture to window frame size, I believe that is just how QT does it. Otherwise you get multiple pic in the background depending on size.

**Comment by Gernash** [comment]
@TanninOne 
Sorry, I thought I was done bugging you on this topic.

The highlights for the overwriting mods in the main tree view and the highlight in the scroll bar, is there any handles for them ? Or any QtreeView way to selecting them?

**Comment by TanninOne** [comment]
Nope, sorry, those are also hard-coded.

**Comment by Gernash** [comment]
OK, thanks again. You can chalk it up to "Feature request now...."
