### ISSUE TITLE
after win 10 update says dot net outdated/not installed

### ISSUE THREAD

**Issue by sidfu** [TanninOne/modorganizer#919]
windows 10 just had a big update. now always says

dotNet is not installed or the wrong version. This is required to use NCC. Get it from here: http://www.microsoft.com/en-us/download/details.aspx?id=17851

far as i can tell everything still works thou.

ive already treid to reinstall dotnet but says its already installed

**Comment by TanninOne** [comment]
This is about MO1, right? MO1 requires dotnet 3.5 which is fairly outdated now to be able to install certain fomods. The newer dotnet versions are not backwards compatible but you can have several installed in parallel. You need 3.5, which you can get through "Programs & Features"->"Turn windows features on or off"
