### ISSUE TITLE
Fallout 4 Requires Elevation to Run?

### ISSUE THREAD

**Issue by InfinateX** [TanninOne/modorganizer#927]
Whenever I try to boot Fallout 4 through Mod Organizer 2 I get a message saying that the process requires elevation to run, I should try to install the application in a way that does not require elevation as it is a security risk, and then the game boots without loading any of my mods. They seemed to be working up until I tried to switch from manual installation to MO2. I'm not entirely sure what elevation means, but I didn't see anybody else posting about it so I thought it might be an uncommon issue. If it's not actually a problem with the program and anybody could help me get my mods working that would be awesome. I'd hate to go through as much work as I did only to go back to manually installing mods or downloading NMM.

**Comment by Gernash** [comment]
http://forum.step-project.com/topic/11094-wip-fallout-4-using-modorganizer-2/?p=176398

**Comment by InfinateX** [comment]
Gernash, that didn't help me. All it did was remind me to reinstall F4SE, though none of the mods I'm using it require it to be installed so I don't actually need it.

**Comment by InfinateX** [comment]
Got it working. The issue was with logging into Bethesda's servers. I was completely wrong about the elevation having an effect on the way MO2 was loading the mods.

**Comment by CrazyV1ad** [comment]
Fallout 4 Requires Elevation to Run? - Got it working. HOW?????????
