### ISSUE TITLE
Bodyslide doesn't load outfits/bodies in Mod Organizer 2.0.7

### ISSUE THREAD

**Issue by Relentless757** [TanninOne/modorganizer#937]
Tried reinstalling CBBE and bodyslide. Didn't work. Tried changing path, didn't work. Running both as admin so I'm not sure what the problem is.

**Comment by Dragon02022003** [comment]
Run bodyslidex64 and modorganizer as admin. All cbbe related mods must be placed within one mod, I just created an empty mod called CBBE and installed everything in it.

**Comment by Relentless757** [comment]
Was already running them as admin, but thanks anyway. I just checked bodyslide and everything is fine now.
