### ISSUE TITLE
Beta 3: usvfs causing F4 to CTD

### ISSUE THREAD

**Issue by dragonshardz** [TanninOne/modorganizer#939]
Exactly as it says on the tin. Try to launch Fallout 4, game launches and loads ReShade, but as soon as the intro video ends the game crashes to desktop with a message saying "Fallout 4 has stopped working..." and the usual unhelpful information from Windows.

Event Viewer shows an application error with usvfs_x64.dll as the faulting module.

Here's the details I'm seeing right now: 
_Faulting application name: Fallout4.exe, version: 1.7.12.0, time stamp: 0x57ab87bf
Faulting module name: usvfs_x64.dll, version: 0.2.2.0, time stamp: 0x57668a8c
Exception code: 0xc0000005
Fault offset: 0x00000000000dd11f
Faulting process id: 0x3864
Faulting application start time: 0x01d203251a602d68
Faulting application path: D:\Steam\SteamApps\common\Fallout 4\Fallout4.exe
Faulting module path: E:\ModOrganizer\usvfs_x64.dll
Report Id: e8008e9e-a7aa-4c4b-a250-3bc30a873d65
Faulting package full name: 
Faulting package-relative application ID:_

**Comment by dragonshardz** [comment]
Addendum, can launch and play game through Steam just fine and neither MO nor LOOT are detecting missing masters so I really don't know what is going on.

I wish I had better logs to share...

**Comment by Gernash** [comment]
I think I linked the wiki thing to you before...

this section is for odd ball stuff
http://wiki.step-project.com/User:Gernash/MODWiki#Checking_.5CLocal.5CFallout4_Validity
if you have had NMM on the computer or Beth mods installed you need to reset this for the following reson "Because" :)

**Comment by dragonshardz** [comment]
You have linked me the wiki yes. As for NMM or BethSoft mods, I used to have NMM until I discovered MO1 and promptly dropped it. And I don't use any BethSoft mods.

The contents of %appdata%/Local/Fallout 4 are DLCList.txt (which is blank, as I don't own any of the DLCs), Plugins.fo4viewsettings, and Plugins.txt which has Fallout4.esm as the only entry. I can try resetting the folder as your instructions say but I don't expect it to work. :/

**Comment by Gernash** [comment]
I agree, 
This
http://forum.step-project.com/topic/11094-wip-fallout-4-using-modorganizer-2/page-5#entry180082
is a checklist if you have redirected your folders via mklink all that good?

**Comment by dragonshardz** [comment]
Yup, well, all boxes there checked too. I got as far as seeing the power armor before the game crashed with the same error entry in Event Viewer.

**Comment by Gernash** [comment]
loot and fo4edit ned to work so you have to resolve that then everything else will work(if they work then the usvfs is working properly) , if you open FO4edit what do you see?

**Comment by dragonshardz** [comment]
LOOT and FO4Edit work just fine. Launch FO4Edit and it shows all of my mods, loads 'em up with no problems. Hell, even BodySlide works. But the game proper still just crashes with the error.

**Comment by Gernash** [comment]
AHHHHHHH, IR Dumb
if you run Fo4Edit and select all the mods does it bomb out with X mod have to be installed before x esp master?

**Comment by dragonshardz** [comment]
Nope. Loads up all the things without issue. Trust me, if it was a simple missing master, I'd have caught it. Fallout 4 launches without issue if I go through Steam and skip MO entirely, FO4Edit doesn't complain about missing masters, LOOT doesn't either, and nor does MO itself. :)

**Comment by Gernash** [comment]
Yea I'm just doing it step by step so I can link a fault find later Mr guinea pig :)   (No offense intended)

Are you using F4SE,enb,fxshader,shadowboost or any other dll that is loaded in the FO4 installation directory?

**Comment by dragonshardz** [comment]
F4SE, ReShade, and ShadowBoost. No ENB, as I had problems with infinite loading screens with ReShade+ENB installed so had to rename ReShade's dxgi.dll to d3d11.dll to fix them, which necessitated removing ENB.

**Comment by Gernash** [comment]
AH, that's a different issue (proxy dll and such, can help with that too)
IF a game crashed when loading a save then it's a mod related issue
IF a game crashed at menu then it's a plugin/file corruption.

I recommend installing
http://www.nexusmods.com/fallout4/mods/9838/?
Add xinput1_3.dll,ShadowBoost.ini and ShadowBoost.asi to ENB FXAA SweetFX Manager files.txt if you want to backup or remove ShadowBoost with your profile.(that is in the little files box in the right corner)
Hover over the profile 1 box click the save icon then you can name the profile default then save again
Then click the big remove button.
see if it starts....
(you can revert back to you setup with the load button when you hover over the profile.)

**Comment by dragonshardz** [comment]
Tried that. Neat and useful tool, but the game still crashes as soon as it reaches the main menu.

**Comment by Gernash** [comment]
I dont have the issue at all and I use MO2 with f4se,shadowboost,fx and enb
all 4 are installed in the FO4 install directory not MO2 (just had to say that)
I'd backup the ini files and run http://www.nexusmods.com/skyrim/mods/69787/?
to make a new clean set 

after that I'd do a file integrity then run vanilla launcher and reset ini files to base and try that

then I'd scream and delete the fo4 folder and reinstall clean copy

**Comment by Gernash** [comment]
Um your FO4 is not in your program folders?

**Comment by dragonshardz** [comment]
Yeah, it's installed in a different drive. C: is a SSD so I save space by offloading large shit to a HDD. MO isn't on the same drive but I can try moving it over.

**Comment by dragonshardz** [comment]
- New Clean INI files: Still crash.

- File Integrity &c: Checks good, but still crashes.

- Nuke and reinstall: In progress...

**Comment by Gernash** [comment]
MO can't be in the FO4 install directory causes the proxy to doo odd stuff

**Comment by dragonshardz** [comment]
It's not in the install directory, am going to move it to the same drive.

**Comment by Gernash** [comment]
mmm, just off the top of my head comments, is this win 10 or 7?

**Comment by dragonshardz** [comment]
10.

**Comment by Gernash** [comment]
No idea then Id reinstall fallout 4 via steam remove then install in steam i mean. I can't think of any other reason it won't work. there has to be some odd ball file left in the fo4 install folder causing it. 
If fo4edit and loot work then proxt structure works and crashing on load screen is strange has to be a coruption of bad loose file

**Comment by dragonshardz** [comment]
Yeah, trying it now. It looks like there are a couple of SWF files that got left behind in the /Data/Interface folder...I wonder if those were the cause.

**Comment by Gernash** [comment]
swf are usually for pit boy mods.

**Comment by Gernash** [comment]
Oh and NEVER run the creation kit with enb install, your gonna have a bad time

**Comment by dragonshardz** [comment]
Well, even after a complete reinstall the game is still crashing as soon as it gets to the main menu. I still haven't a blue bloody clue why.

**Comment by Gernash** [comment]
I'd go back to basics as it make no sense (unless you have 2gb of ram )
administrative prompt 
chkdsk c:
run ccleaner remove temp files and reg clean
https://www.piriform.com/ccleaner/download
Run adwcleaner
http://www.bleepingcomputer.com/download/adwcleaner/
This is nifty spyware/malware cleaner
reboot

**Comment by dragonshardz** [comment]
I think I figured it out - Settlement Keywords Expanded has a patched version of the Homemaker ESM and MO was loading the original + patched Homemaker ESMs into the game, and that *seems* to have been the cause of the crash at the main menu. So the solution here is if you have a mod entry that overwrites a master file from a different mod, the overwritten master needs to be hidden or the game crashes.

I then turned on the other 9 mods in the set after hiding the original ESM in the Homemaker mod. And it still crashed. So I slowly removed mods until it stopped crashing, and apparently Functional Displays needs a patch for SKE that I can't find.

The strangest thing is that I know for sure the game worked when I initially installed Functional Displays. And then it suddenly didn't.

**Comment by Gernash** [comment]
I use functional display, only thing it plays with is vis and bobblegirl, as far as i've seen

SKE and home maker
ske at bottom of house mode list(overwriting everyother house mod, and top of plugin list
(yes I understand that the overwrite dose not seem to be working for you in mod load order in the left panel.)
I said it before strange......

**Comment by dragonshardz** [comment]
Yeah, I've got it all working now, it's just weird as all hell.

**Comment by Gernash** [comment]
BTW there is this
http://www.nexusmods.com/fallout4/mods/12647/?
I don't use it but have tried it

**Comment by dragonshardz** [comment]
I've tried it as well, it doesn't work as well as it claims to.

**Comment by Gernash** [comment]
@dragonshardz 
Hi I've just had a nightmare...
My Mo2 broke like yours
I installed the August TES5Edit, Both Loot and FO4Edit could not see any mods
Overwrite went screwie
I did a system restore prior to KB3176938
then ran the new FO4edit via TES5Edit.exe -fo4 -edit -l:fr -cp:utf-8
then installed the  KB3176938 with all the other updates for win 10 Pro
and now exerything is working again.

Hope this helps.
