### ISSUE TITLE
Can you relocate the VFS logs?

### ISSUE THREAD

**Issue by Ajajane** [TanninOne/modorganizer#948]
I have Mod Organizer 2 installed on a SSD, with FO4, but the logs folder in MO2 is empty.  Turns out the VFS logs are saving to my SSD that has my OS (C: drive), not the one where MO2 is installed.  This logs folder is taking up almost 30gigs of space, and this is an older SSD with minimal space to begin with.  When I tried to move the logs from C:, MO2 could not find them and wouldn't give me an option to tell it where to look.  This caused all of my mods to turn off, and alphabetized my plugin list and the left pane.  Is there a way to tell MO where to look for these logs?  Thanks.

**Comment by Gernash** [comment]
move the log folder
mklink /J C:\{whatever the original path was}\Fallout 4\logs {whatever the new path is}\logs

**Comment by Gernash** [comment]
Changing the path in setting from default causes issues....

**Comment by Ajajane** [comment]
Awesome, I was able to get it working.  Thanks for the help.  :)
