### ISSUE TITLE
NPCs aren't working (open mouth, freeze, talking)

### ISSUE THREAD

**Issue by quythan97** [TanninOne/modorganizer#949]
i'm playing Skyrim = MO with no mod . But when i'm play the game, NPCs aren't talking and open mounth. It's stuking when i created my chac (quest) because NPCs don't open mounth  and working.I don't know why @@ I use another choise is NMM and it working normal. I don't use any mods, just playing game throught MO and NMM. So can u help me ? I think it's a MO bug. Sorry for my bad grammar xD
**https://youtu.be/BrjnIFEfiJU**

**Comment by quythan97** [comment]
[https://www.youtube.com/watch?v=5c_Xa2NG1ZI](url)

**Comment by GSDFan** [comment]
Not sure if this will help but your left hand pane priority order should follow the order of the plugins. You got them in the wrong order.
Should be Dawnguard, HF, Dragonborn and HRpack 1,2,3.

**Comment by quythan97** [comment]
tks #GSDFan but it doesn't work :)

**Comment by GSDFan** [comment]
In the video you run the game from the Skyrim launcher (play) from inside of MO, are you doing this all the time or was this just for demonstration purposes? The game should be run from either SKSE or Skyrim short cut to load the game.

**Comment by quythan97** [comment]
#GSDFan i test all shortcuts and it still doen't work :)

**Comment by GSDFan** [comment]
You are missing Skyrim - Voices.bsa.

**Comment by quythan97** [comment]
@GSDFan the problem is npcs aren't working when i played = MO, it's normal when i play = Nexus mod manager 
![image](https://cloud.githubusercontent.com/assets/21965403/18236375/7b9fe716-734f-11e6-8d6c-caec6eeca43b.png)

**Comment by GSDFan** [comment]
On the data tab in the video the Skyrim - Voices.bsa is missing. Since it is in the folder and not showing up in MO, try downloading the non installer archive of MO and copy the contents into the installed one on the computer.

Also what are the paths the game and MO are installed in?

**Comment by quythan97** [comment]
@GSDFan if i try to put it in data folder, the game will not work.

**Comment by quythan97** [comment]
i also install new MO. but it seems not working too
