### ISSUE TITLE
MO1 the sidebar thingy is missing?

### ISSUE THREAD

**Issue by yndrelbosch** [TanninOne/modorganizer#950]
The sidebar thing in MO1 is missing? I don't know how to make it appear again...

![Screenshot](http://i.imgur.com/i9iucZ2.png)

**Comment by quythan97** [comment]
![image](https://cloud.githubusercontent.com/assets/21965403/18226502/96463a68-7235-11e6-8113-c73f7e65fcaf.png)
my mouse ?

**Comment by quythan97** [comment]
move u mouse to line from right to left... sorry for my bad grammar

**Comment by yndrelbosch** [comment]
that made absolutely no sense XD but don't worry, I figured it out ~~

**Comment by quythan97** [comment]
![image](https://cloud.githubusercontent.com/assets/21965403/18226528/037e0886-7236-11e6-911b-f0265794759c.png)
