### ISSUE TITLE
Nexus Category not populated 

### ISSUE THREAD

**Issue by Reidlos65** [TanninOne/modorganizer#951]
Installed mods from Nexus are not providing a Category automatically or gives wrong category

**Comment by Gernash** [comment]
that is something you have to do yourself 
or
http://www.nexusmods.com/fallout4/mods/17375/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Ffallout4%2Fajax%2Fmodfiles%2F%3Fid%3D17375&pUp=1

catagories at the bottom

**Comment by Gernash** [comment]
instructions http://wiki.step-project.com/User:Gernash/MODWiki#Adding_all_the_Nexus_categories

**Comment by Reidlos65** [comment]
So even though I changed the path for the downloads, configs etc, the REAL categories.dat only exists in the APPDATA location,  If I place it in its place I moved it it doesnt take effect.

**Comment by Gernash** [comment]
Yep, changing paths dosent work in MO2 correctly. you need to leave the defalt path alone and create a virtual link to where your stuff iis

http://wiki.step-project.com/User:Gernash/MODWiki#Setting_up_your_modding_environment
