### ISSUE TITLE
Query Info Latest Version Error

### ISSUE THREAD

**Issue by Nsamurai** [TanninOne/modorganizer#956]
The short version is this : MJods that have a fairly new version don't always show up in the query info window/process.

Wen I have a newer mod (within the last couple weeks) It is not uncommon to see it is missing info (despite having just downloaded it). I right clik, 'query info', tell it which number is the mod id, and then get slammed with 
![mod organizer wrong version](https://cloud.githubusercontent.com/assets/22090969/18375297/8da8c50e-761a-11e6-9ea4-f52c11318b1e.PNG) 

Which sometimes works, In Context. However, This is quite confusing because I know for a fact that there is a file with exactly this file name and id.  I can do this with a few files (not a big deal), but it happens on almost every newer mod.

Is there a simple cache flush i am missing? Or is a setting I can activate to have Mod Organizer Update it's database?

**Comment by Gernash** [comment]
I've seen this when you dont use the manage download and just download it into the downloads folder.
The issue with different subversions is on the mod auther and the version on the main page.
The only solution I've seen and works with most mods is to unhide the download (remove the download) remove the mod then reinstall it from the nexus mod manager downloader. 
If your manage download button does not work then.

To resolve download manager issue from Nexusmod site I recommend deleting the nxmhandler.ini from C:\ModOrganizer2 and C:\ModOrganizer2Data then run nxmhandler.exe in C:\ModOrganizer2 folder to generate the nxmhandlers.ini files 
extract from http://wiki.step-project.com/User:Gernash/MODWiki#Setting_up_your_modding_environment

**Comment by Nsamurai** [comment]
The second part I did, as I actually just went through your guide to fix loot problems. (saw only vanilla).
As for the first part, well...  That seems to have worked. Could have sworn that It still did that even after redownloading. Huh. Had to reinstall Mod Organizer So many times to fix it the right way (using your guide). Still trying to fix loot crashes though.
Thanks.

**Comment by Gernash** [comment]
@Nsamurai 
NP if you guide specific issues you can ask on the linked STEP forum I can chase it down from there.
