### ISSUE TITLE
downloads not working?

### ISSUE THREAD

**Issue by littlebunnyrawr** [TanninOne/modorganizer#965]
ive linked my account to mod organizer and set everything up and it doesnt download to the manger from the nexus?

**Comment by Gernash** [comment]
last person with the issue had to re-register on the nexus to get it working.

**Comment by littlebunnyrawr** [comment]
re-register?

**Comment by littlebunnyrawr** [comment]
make a new account?

**Comment by Gernash** [comment]
https://github.com/TanninOne/modorganizer/issues/960#issuecomment-246437543
