### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by 123keelos** [TanninOne/modorganizer#987]
- Mod Organizer game switcher (able to switch games)
- Tools such as BSA Unpacking, FOMOD maker, etc

**Comment by TanninOne** [comment]
Yeah, that is far to unspecific as a feature request. What do you think anyone is going to do with "etc"? Do you think there are developers sitting around picking their nose and then see your feature request and go "oh, we could do features? Like 'etc' features? Cool, finally someone is telling us to do 'something'." ?

More seriously though: BSA unpacking is already there, so is a game switcher (kinda) in MO2. A fomod maker could be done just as well as a separate application, there is no real reason to integrate that into MO.
