### ISSUE TITLE
[Feature Request] Select profile from command line

### ISSUE THREAD

**Issue by lupus590** [TanninOne/modorganizer#990]
Biggest wish for this is having MO open my games from desktop shortcut (actually steam shortcut but no difference) and have the correct mod set loaded. Currently, when loading a game from a shorcut (or any other program with MO) the mod profile loaded is the last one which was selected in MO.

I would like to be able to create multiple desktop shortcuts to the same game and be able to also tell MO which profile it should switch to before running the game. Suggested syntax: `-profile "Profile Name"` 

Additional suggestions: if no profile is given the use the existing behaviour, if profile doesn't exist then exit with error message.

**Comment by TanninOne** [comment]
This is already possible, the command line switch is -p
