### ISSUE TITLE
Hey all, just in case you have not noticed, Tannin is now with Nexus

### ISSUE THREAD

**Issue by KeltecRFB** [TanninOne/modorganizer#991]
MO is switching development from individual development into NMM or the next version of NMM.

**Comment by AronaxAE** [comment]
Yeah I am kind of both disappointed and exited at the same time. I bloody hate NMM with a passion, but I hope now that Tannin is working there, he will make it so much better and implement some of MO's features into it. Still hope someone takes control over MO though, or at least someone who can maintain it to keep it working.

**Comment by Gernash** [comment]
http://forum.step-project.com/topic/11469-cat-is-out-of-the-bag/page-2#entry184430

There is hope.......(VFS Like pligin {Fingers crossed})

If they are using QT please expose more of the engine so more stuff can be modified by enduser.....

**Comment by LeFlemard** [comment]
To be precise, they want to include both of managers best point : simplicity of use from NMM, advanced feature from MO (like VFS)

**Comment by TanninOne** [comment]
Ok, but this is an issue tracker not a forum or a news page.
MO is doing nothing, it remains an open source project independent of Nexus here on github, it's just me who's going to work for nexus. If anyone decides to continue working on MO that's fine.
