### ISSUE TITLE
Bug tracker and code repostery.

### ISSUE THREAD

**Issue by gabridello** [TanninOne/modorganizer#992]
please somone can help me? I don't understand what this issue means and how to solve it.

The bug tracker and code repository for Mod Organizer have moved.
Please post bugs to https://github.com/TanninOne/modorganizer/issues now.
Existing open bugs have been imported into that tracker although some state and formatting may have been lost.
The source code has been split into multiple projects on github. Please see here for a complete list: https://github.com/TanninOne/modorganizer

**Comment by TanninOne** [comment]
This is so meta I don't know how to respond to it. You're quoting the explanation on how to report an issue. Which you obviously read because you're actually quoting it in an issue on the mentioned issue tracker... What it is you did't understand eludes me completely
