### ISSUE TITLE
Not mod organiser .

### ISSUE THREAD

**Issue by lurkalot1** [TanninOne/modorganizer#997]
HI TanninOne problem is how did Bethesda get any way with such a Crass Dross loading screen bug . Its not my saves that is bug its Loading srceens that is allways a major issue no matter what you do , I think it is to do with White- run should be re-named CTD CITY . Can run all over map cell navs but go to White that is when CTDS start freezes you can mod the hell out of skyrim eceprt White run ,You name it it it ITS ARRRRRR ups , and horse's dont get me started on horses major bug again GRRRRRR Bethesda. I wish I  knew how to mod Because the first thing I would hit is screen loading . Any way thanks .

**Comment by Akzyra** [comment]
First: Mod Organizer is not activily developed right now, as Tannin is now working on the new Nexus Manager. Yes, a completely new NMM. See the [news ](http://www.nexusmods.com/skyrim/news/12905/?)if you haven't already.


Second: This is a issue tracker for MO, and MO only. Not a mean of contacting one, especially when you are complaining like that. **GitHub is a professional platform for software development.**


Third: Many tutorials and guides exists, I recommend [S.T.E.P](http://wiki.step-project.com/Main_Page). as well. It has many pointers for beginners. Maybe you just have too many mods...

**Comment by TanninOne** [comment]
What he said. ;)
