### ISSUE TITLE
Mod Organizer 2.0 causes Steam Controller to stop sending inputs.

### ISSUE THREAD

**Issue by ashelleyPurdue** [TanninOne/modorganizer#999]
OS: Windows 10

MO version: 2.0.7

Steps to reproduce: Open up MO using the steam controller.  When you click inside MO's window, Windows will start ignoring all inputs from the SC until you click outside it.

**Comment by ace13** [comment]
This is because MO runs as admin, the Steam controller isn't available as an input device for applications running as admin.

**Comment by ashelleyPurdue** [comment]
Interesting, especially considering the old version doesn't have that issue.  Is there any particular reason MO needs to run as admin?

**Comment by TanninOne** [comment]
No official source will tell you to run MO as administrator.

**Comment by ashelleyPurdue** [comment]
Why was this closed, Tannin?  The problem was not resolved.

**Comment by TanninOne** [comment]
No it did not. You may have forgotten that you set up mo to run as admin but mo has no "needs to run as admin" flag so there is nothing to fix
